### ISSUE TITLE
play_mysonos through exception during fetch the favorites

### ISSUE THREAD

**Issue by CannyDuck** [hklages/node-red-contrib-sonos-plus#10]
"play mysonos - error caught from response Details: {"stack":"TypeError: Cannot read property 'startsWith' of undefined\n at sonosPlayer.getFavorites.then.response (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-radio.js:160:37)\n at process._tickCallback (internal/process/next_tick.js:68:7)","message":"Cannot read property 'startsWith' of undefined"}"

**Comment by hklages** [comment]
Hi, what version do you use? Can you send the payload?

**Comment by CannyDuck** [comment]
Using 0.4.4 with RedMatic 5.0.5, Sonos version 10.4.2. I wrote you the payload of a debug node connected to the manage radio node. No you need anything else?

**Comment by hklages** [comment]
I mean the msg you send to the manage_radio node.

**Comment by CannyDuck** [comment]
![image](https://user-images.githubusercontent.com/1655493/67043339-200aa600-f12a-11e9-9b73-62b79e7b4501.png)
A matching radio entry exists:
```
object
id: "2/22"
parentID: "2"
title: "Fritz"
artist: null
album: null
albumArtURI: null
uri: "x-rincon-mp3radio://http://www.fritz.de/live.m3u"
```

"get_mysonos" without topic triggers the same error.

**Comment by hklages** [comment]
I have to do some testing - tomorrow evening I will upload 0.4.5.

**Comment by hklages** [comment]
hmmmm. On my Raspberry Pi everything works fine. But after migrating to RedMatic 4.05 several commands do not work anymore. 
I have to check what the reason is.

**Comment by CannyDuck** [comment]
> How did you manage to get x-rincom-mp3 .... to "My Sonos" list.
I don't like the ad spot TuneIn plays on some stations before the stream starts to play. You can add your personal radio stream using the Sonos Windows client.

I double checked the IP-address. It is the right one, get the same error. An inject node triggering an TuneIn station one the same Sonos node works as aspected.

**Comment by hklages** [comment]
Very good idea, I hate that also but did not know that TuneIn added the ads. 

I will do the same and check whether that causes the error message.

**Comment by hklages** [comment]
Could you please use "get_mysonosall" as payload  and send the fritz box entry  (screen shot or text) .  It seems that the "fritz" entry does not have an "uri" property. Maybe there is another field I can use to activate the station.

**Comment by CannyDuck** [comment]
`1: object
id: "2/22"
parentID: "2"
title: "Fritz"
artist: null
album: null
albumArtURI: null
uri: "x-rincon-mp3radio://http://www.fritz.de/live.m3u"`

**Comment by hklages** [comment]
I was able to add that stream to My Sonos (app - browse  - Radio by Tunein - My Radio Stations - Menu - Add new Radio Station (enter http ... + title) and then add this to My Sonos. 

In version 0.4.5 play_mysonos and get_mysonos works fine on my systems raspberry pi with nodeRed and CCU with Redmatic. 

So there is something else... 
I just submitted a new version only updating "get_mysonos". Please update to 0.4.6, enable debug logging and trigger a "get_mysonos". The log file should then show at which item in the list the error occurs.

**Comment by CannyDuck** [comment]
Thanks for your great support. A added "New Releases" of the Sonos PocketCast integration to my favourites. Here is the error:

`5: object
id: "2/25"
parentID: "2"
title: "New Releases"
artist: null
album: null
albumArtURI: "https://integrations.pocketcasts.com/images/newreleases.png"`

**Comment by hklages** [comment]
Please try the update 0.4.7. Know all items with out uri are ignored. 
I hope that play_mysonos and get_mysonos now works with your My Sonos.

**Comment by CannyDuck** [comment]
It works. Thank you very much.

**Comment by hklages** [comment]
Great. Thanks for the feedback. I am closing this issue now.
