### ISSUE TITLE
Spotify Playlist Error

### ISSUE THREAD

**Issue by MBombeck** [hklages/node-red-contrib-sonos-plus#102]
### Description
I'm trying to stream a Spotify Playlist via a "MySonos" node. The Spotify Playlist is added to "MySonos" and put out on a mysonos.get.items query:
`mysonos.get.items : msg.payload : array[3]
array[3]
0: object
1: object
title: "Kitchen Swagger"
...`

My Flow:
I send a msg.payload with 'Kitchen Swagger' via "Inject Node" to 'mySonos.stream.item'. Unfortunately I get an error msg. in return":
`"mysonos.stream.item:statusCode 500 & upnpError 714 :: Details: unknown error"`

It worked fine with a TuneIn Radio Station. 

### What node/command (topic)/state (payload)

node:  My Sonos 
command:  Kitchen Swagger

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

**what system:** CCU3 with Redmatic (6.0.2)
**node-red-contrib-sonos-plus version:** 4.2.1
**Node-RED version:** 1.1.3

**Comment by hklages** [comment]
Hi. 
Please try mysonos.queue.item oder use mysonos.export item together with universal node group.play.export.

Stations --> stream, Playlists, Album, ...--> queue

**Comment by MBombeck** [comment]
Hej @hklages,

i owe you a beer. mysonos.export together with universal node group.play.export works great.

Thank you!
