### ISSUE TITLE
household.create.group space in player names regex filter

### ISSUE THREAD

**Issue by hunter-hunter** [hklages/node-red-contrib-sonos-plus#103]
### Description
household.create.group does not accept player names with spaces. Other commands don't have a problem with this so I'm wondering if this is intentional or just an oversight.

### What node/command (topic)/state (payload)

node: Universal
command: household.create.group
state: "Break Room,Conference,Foyer,Office"

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

**what system:** Raspberry Pi
**node-red-contrib-sonos-plus version:** 4.2.1
**Node-RED version:** 1.1.3
**NodeJS version:** 12.18.4

**Comment by hklages** [comment]
It was intentionally  - but not one of my best :-)
The new REGEX will allow one blank or hyphen inside the player name and also allow digits.  
Tomorrow I do some tests and then publish it. (4.1.4). Hope that there are no side effects.

**Comment by hklages** [comment]
... please try 4.2.2. Does it work now?

**Comment by hunter-hunter** [comment]
4.2.2 looks to be working great! Thank you for the quick update!

**Comment by hklages** [comment]
Great. Thank you for making me aware of it  and your feedback. I close this issue
