### ISSUE TITLE
Start Radio Station with Stereo Pair

### ISSUE THREAD

**Issue by emmiOU** [hklages/node-red-contrib-sonos-plus#107]
Hi, 

I don't have an issue but would like to ask if there is an opportunity to start playing a radio channel with two paired sonos?
Sorry if this is the wrong place to ask.

I get the following error message:

error: group.play.tunein - could not find given player (must be visible) in any group

Thanks for your help

**Comment by hklages** [comment]
Hi, you are right here :-)

It should be possible right now. Please try Universal node, household.get.groups to see your topology. 
In a stereopair, there is one player hidden, the other one is visible. You have to select the visible one for the commands.

**Comment by emmiOU** [comment]
Well, thanks for your quick reply and thanks for your excellent work.
Works perfectly now

Greetings from Switzerland

**Comment by hklages** [comment]
Welcome. Thanks.
