### ISSUE TITLE
Imported example flows do not expose commands

### ISSUE THREAD

**Issue by jayheavner** [hklages/node-red-contrib-sonos-plus#109]
### Description
Imported nodes have commands that are not visible/editable after importing

### What node/command (topic)/state (payload)

node: Universal | My Sonos
command: any command
state: N/A

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

**what system:** Docker on Ubunu server
**node-red-contrib-sonos-plus version:** 
**Node-RED version:** 
**NodeJS version:** v0.20.8

I've been importing sample flows and I'm noticing that the JSON contains commands but when I import the flows, the commands aren't visible and cannot be edited.

**Comment by hklages** [comment]
Hi. From what page did you get the flows? All flows or a specific one?

What nodeJS version do you use? 0.20.8 is strange. What nodered. Best would be NodeJS 14.x.x and Nodered at least 1.1.x

**Comment by jayheavner** [comment]
Sorry, my node-red version is 0.20.8. It's from 2019. For node, I'm using 10.16.3. Let me pull a new image.

**Comment by jayheavner** [comment]
ok, after pulling a new image node-red:latest I no longer see some of the weirdness I was seeing and I can now see the commands in my nodes. I'm not 100% sure how to upgrade the instance of node the image is using. I'd have to research that a bit.

**Comment by hklages** [comment]
Hi. Perfect. NodeJS 14 would be best, but 10 should work too. 12 would be better. 
When using Docker you can choose node red container #latest but there are also container for different NodeJS versions - see the whole list of images and naming here: 
[Node-RED docker images naming convention](https://github.com/node-red/node-red-docker/blob/master/README.md)
