### ISSUE TITLE
Lenght of Music Libary Playlist

### ISSUE THREAD

**Issue by kickbutts** [hklages/node-red-contrib-sonos-plus#11]
Hi there!
Great Job implementing this Sonos node.
I started playing with it and crashed into a Problem:
I wanted to insert Playlists in the queue from my local NAS. Some Playlists worked without Problems, other would not work. I took me some time to figure it out, but I think i now know the Problem.
You import only the first 100 Playlists.

I took a look into your Code i think the Problem is here:
```
function getMusicLibraryPlaylists (node, msg, sonosPlayer) {
    const sonosFunction = 'get music library playlists';
    sonosPlayer.getMusicLibrary('playlists', { start: 0, total: 100 })
```
in the file sonos-manage-queue.js.
I there a reason you import only 100 Playlists?
Is it possible to make the Array of Playlists longer?
I am not that good at Javascript, but maybe you should use a different Datatype? Not a static type like an Array, more a List or something?

All the Best!

**Comment by hklages** [comment]
Hi, yes there is a limit to 100. 

There are several options -  increase that number or add another property defining the size.  

Lets first some clarity about the error: 
Did you use "insertMusicLibraryPlaylist" as payload? What error message do you receive? Do you really have more than 100 imported playlists (browse --> Music Library --> Imported Playlists)?

**Comment by kickbutts** [comment]
Let me be more precise: Importing the playlists works without a Problem. The first 100 Playlists were imported successfully. I am currently working an a Project for my kids. The Idea is to have some RFID Cards and an RFID Reader (currently using an Raspy, planing to use an ESP32). The kids can use the RFID Cards to start their music.

We have far more than 100 playlists. I can not play playlists which are not imported (obviously). 
So I ask if it is possible to import more playlists.
Using a larger Array is possible, but may not be very efficent. I am not good at JavaScript, but in Java i would use an binary Search Tree for this Problem. I am not sure if a Search Tree can be easily used in JavaScript.

**Comment by hklages** [comment]
Hi, 
... works without a problem: Good to hear. I hate unhandled exceptions :-) 
... binary search tree: I have to stick to the data structures [node-sonos](https://github.com/bencevans/node-sonos) uses.

I added a `msg.size` property. So you can specify the size of the playlist array. If nothing is specified, the default will still be 100.
Now there is also a warning in case the number of imported playlists reaches the maximum size of the array. 

The code is already pushed to Github. Feel free to download as file. I will do some testing, update documentation over the weekend and afterward publish the package. 

... kids: Interesting project. 

Grüße von Mün(chen) nach Mün(ster) Henning
PS: Was man nicht so alles für die Kids macht. Toll!

**Comment by kickbutts** [comment]
Thanks reacting this fast. Works perfect. I know now i have around 500 Playlists.

Grüße zurück nach München.
Werd mal irgendwo eine Beschreibung veröffentlichen, wenn ich das Projekt fertig habe,

**Comment by hklages** [comment]
Great - so I close this issue. 

If veröffentlicht then bitte kurze info :-) Viel Spass.
