### ISSUE TITLE
Malformed albumArtURL 

### ISSUE THREAD

**Issue by hunter-hunter** [hklages/node-red-contrib-sonos-plus#111]
### Description

There appears to be a problem with the album art url returned from group.get.trackplus. I'm not sure if this is an issue with this package directly or with the value returned from the Sonos API. 

An example of the current url returned in msg.payload.albumArtURL is `http://172.16.4.79:1400http://sonosradio.imgix.net/placeholders/fe9cd0a0bbfca70dd863c43e88e65ffa_bg_08.png?w=200&mark-scale=93&mark-align=center,middle&mark=https%3A%2F%2Fapi.napster.com%2Fimageserver%2Fv2%2Falbums%2Falb.444689149%2Fimages%2F600x600.jpg`

There appears to be a few characters missing from between the port number of the Sonos device and the actual album art url hosted somewhere on the internet

### What node/command (topic)/state (payload)

node: Universal 
command: group.get.trackplus 
state: 

### In case of a bug: Are you able to reproduce the error
yes

### Versions and Infrastructure

**what system:** Ubuntu 20.04 
**node-red-contrib-sonos-plus version:** 4.4.0 
**Node-RED version:** 1.1.3 
**NodeJS version:** 12.18.4

**Comment by hklages** [comment]
Thanks. I will fix it by the end of this week end.

In the meantime please replace "http://172.16.4.79:1400http://" by "http://". That should work.

**Comment by hunter-hunter** [comment]
Can confirm that works. That's what I've been doing for now, thank you!

**Comment by hklages** [comment]
Hi. Release 4.5.0 is out including a fix for this issue. 

Be aware: I renamed the property - new name is now artUri. 

I did a lot of changes in the code - hope to achieve more consistency (everywhere the http:// prefix for art). 

Let me know whether it works for your.

**Comment by hunter-hunter** [comment]
4.5.0 looks to have fixed the issue. Thanks for the quick update!

**Comment by hklages** [comment]
Thanks for the update. I close the issue.
