### ISSUE TITLE
group.set.queuemode returns error: "property InstanceID is missing"

### ISSUE THREAD

**Issue by lenaxia** [hklages/node-red-contrib-sonos-plus#112]
### Description
Trying to create a flow to play a playlist and shuffle every time it plays. When I create a universal with "group.set.queuemode: SHUFFLE", I get an error of "property InstanceID is missing." 

Other universal commands work, including group.play.export, group.play, group.pause, etc. 

### What node/command (topic)/state (payload)

node: Universal
command: group.set.queuemode
state: SHUFFLE

### In case of a bug: Are you able to reproduce the error

Yes

### Versions and Infrastructure

**what system:** docker on Synology 
**node-red-contrib-sonos-plus version:** 4.4.0
**Node-RED version:** Latest 1.2.2
**NodeJS version:** v10.22.1

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
Thanks for reporting. A fix is on the way, maybe today.

**Comment by hklages** [comment]
4.5.1 is available now. That should fix it. Feel free to reopen if it does not work.

**Comment by lenaxia** [comment]
It's fixed now. Thanks!
