### ISSUE TITLE
Special characters in player names

### ISSUE THREAD

**Issue by mtjoernelund** [hklages/node-red-contrib-sonos-plus#115]
My understanding (correct me if I am wrong) is for calls to player names are to the player names given in the Sonos app and not the names in the configuration of the individual players in the node. I.e. issuing household.create.group, I need to use the names given to the players in Sonos.

My understanding being correct, I have problems with a couple of player names that contain danish characters. I have a players called Køkken (kitchen), Badeværelse (bathroom) and Soveværelse (bedroom). Shy of changing to english names for these rooms I do not really have anything better to call them. Any chance that the commonly used danish characters æ,ø and å could be implemented as allowed characters?

**Comment by hklages** [comment]
Hi. Yes, you are right. 
I will fix it latest by this week end.

**Comment by mtjoernelund** [comment]
Thanks a lot, greatly appreciated. Just want to thank you for a great add-on. While it is a bit of a steep learning curve, the documentation is great and the node seems really powerful once you get the hang of it, so just thanks!

**Comment by hklages** [comment]
Thanks for the feedback. 4.5.2 has been just published - should be available in some minutes. 
I tested `Køkken`  - that works. Please test the others. 

Hope that now all European characters work - waiting for Chinese people to request support for Chinese characters ;-)
 
If you have any ideas how to make it easier to get started with this node ( I know it is complex ) - let me know. 
What was most "confusing" or "difficult" to understand?

**Comment by mtjoernelund** [comment]
Thank you for the quick update. Will test as soon as I have the chance (good luck adding Chinese characters, and Cyrillic, and...) 

I don't really know how to make it simpler. To be honest I am not sure you really can. I guess this is intended for more complex setups and as such you just need to take the time to read through documentation, which by the way is well written. I'll be trying to set up some more stuff with this and be sure to let you know if I come up with any ideas.

**Comment by mtjoernelund** [comment]
Confirm that letters `æ` and `ø` works. Do not have rooms with å in them at the moment, so cannot confirm this one.

Quick question which actually belongs in another thread, but can you confirm that pulling up an Apple Music playlist saved in My Sonos with the `mysonos.export.item` (it finds the playlist) and exporting it to `group.play.export` will not work, or am I doing something wrong?

**Comment by hklages** [comment]
Thanks for your feedback. 

Regarding: Apple Music playlist. It should work. Please use the SONOS app and browse/search your playlist. After having found use "Add to My Sonos". It should now show up in your My Sonos tab under playlists. Ready for use with mysonos.export.item. 
Does it work?

**Comment by mtjoernelund** [comment]
In that case it seems as if I am doing something wrong or found a bug.

I have a playlist in Apple Music that I have added to My Sonos. The `mysonos.export.item` node finds the playlist, but when it exports it to the universal node, it returns status code 500 and upnpError 714.

![image](https://user-images.githubusercontent.com/6225383/100515219-a2152d00-317a-11eb-9f56-7ec52aea2824.jpeg)

Payload from the mysonos-node:
> {"uri":"x-rincon-cpcontainer:1006206clibraryplaylist%3ap.x5GHEN50Ep?sid=204&flags=8300&sn=3","metadata":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"1006206clibraryplaylist%3ap.x5GHEN50Ep\" parentID=\"10fe2066libraryfolder%3af.4\" restricted=\"true\"><dc:title>Mortens Playlist</dc:title><upnp:class>object.container.playlistContainer.#PlaylistView</upnp:class><desc id=\"cdudn\" nameSpace=\"urn:schemas-rinconnetworks-com:metadata-1-0/\">SA_RINCON52231_X_#Svc52231-0-Token</desc></item></DIDL-Lite>","queue":false}

And error message from the universal-node:
> group.play.export:statusCode 500 & upnpError 714 :: Details: unknown error

Am I doing something wrong here? The same flow works fine if I select a Tune-In Radio stream saved in My Sonos or a Sonos playlist.

**Comment by hklages** [comment]
hmmm. Can you please copy that playload and change "queue":false to "queue":true and inject it to the group.play.export 
Does that work?

**Comment by mtjoernelund** [comment]
Changing queue:false to queue:true did the trick. So a pretty easy work around. Thanks for helping out.

**Comment by hklages** [comment]
Good to hear. Its a bug :-( 
Will fix it with the next release - expected at 2020-12-07.

**Comment by hklages** [comment]
Hi. I have just published 4.5.3. Please check. Now sonos-plus should recognize the "queue" mode automamtically.
