### ISSUE TITLE
group.queue.urispotify results in error

### ISSUE THREAD

**Issue by max-stockhausen** [hklages/node-red-contrib-sonos-plus#116]
### Description
"group.queue.urispotify" results in error message: group.queue.urispotify: not supported type of spotify uri :: Details: none
The right Spotify URI is entered in the documented format: [DOCUMENTATION](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A.1-Universal-Node#groupqueueurispotify)

### What node/command (topic)/state (payload)

node: Universal
command: group.queue.urispotify
state: spotify:playlist:176lwUn78zXXXXXXXXXXXXXXX (truncated, but the right URI copied from Spotify)

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

**what system:** CCU3 with Redmatic
**node-red-contrib-sonos-plus version:**  4.5.2
**Node-RED version:** 1.2.3
**NodeJS version:** 14.15.0

**Comment by hklages** [comment]
Hi - there is a special syntax for playlists - dont know why. 
Please try: 
**spotify:user:**spotify:playlist:176lwUn78zXXXXXXXXXXXXXXX (truncated, but the right URI copied from Spotify)

**Comment by max-stockhausen** [comment]
Thank you for the quick answer!
It works with the additional prefix
