### ISSUE TITLE
group.play.notification starts playing last mp3 as well...

### ISSUE THREAD

**Issue by Vinisz** [hklages/node-red-contrib-sonos-plus#117]
### Description
when playing a group.play.notification, after playing the notifcation, the sonos also plays an mp3 notification which was played before on the sonos.
So, it looks like it just is not looking at the state of the speaker when playing the notification (was it playing or not) and just plays what was already loaded to the speaker after that.

### What node/command (topic)/state (payload)
group.play.notification

### In case of a bug: Are you able to reproduce the error
yes

### Versions and Infrastructure

**what system:** 
**node-red-contrib-sonos-plus version:** 
**Node-RED version:** 
**NodeJS version:** 

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
Hi. What version Node-RED, Node.JS do you use? 

Please explain a bit more what you want to do. 
Notifications are NOT a SONOS build in function. This package saves the current state, plays the given notification and trys to restore the previous state. If - during that time - some other programs or even this package send another play or stop or play  notification the restore might fail. Part of that you can avoid by using a queue node before. See example [here](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification). Part "Serialize messages ..."

**Comment by Vinisz** [comment]
Hi,

 

Ok, I try to explain a little bit more and add some screenshots here.

 

1.	Nothing is playing, but as you can see in the picture, “wasdrogerklaar.mp3” is loaded/last played in “Slaapkamer”
2.	Doorbell rings, Sonos “Slaapkamer” & “Keuken” & “Tuin” play “voordeur.mp3” , this all goes fine
3.	But then, after that , “Slaapkamer” starts playing “wasdrogerklaar.mp3” (which was not playing) , same happens with other devices if previous announcement/mp3 was loaded, it does NOT happen for example with “Keuken” , which has radio loaded (but not playing)
Nothing changed in between.




In the other picture you see what it looks like in node-red. I’m using the official node-red docker container bye the way, version 1.2.3 
What I’m wondering is, does it go wrong maybe because it needs to play the sound on 3 sonos devices, am I maybe not doing that the right way ?
Thanks for helping out already.

 






 



 

 





 

Van: H. Klages <notifications@github.com> 
Verzonden: dinsdag 1 december 2020 17:19
Aan: hklages/node-red-contrib-sonos-plus <node-red-contrib-sonos-plus@noreply.github.com>
CC: Vinisz <vszabang@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [hklages/node-red-contrib-sonos-plus] group.play.notification starts playing last mp3 as well... (#117)

 

Hi. What version Node-RED, Node.JS do you use?

Please explain a bit more what you want to do.
Notifications are NOT a SONOS build in function. This package saves the current state, plays the given notification and trys to restore the previous state. If - during that time - some other programs or even this package send another play or stop or play notification the restore might fail. Part of that you can avoid by using a queue node before. See example here <https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification> . Part "Serialize messages ..."

**Comment by hklages** [comment]
hmmm. Please have a look at github.com - your issue. The "email reply" seems to be in error. I can not see any screen shot.

**Comment by Vinisz** [comment]
> hmmm. Please have a look at github.com - your issue. The "email reply" seems to be in error. I can not see any screen shot.

Sorry, was quite busy... I have added the 2 screenshots now.

**Comment by hklages** [comment]
No problem.

Are the players always grouped or stand alone? I am asking because on your picture it shows "slaapkamer master". 
If they are always grouped you should only send the notification to one (only one) of them.

**Comment by Vinisz** [comment]
They are always ungrouped, it is just named “master” because it is the master bedroom.

**Comment by hklages** [comment]
Please activate debug mode and send me the log ( nrcsplus@gmail.com )
And please upload the export of your small flow (use the <> in this editor)

**Comment by hklages** [comment]
Thats strange. The group.play.notification checks the current playback status of the player (playing, stopped, paused, ...) and restores that status after playing the notification. 

Do you use group.play.notification or joiner.play.notification? 

Is that player grouped? If the player is grouped and not the coordinator, the playback status (playsing, stoppted, ...) is not correct. 

What about adding a group.stop after group.play.notification?

**Comment by GeorgeCastanza** [comment]
Thanks mate. That worked. Putting a group.stop worked with that flow you posted last time.
