### ISSUE TITLE
Turn on/off Google Assistant

### ISSUE THREAD

**Issue by GeorgeCastanza** [hklages/node-red-contrib-sonos-plus#118]
Is it possible to turn on/off Google Assistant in the Sonos players that have Google Assistant built in through Node Red?  This would be helpful, as I have one in the bedroom, and I dont like the LED light on when sleeping.  But I like the option of asking Google questions during the day.

**Comment by hklages** [comment]
Hi. Did you try universal node, `player.set.led` with payload off|on?

**Comment by GeorgeCastanza** [comment]
Yes, it doesnt change the Google Assistant LED, but it does turn off/on the main LED.

**Comment by hklages** [comment]
Understand. I haven`t recognized that additional light. 
What device do you use? 
Is it possible to switch of that light with the standard SONOS IOS,  Android or desktop app?

**Comment by GeorgeCastanza** [comment]
I just looked, and I dont think it's exposed to the app.  So, sadly no.

**Comment by hklages** [comment]
There is no official documentation of the SONOS api. In the internet I could not find anything related. 

What about any mechanical solution: 
a) put an Euro on the light 
b) or if you really only want to cover it during the night and like to use some nonsense gadgets :-) 
[switchbot](https://www.switch-bot.com/products/switchbot-bot). It supports mechanical movements and might be use to cover the light.

**Comment by hklages** [comment]
Seems that we don't have any chance to switch of the light - it is hard wired to the microphone: 

> Currently, there is no way to lock the status of the mic on any voice enabled Sonos device. Currently you only have 2 options, disable the mic on the Arc itself or just like what @AjTrek1 provided, remove voice assistant on the Sonos app. However, what I can do is send this to our engineering team to take a look into as a feature request. Just to set your expectation since our engineering team does not respond to any feature requests. We can subscribe to this thread and our announcement thread for any feature release and up-to-date announcements.

**Comment by hklages** [comment]
Therefore I close this issue.
