### ISSUE TITLE
Support for setLEDState getLEDState?

### ISSUE THREAD

**Issue by ukmoose** [hklages/node-red-contrib-sonos-plus#12]
Many thanks for your efforts in making these nodes.

Any chance you would consider exposing the setLEDState getLEDState commands?

The use case is being able to turn off the sonos LED so as not to disturb people sleeping.  
But still show the sonos is on during the day.

Many thanks

Mark

**Comment by hklages** [comment]
The getLEDState works in my test environment but does not help in your use case. 

For the setLEDState I opened an issue at node-sonos as it throws an exception.
We have to wait for an answer.

**Comment by hklages** [comment]
Hi - have a look at update 0.5.0.  Yesterday node-sonos provided an update and now setting the LED should work. 

I put "set_led" into "controler node", topic should be "On" or "Off".

Sleep well :-)

**Comment by zwok** [comment]
Hijacking this thread to thank you for the work on this node. We use it every day in our house. Looking forward to the Spotify integration!

**Comment by hklages** [comment]
zwok - thanks for your nice feedback. I have opened a separate issue for "Spotifiy". Let me know how you would like to use Spotify and check how to implement.

**Comment by ukmoose** [comment]
Working well!  Many thanks!
