### ISSUE TITLE
Favorites support?

### ISSUE THREAD

**Issue by jpoeppelman1** [hklages/node-red-contrib-sonos-plus#120]
Great node red integration, works fantastic!   Is there any plan to support playing Sonos favorites via command or must I reference the URI instead?

**Comment by hklages** [comment]
Thanks. 

Sonos favorites are already supported. Use node "My Sonos" and command `mysonos.export.item` with payload the title of your favorite. The output can be used as inpurt for "Universal node" and command `group.play.export`

Favorites = the "My Sonos" tab in the offical SONOS App. Right?

**Comment by jpoeppelman1** [comment]
Thank you.

**Comment by hklages** [comment]
Does it work for you? There are more information at the [wiki](https://github.com/hklages/node-red-contrib-sonos-plus/wiki)
