### ISSUE TITLE
Can't play deezer playlist from My Sonos

### ISSUE THREAD

**Issue by watchforstock** [hklages/node-red-contrib-sonos-plus#121]
### Description
I am trying to add a Deezer playlist (called "kid suitable") that I have added to My Sonos. I use the My Sonos node to export the playlist (this works), but when I send that output to the Universal node I get an error saying "group.play.export:statusCode 500 & upnpError 714 :: Details: unknown error".

The export item produces a payload of :

`{"uri":"x-rincon-cpcontainer:10060a6cplaylist_spotify%3aplaylist-6175363444?sid=2&flags=2668&sn=2","metadata":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"10060a6cplaylist_spotify%3aplaylist-6175363444\" parentID=\"10fe2664playlists\" restricted=\"true\"><dc:title>kid suitable</dc:title><upnp:class>object.container.playlistContainer.#DEFAULT</upnp:class><desc id=\"cdudn\" nameSpace=\"urn:schemas-rinconnetworks-com:metadata-1-0/\">SA_RINCON519_X_#Svc519-bb0d1822-Token</desc></item></DIDL-Lite>","queue":false}`

I notice it references "spotify" in the URI - not sure if this is correct or not?

### What node/command (topic)/state (payload)

node: My Sonos and Universal
See example flow here: https://flows.nodered.org/flow/9cba05cb7bfc21fba596d9f25b60684d

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

** Linux 5.4.0-58-generic x86_64
**node-red-contrib-sonos-plus version:** 4.5.4
**Node-RED version:** v1.2.6
**NodeJS version:** v12.20

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
Hi. That's for sure a Spotify playlist.
Do you have/had a Spotify account? And maybe an old Spotify playlist in your My Sonos? 

Can you please do a "mysonos.get.items" and send the output to my email "nrcsplus@gmail.com". 

Can you play the playlist with the official SONOS app and do a (Universal node) group.get.trackplus?

**Comment by watchforstock** [comment]
Hi,

It's funny as I don't think I've ever added a spotify account to Sonos (I think I tried it once, but never paid for it). The playlist shows up as a deezer playlist when I look in the official app.

I'll email you the get items output now. When playing the playlist with the official app and doing group.get.trackplus I get the following:

`{"trackData":{"id":null,"parentID":null,"title":"Titanium","artist":"David Guetta","album":"Virgin Records: 40 Years Of Disruptions","position":4,"duration":246,"albumArtURL":"http://10.14.2.21:1400/getaa?s=1&u=x-sonos-http%3atr%253a71152458.mp3%3fsid%3d2%26flags%3d8224%26sn%3d2","uri":"x-sonos-http:tr%3a71152458.mp3?sid=2&flags=8224&sn=2","queuePosition":1},"artist":"David Guetta","title":"Titanium","artUri":"http://10.14.2.21:1400/getaa?s=1&u=x-sonos-http%3atr%253a71152458.mp3%3fsid%3d2%26flags%3d8224%26sn%3d2","mediaData":{"NrTracks":"104","MediaDuration":"NOT_IMPLEMENTED","CurrentURI":"x-rincon-queue:RINCON_000E58787BA401400#0","CurrentURIMetaData":"","NextURI":"","NextURIMetaData":"","PlayMedium":"NETWORK","RecordMedium":"NOT_IMPLEMENTED","WriteStatus":"NOT_IMPLEMENTED"},"queueActivated":true,"radioId":"","serviceId":"2","serviceName":"Deezer","stationArtUri":"","positionData":{"Track":1,"TrackDuration":"0:04:06","TrackMetaData":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"-1\" parentID=\"-1\" restricted=\"true\"><res protocolInfo=\"sonos.com-http:*:audio/mpeg:*\" duration=\"0:04:06\">x-sonos-http:tr%3a71152458.mp3?sid=2&amp;flags=8224&amp;sn=2</res><r:streamContent></r:streamContent><upnp:albumArtURI>/getaa?s=1&amp;u=x-sonos-http%3atr%253a71152458.mp3%3fsid%3d2%26flags%3d8224%26sn%3d2</upnp:albumArtURI><dc:title>Titanium</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:creator>David Guetta</dc:creator><upnp:album>Virgin Records: 40 Years Of Disruptions</upnp:album></item></DIDL-Lite>","TrackURI":"x-sonos-http:tr%3a71152458.mp3?sid=2&flags=8224&sn=2","RelTime":"0:00:04","AbsTime":"NOT_IMPLEMENTED","RelCount":"2147483647","AbsCount":"2147483647"}}`

Thanks

Andrew

**Comment by hklages** [comment]
.... work around: 

Add a change node between My Sonos export and Universal play export:
The change node should only  set msg.payload.queue =true (boolean value)

**Comment by hklages** [comment]
should be solve with 4.5.5 - just published.
