### ISSUE TITLE
Config NODE did not find any sonos any player under RedMatic on CCU3

### ISSUE THREAD

**Issue by ralfhille** [hklages/node-red-contrib-sonos-plus#122]
I have installed the extension under RedMatic V.1.2.6 on a CCU3.

When configuring the sonos-config node, no Sonos players are found. However, after manually entering the serial number or IP address, the sonos-config node work.

Same Node-Red installation in a DOCKER container works fine.

Does anyone have an idea why it does not run on the CCU3 under Redmatic?

**Comment by hklages** [comment]
Hmmm. It should show the players. I run it also on a CCU3 and it works - as you can see in the picture. 

How complex is your network? Are all player and the CCU in 192.178.168.xx ? Any repeater?
Do you know how to activate the debug mode and get the log file? Upload it or send it to my address nrcsplus@gmail.com and I will check it.

![ccu](https://user-images.githubusercontent.com/17273119/103213642-8da98900-490e-11eb-81ab-b77abba1e8b4.png)

**Comment by hklages** [comment]
Solution: open ports at CCU3. 

I solve this issue.
