### ISSUE TITLE
could not find givenn player in any group :: Details: none

### ISSUE THREAD

**Issue by tbone4711** [hklages/node-red-contrib-sonos-plus#125]
### Description
I've tried to use the xamples from https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-Examples.
So I changed the config node to my system and the mysonos.export.item(green node) worked as expected, but the grey node throws an error with the same config node as the green one.
Did I miss anything to get the gray node working?
Regards,
Tbone

`[{"id":"8bc3d59c.e0ea48","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"f427f799.1bc808","type":"inject","z":"8bc3d59c.e0ea48","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Jerusa","payloadType":"str","x":150,"y":180,"wires":[["b7f0d03a.ff074"]]},{"id":"b7f0d03a.ff074","type":"sonos-manage-mysonos","z":"8bc3d59c.e0ea48","confignode":"92f0ebec.da56d8","compatibilityMode":false,"command":"mysonos.export.item","state":"","stateType":"str","name":"","x":352,"y":184,"wires":[["a28f93b9.4b1d38","7784443c.241e14"]]},{"id":"7784443c.241e14","type":"debug","z":"8bc3d59c.e0ea48","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":610,"y":160,"wires":[]},{"id":"a28f93b9.4b1d38","type":"sonos-universal","z":"8bc3d59c.e0ea48","confignode":"92f0ebec.da56d8","compatibilityMode":false,"command":"group.play.export","state":"","stateType":"str","name":"any","x":590,"y":220,"wires":[[]]},{"id":"92f0ebec.da56d8","type":"sonos-config","name":"SONOS One SL - Esszimmer (L+R)","serialnum":"48-xx-xx-xx-xx-xx-0","ipaddress":"192.168.13.50"}]`

### What node/command (topic)/state (payload)

node: My Sonos 
command: mysonos.export.item
state: error - could not find givenn player in any group

### In case of a bug: Are you able to reproduce the error

every time

### Versions and Infrastructure

**what system:** Docker on Ubuntu
**node-red-contrib-sonos-plus version:** 4.5.4
**Node-RED version:** v1.2.7
**NodeJS version:** v10.23.1

**Comment by hklages** [comment]
Hi. It should work. 

Please post the outcome of "mysonos.export.item" that i can see what service you use. 

Often the trick from #121 works.

**Comment by tbone4711** [comment]
The output is:
`mysonos.export.item : msg.payload : Object
uri: "x-sonosapi-hls-static:catalog%2ftracks%2fB08CMDBSL7%2f?sid=201&flags=0&sn=1"
metadata: "<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="10030000catalog%2ftracks%2fB08CMDBSL7%2f" parentID="1004206ccatalog%2falbums%2fB08CM527DZ%2f%23album_desc" restricted="true"><dc:title>Jerusalema (feat. Nomcebo Zikode)</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON51463_X_#Svc51463-0-Token</desc></item></DIDL-Lite>"
queue: true
`
#121 exchanges the whole msg.payload? If so, I get **group.play.export: uri is missing :: Details: none**

Regards,
Tbone

**Comment by hklages** [comment]
. . . s t r a n g e . .  . 

Can you try this as payload for mysonos "group.play.export" - just a inject node with playload JSON and the value beneth

`{"uri":"x-sonosapi-hls-static:catalog%2ftracks%2fB08CMDBSL7%2f?sid=201&flags=0&sn=19","metadata":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"10030000catalog%2ftracks%2fB08CMDBSL7%2f\" parentID=\"00030000catalog%2ftracks%2fB08CMDBSL7%2f\" restricted=\"true\"><dc:title>Jerusalema (feat. Nomcebo Zikode)</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><desc id=\"cdudn\" nameSpace=\"urn:schemas-rinconnetworks-com:metadata-1-0/\">SA_RINCON51463_X_#Svc51463-0-Token</desc></item></DIDL-Lite>","queue":true}`

**Comment by tbone4711** [comment]
<img width="631" alt="Sonos-Error01" src="https://user-images.githubusercontent.com/25219246/104852996-50795b00-58fe-11eb-9e71-1d5170f90756.png">
Sorry, same error.
-Tbone

**Comment by hklages** [comment]
oh - my fault. 
There is a problem with the player not with the exported item. 

Did you pair the player? 

Try with the ip of the other one.

**Comment by tbone4711** [comment]
Unbelievable, that solved the problem. Thank you for your support.
Do you have any idea where's the problem?

**Comment by hklages** [comment]
When you pair Sonos player, both share the same name, have different ip address and one gets "hidden".  You can see that in the SONOS app. 

So I followed that "behavior" and remove the hidden player from the list. 

That's why you got the message: Could not find player in group. 

If you have any other issue let me know (nrcsplus@gmail.com). 

I close this item.
