### ISSUE TITLE
Trigger Flow After Changes via Sonos App

### ISSUE THREAD

**Issue by peterphilipp** [hklages/node-red-contrib-sonos-plus#126]
This is more of a consulting issue than a bug issue:

Is it possible to trigger a Node Red Flow when the state of the Sonos Nodes are changed via the Sonos App?

BTW great implementation!

**Comment by hklages** [comment]
> ... the state of the Sonos Nodes are changed  ... 
Do you mean the state of a player changed? Volume change, playback change, new track is playing .... ? 

For that I just finished another package [sonos - events ](https://flows.nodered.org/node/node-red-contrib-sonos-events). 

Examples are at Node-REd Import, Examples after installing that package. 

Both packages can be used in parallel. Intention is to merge them, but not in the next 2 months. 

> BTW great implementation!
Thanks!

**Comment by peterphilipp** [comment]
Hi that sound great. I started playing around with it. Looks pretty good so far...
