### ISSUE TITLE
MyTuner Radio or Sonos Radio support?

### ISSUE THREAD

**Issue by mpsamuels** [hklages/node-red-contrib-sonos-plus#127]
Is it possible to play either a MyTuner Radio or Sonos Radio station via the universal node? The number of stations that play properly via TuneIn in my country is decreasing on a daily basis while the same stations being removed from TuneIn are still working on either MyTuner or Sonos Radio so I've found myself moving away from TuneIn recently and using the other platforms instead.

I've had a look through the documentation and can't see anything that seems to hint at how the other radio platforms could be used but am happy to be pointed in the right direction if there is a method that you know works with the other radio players. 

Otherwise, is there any appetite to add support for the use of these other services as part of the universal node, please?

**Comment by hklages** [comment]
Not with the universal node. 

My preferred way is to use the Sonos App, add the stations to My Sonos and use the node My Sonos, mysonos.export.item in combination with Universal, group.play.export. That works for TuneIn, Radioplayer, Sonos Radio and shcould also work for MyTuner. 

Could that be a solution for your?

**Comment by mpsamuels** [comment]
That sounds like that works in theory, thanks 👍 I'll give that a try.
