### ISSUE TITLE
Spotify 

### ISSUE THREAD

**Issue by hklages** [hklages/node-red-contrib-sonos-plus#13]
As I am not a Spotify subscriber please let me know how you would like to use Spotify service in Node-RED. 

You can add your feedback as a comment to this issue. That will help me to prioritize the tasks.

**Comment by zwok** [comment]
Hi, we are using Spotify for 90% of the music that is being played.

It would be great if we could:
- Insert Spotify playlists
- Insert playlists, artists, tracks, albums by their Spotify URI e.g.:
-- spotify:track:4LI1ykYGFCcXPWkrpcU7hn
-- spotify:playlist:5NBncFjcwcgrZZg4odPckW

This functionality is also available in the Sonos HTTP api by jishi (https://github.com/jishi/node-sonos-http-api)
Spotify search might be a cool feature as well but less useful for us.

**Comment by hklages** [comment]
I am working on it but have to do some code consolidation. On 2019-12-01 the packate 1.0.0 will be available and allow insertion of playlists, albums, tracks from My Sonos and most likely also "direct" by uri.

**Comment by zwok** [comment]
Thanks a lot. Looking forward to it.

**Comment by hklages** [comment]
I added the Spotify functionality and published it today. Let me know whether it works on your system. Hint: I changed some property name to have everywhere the camel case notation for properties.

**Comment by zwok** [comment]
Thank a lot! I will try to test it this week and provide you with feedback.

**Comment by zwok** [comment]
Hi, finally managed to setup the spotify functionality. It seems to work like a charm. 
I used a USB Barcode reader connected to a raspberry pi to convert barcodes to songs, albums or playlists on Spotify. This way my kids can turn on some music based on the album cover without needing a phone.

You nodes greatly simplified things for me, so many thanks. We will be using them every day.

**Comment by hklages** [comment]
Hi thanks for the feedback - good to hear that it works for your.
Self-service for kids - great projects! 
I close this issue now.
