### ISSUE TITLE
playerName is not always overriding config node

### ISSUE THREAD

**Issue by AndyMcSchopf** [hklages/node-red-contrib-sonos-plus#131]
### Description
I am using the following flow: https://github.com/kickbutts/Kartenspieler 
To play music using RFID Cards.
I changed the flow because I want to use different MQTT Topic for different Rooms.
But I don't want to make a flow for every Room so I tried to use msg.playerName to choose, using the MQTT Topic, between the Rooms.
This is not working because I always get an UPnP Error if the playerName is different from the used config node.
I hoped to override the config node with using the msg.playerName.

Is this a bug or a feature not implemented yet?

### What node/command (topic)/state (payload)

node: Universal and My Sonos ?

### In case of a bug: Are you able to reproduce the error

yes

**Comment by hklages** [comment]
Hi. In Node-RED it is not possible to use the config name in the way as you want it. 

Therefore I used the SONOS-Playername - see a comparision [here](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/D.-Development#1-player-addressing)
In the example the msg.playerName should be "Bad" while the config name is there "bath".
You can lookup your playerName in the SONOS app or with Universal node  "household.get.groups"

Does that help?

**Comment by AndyMcSchopf** [comment]
@hklages 
Exactly this msg.playerName is what is not working as expected. 
I deside with an Input from MQTT (eg. Sonos/Buero; Sonos/Move)) that the PlayerName is "Move Stereo" (which is the actual SONOS-Playername).
If I feed this (with the Playlist) to the "Kartenspieler"-Flow it is only working when the config node points to the same Player (-> configured config Node).

So when I feed the same flow with an other msg.playerName like "Büro One Stereo" it is not working -> Error "group.play.queue: queue is empty :: Details: none". 
Or in the next.track case - "group.next.track:statusCode 500 & upnpError 711 :: Details: unknown error"

In this Example the config node is the Sonos Move: 

![flow](https://user-images.githubusercontent.com/13237656/108362682-56f83c80-71f4-11eb-8258-5c8053b52ca9.jpg)

Using the Move MQTT (Sonos/Move) works like a charm and as expected:

![flow1](https://user-images.githubusercontent.com/13237656/108363241-fc131500-71f4-11eb-99f6-fa352720afcc.jpg)

So at some point there is the "override" of the node config missing.

**Comment by AndyMcSchopf** [comment]
BTW: when I change all config nodes to "Büro" the Move is not working, but the "Büro"... ;-) So it somehow depends even with msg.playerName set on the config node...

**Comment by hklages** [comment]
Ok. Understand. The My Sonos node does not support msg.playerName. 

Try to replace library.queue.playlist and group.play.queue by library.export.playlist and group.play.export

**Comment by AndyMcSchopf** [comment]
Thanks for your feedback - it worked as you described it. Is there a future plan to use the msg.playerName in My Sonos Node too?

**Comment by hklages** [comment]
Right now: there are no plans. If you come in the situation, where there is no work around like the above  --> let me know and I will check what I can do for you.
