### ISSUE TITLE
Add metadata with group.play.streamhttp

### ISSUE THREAD

**Issue by picto3000** [hklages/node-red-contrib-sonos-plus#138]
### Description
I'm pushing audio only streams from Twitch to my Sonos setup. This is done via an API that generates an m3u8 URL.
It works, but the Sonos app's Now Playing display isn't user friendly as it just shows the generated m3u8 file name as the title, which is a super long token string...

e.g. CpcEWYUACu8_zsyUTd0V0Cjq1P-EZ6QqsPYPbIYaRpV-YAsXDt3EcUVbvUrDR1Fcnrul2NUfMCiI3erNgeBG96rU7VbrRCC_mIpg7iZPg6_FGMBSU2Dj5ytdE9xDRvcvfWr8SUeUSoHutCq0VTXHc2SGbpJoJedNVeH9eQ3d_iy16flIOojEmK5asasJZUKgZjVP3PuG1SzDLbAomgJPO58yp2CpY8WZmgfsKwgpcWVkHm1-UwzmGo1FoZ2mmNh3k1VjlzAU_kTqqRZyn3czTIulhC_jOlSLm5bE5toP0t3_YMblQ88jYc2lNixF_mJESydkRQZvboQ9kMSVW27iuorETIaTYPFxXL01JwNKS84cT3RKTHOeji9J_YHk6zz94KEVmUz7L6DjxL7FFGbnmLvHWinG3VZhV451_ZHDGi5Zn_0B56gNY07JdSO_04UbbEJ78Pw0VMOVCWBSJyzWhBlUpYGwWxFjU7wA4cXp-ObODse7ohcTWAPHi8dUDOSqEhvPItEg_iWt8NMsBe_pA0o8CGrpF3tzQ19C5cK2lbAE_c0ugKVkT5eCcLAabK9_ehPxhrkSLoThmfuK90Jq5-qFGKN9KKXGh4mD5Iw1KA9djMkNSULHVlK82s5gGHMMNnr1tZwOcu7wqyQKcFvucqM9mXiUhPLKebDlEULcfJrEDMpjrSigB5_juxT-z3M8QNmrj6yaInPjSRIQvb7azJAjtWX5RayawgytZxoMRlBaW4Yzhln9sKnl

What I'd like to do is send metadata (title, arturi, service name etc.) along with the URL to the player to better represent what is playing. Is this possible?

API I use for URL generation (you can't use the standard twitch.tv/USERNAME as it is a video link and is not supported by  Sonos):
https://pwn.sh/tools/getstream.html - allows manual creation of URLs
https://pwn.sh/tools/getstream-api.html - API endpoint info

### What node/command (topic)/state (payload)

node: Universal
command: group.play.streamhttp

### In case of a bug: Are you able to reproduce the error

N/A

### Versions and Infrastructure

**what system:** docker
**node-red-contrib-sonos-plus version:** 5.0
**Node-RED version:** 1.2.9

**Comment by hklages** [comment]
Agree - that should be improved.
So you can provide the "title", "artUri" and "station" and they should show up in the Sonos app? 
Give me a few days - need to understand how I can generate metadata. Right now I use just a blank and let Sonos generate it.

**Comment by hklages** [comment]
... will be included in 5.0.1 in a few days: 
you can specify: 
```
msg.info
msg.artUri
```

**Comment by picto3000** [comment]
Brilliant, thanks!

**Comment by hklages** [comment]
5.0.2 is just published.
Does it work for you?

**Comment by picto3000** [comment]
Yes, working as expected. Thanks!

**Comment by hklages** [comment]
Thanks for the feedback - i close the issue..
