### ISSUE TITLE
Support for audioClip

### ISSUE THREAD

**Issue by jnbht** [hklages/node-red-contrib-sonos-plus#139]
Hi, 
i just found your plugin and it looks awesome!
But i could not find anything about the audioClip-Feature from the Sonos Control-API.
Do you support this feature?
If not, do you plan to implement it?

Background:
You can output soundfiles like Mp3 on its own layer with this API call. Without disturbing the queue.
See here, if you want more information:
https://developer.sonos.com/reference/control-api/audioclip/

Cheers

**Comment by hklages** [comment]
This set of nodes sends the SONOS commands direct to the SONOS player as soap request. That's very fast but audioClips are currently not supported by SONOS for this local communication.  There is something similar called group.play.notification. 

Do you have any experience with this new cloud api. That could be the base for a new "plugin".

**Comment by jnbht** [comment]
Not really a lot of experience. It is a bummer, that this command is not available for local requests. I prefer local over cloud.

There is a plug-in that is using this already. Which works reliable for the most part. Sometimes it looses the auth-token and needs to be reauthorised. 
https://github.com/kevinvincent/hassio-addons/blob/master/sonos-audioclip-tts/README.md

I was hoping that there is a local alternative to use this extra notification layer.

**Comment by hklages** [comment]
I consider to create another package using the cloud. 
That will take some month.
