### ISSUE TITLE
Simple flow fails with error message

### ISSUE THREAD

**Issue by watchforstock** [hklages/node-red-contrib-sonos-plus#144]
### Description
With a very simple flow, I'm getting the error "processInputMsg: command is invalid >>undefined  :: Details: none" from the Universal node. My configuration was working, but my nodered machine died so I have deployed the old config it to a new machine - as it's newly set up the versions of both nodered and libraries are probably different, but I don't know what the old ones were at this stage...

### What node/command (topic)/state (payload)

node: Universal
command: group.get.state (but can't get any to work)
state: 

Flow is as follows:

`[{"id":"6ab1427b.71b3dc","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"f895c77.d28ac38","type":"sonos-universal","z":"6ab1427b.71b3dc","confignode":"a31de8cd.fffb68","name":"Kitchen","x":840,"y":200,"wires":[["99b9e111.1a30d"]]},{"id":"af0f1029.71405","type":"inject","z":"6ab1427b.71b3dc","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":500,"y":200,"wires":[["32c5a1c9.1661fe"]]},{"id":"32c5a1c9.1661fe","type":"function","z":"6ab1427b.71b3dc","name":"","func":"msg = {\n    topic: \"group.get.state\",\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":670,"y":200,"wires":[["f895c77.d28ac38"]]},{"id":"99b9e111.1a30d","type":"debug","z":"6ab1427b.71b3dc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1050,"y":200,"wires":[]},{"id":"a31de8cd.fffb68","type":"sonos-config","name":"Kitchen L","serialnum":"00-0E-58-78-7B-A4:2","ipaddress":"10.14.2.21"}]`

### In case of a bug: Are you able to reproduce the error

Yes

### Versions and Infrastructure

**what system:** Linux 4.15.0-141-generic x86_64 (Ubuntu)
**node-red-contrib-sonos-plus version:** 5.0.4
**Node-RED version:** 1.3.2
**NodeJS version:** 12.22.1

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
Hi. 

In the sonos node, field topic: please select "message".
Or just select the command "group.get.state".

I suggest (optionally) that you delete serial number in your config nodes. The IP address overrides them. 

Does it work with these changes?

**Comment by watchforstock** [comment]
Aha! Yes it does. However, for some reason NodeRed wasn't showing me that field option until I refreshed my browser at which point it appeared. Many thanks for your very rapid response!

**Comment by hklages** [comment]
Good to here. I close this issue.
