### ISSUE TITLE
i get a timeout when queue.item and play.queue

### ISSUE THREAD

**Issue by HubertusH** [hklages/node-red-contrib-sonos-plus#145]
### Description
If i send a mysonos.queue.item to play all songs on a network nas i get a timeout by playing the queue.

It seams the queue is not ready so fast. So i work with a workarround: every 3 sec i call group.get.queue an if the payload.length is > 0 i start play.queue again. This works for me but it is a workaround ;-)

### In case of a bug: Are you able to reproduce the error
yes

### Versions and Infrastructure
**what system:** Raspberry Pi 
**node-red-contrib-sonos-plus version:**  5.0.4  
**Node-RED version:** 1.2.9

**Comment by hklages** [comment]
How to you send it? Can you export the flow? 

To play all songs in a NAS you could try to create a playlist and queue that playlist. But there is also a limit for the internal SONOS queue.

**Comment by HubertusH** [comment]
Here the Flow (a part of the "Bad")... the "list" has >= 500 entries. But with my workaround (s.o.) it works.

`[{"id":"e31acdf1.a459d","type":"sonos-universal","z":"35d6d5d8.ffae7a","confignode":"ef902a25.0c8678","command":"group.clear.queue","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":490,"y":480,"wires":[["1e0c90cb.e1782f"]]},{"id":"91bd72fd.587ab","type":"link in","z":"35d6d5d8.ffae7a","name":"Sonos Play Bad","links":["5d2f9ea9.013ab","b46834ca.989a28"],"x":275,"y":480,"wires":[["6f35200.93750e","e31acdf1.a459d"]]},{"id":"1e0c90cb.e1782f","type":"switch","z":"35d6d5d8.ffae7a","name":"Stream/Queue(+)","property":"topic","propertyType":"msg","rules":[{"t":"eq","v":"stream","vt":"str"},{"t":"eq","v":"queue","vt":"str"},{"t":"eq","v":"queue+","vt":"str"}],"checkall":"false","repair":false,"outputs":3,"x":810,"y":480,"wires":[["7f6a21ae.13b85"],["bd382a3a.89ff48","53999329.0cb54c"],[]]},{"id":"6f35200.93750e","type":"debug","z":"35d6d5d8.ffae7a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":330,"y":540,"wires":[]},{"id":"7f6a21ae.13b85","type":"sonos-manage-mysonos","z":"35d6d5d8.ffae7a","confignode":"ef902a25.0c8678","command":"mysonos.stream.item","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1200,"y":480,"wires":[[]]},{"id":"bd382a3a.89ff48","type":"sonos-manage-mysonos","z":"35d6d5d8.ffae7a","confignode":"ef902a25.0c8678","command":"mysonos.queue.item","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1200,"y":540,"wires":[["24176eee.247702"]]},{"id":"53999329.0cb54c","type":"sonos-universal","z":"35d6d5d8.ffae7a","confignode":"ef902a25.0c8678","command":"group.get.queue","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1180,"y":600,"wires":[["a9a805c5.8cdfb8"]]},{"id":"24176eee.247702","type":"debug","z":"35d6d5d8.ffae7a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1430,"y":540,"wires":[]},{"id":"a9a805c5.8cdfb8","type":"function","z":"35d6d5d8.ffae7a","name":"Queue ready","func":"msg.play = (msg.payload.length != 0)\nreturn msg;\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":1450,"y":600,"wires":[["a50f400b.12f1"]]},{"id":"55816370.65cfbc","type":"delay","z":"35d6d5d8.ffae7a","name":"","pauseType":"delay","timeout":"3","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":1460,"y":660,"wires":[["53999329.0cb54c"]]},{"id":"a50f400b.12f1","type":"switch","z":"35d6d5d8.ffae7a","name":"Play True/False","property":"play","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":1660,"y":600,"wires":[["d4011584.e4e778"],["55816370.65cfbc"]]},{"id":"d4011584.e4e778","type":"sonos-universal","z":"35d6d5d8.ffae7a","confignode":"ef902a25.0c8678","command":"group.play.queue","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1890,"y":600,"wires":[[]]},{"id":"ef902a25.0c8678","type":"sonos-config","name":"Bad","serialnum":"B8-E9-37-52-9D-06:B","ipaddress":"10.67.77.45"}]`

**Comment by hklages** [comment]
So you have a list of about 500 songs. You want to add these songs to the SONOS queue and then play them in shuffle or normal order - right. 

Is this list "static" - always the same? You could add in once to the SONOS queue and then use `group.save.queue`  (lets say with name "mybigqueue" to save it. It is then available in My Sonos playlists. And you can "restore" the whole queue with mysonos.export.item payload mybigqueue and playit with group.play.export

**Comment by HubertusH** [comment]
on the NAS are all songs from all my CD's and musik downloads - the list is so not static. it contains today over 7.000 items. i will test it with your option or use my workaround. Thank you. BR Hubertus

**Comment by hklages** [comment]
Reading this: [maximum tracks in SONOS queue](https://en.community.sonos.com/controllers-software-228995/maximum-tracks-in-queue-6838916) you could add all your tracks to the SONOS queue. 

Some weeks a ago I accidentally added about 3000 tracks to the queue - it works but took some seconds.

**Comment by hklages** [comment]
You can use [clementine](https://www.clementine-player.org/). It has "smart playlist" (autogenerated) and one of them is all tracks. Save it as wpl/m3u playlist. This you can insert in SONOS.

**Comment by HubertusH** [comment]
Ok - thank you. i will try the queue - do you have a sample flow how to do this?

**Comment by hklages** [comment]
Use the Sonos App, tab Browse Music, select Music Libary,  Select Songs - then button play and all are in your queue. 
Then you can save the queue and it should be available in My Sonos.

**Comment by HubertusH** [comment]
Ok - thank you for all.
