### ISSUE TITLE
Error "response form parse xml: properties missing. :: Details: none"

### ISSUE THREAD

**Issue by My-Random-Thoughts** [hklages/node-red-contrib-sonos-plus#147]
### Description
I am getting the above error for everything I try.  I am wondering if it's a Sonos version issue as my firmware is quite old (36.4-42130 according to http://< ip >:1400/support)

### What node/command (topic)/state (payload)
node: Universal
command: group.get.state (same error with all commands though)
state: 

### In case of a bug: Are you able to reproduce the error
Yes
### Versions and Infrastructure
what system: docker on Synology
node-red-contrib-sonos-plus version: 5.0.4
Node-RED version: 1.3.1
NodeJS version: v10.24.1

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

[{"id":"9588abce.e4aab8","type":"tab","label":"Sonos","disabled":false,"info":""},{"id":"faa56578.a2f948","type":"inject","z":"9588abce.e4aab8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":200,"y":220,"wires":[["1721cd68.932073"]]},{"id":"1721cd68.932073","type":"sonos-universal","z":"9588abce.e4aab8","confignode":"fd3c504b.135a3","command":"group.get.state","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":400,"y":220,"wires":[[]]},{"id":"fd3c504b.135a3","type":"sonos-config","name":"study","ipaddress":"192.168.1.101"}]

**Comment by My-Random-Thoughts** [comment]
Additionally, I have updated to the latest node 12 version (just in case) and I am getting the same message
Nde-Red: v1.3.3
NodeJS: v12.22.1

**Comment by hklages** [comment]
Hello. 

All "group.*" command use an internal command getGroupsAll and this produces the mentioned error message,  when there is a wrong response from the player. So the reason could be an old SONOS api firmware. Are you able to upgrade? 

Does  `player.get.properties` or `mysonos.export.item` work?

**Comment by hklages** [comment]
In docker on Synology you can set the ENV variable: DEBUG=nrcsp:universal or DEBUG=nrcsp:*
Then in log file/ terminal you can see more detailed error messages.

**Comment by My-Random-Thoughts** [comment]
OK, interesting.  Turning on debugging results in the error message "nrcsp:universal ip address not reachable"
I know the IP is correct, but using the little search buttons next to either the IP or MAC boxes results in "no player found".  I actually have 3 players.

I opened port 1900 on the docker, but still get the same results.

**Comment by hklages** [comment]
What are the docker settings for  that container? 
Does the container use the host network (thats what I do and it works) or do you use a bridge?

Port 1900 is only needed to discover/search player. If you enter a valid ip address the software will work even with blocked port 1900. 

In you nod-red docker container, terminal, new terminal bash: does a ping works?

**Comment by My-Random-Thoughts** [comment]
Redeployed it as using the host network, still the same issue.  However the debug logs now say:

  nrcsp:config error discovery >>{"stack":"Error: nrcsp: response form parse xml: properties missing.
    at parseZoneGroupToArray (/data/node_modules/node-red-contrib-sonos-plus/src/Extensions.js:736:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getGroupsAll (/data/node_modules/node-red-contrib-sonos-plus/src/Commands.js:413:12)
    at async discoverAllPlayerWithHost (/data/node_modules/node-red-contrib-sonos-plus/src/Discovery.js:91:23)","message":"nrcsp: response form parse xml: properties missing."} +319ms
  
 
Thanks for your help btw  :)

**Comment by hklages** [comment]
... what about a ping? 

Does a http node with get, http://up:1400/info work?

**Comment by My-Random-Thoughts** [comment]
Ping does not work in the terminal window for some reason.  It's just showing what I type in as if it were a text editor and not a terminal window

The HTTP request returns:
`{"websocketUrl":"wss:\/\/192.168.xx.xx:1443\/websocket\/api","playerId":"RINCON_5CAAFD2336FC01400","householdId":"Sonos_ifmbHQdSLe1RVEqT3gs68X87PS","groupId":"RINCON_5CAAFD2336FC01400:12"}`

This one works: https://github.com/shbert/node-red-contrib-sonos
It's a pain to use as it would duplicate a lot of code as I can't specify the player to use, your library does.  :)

I have 2x Play:1 and 1x Play:3.
One of the Play:1 is standalone (the one I am testing with), the other two are grouped.  I have not configured that those in Node-Red yet.

**Comment by hklages** [comment]
There seems to be a bug in the getGroupsAll. I will check it tomorrow morning.

**Comment by hklages** [comment]
Please update to 5.0.5 and try the following flow - you only have to modify config node with your ip address: 

`[{"id":"56bafa1b.db6af4","type":"inject","z":"55805384.a4695c","name":"ZoneGroupState","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"player.test","payload":"{\"endpoint\":\"/ZoneGroupTopology/Control\",\"action\":\"GetZoneGroupState\",\"inArgs\":{}}","payloadType":"json","x":140,"y":800,"wires":[["5435d9af.214928"]]},{"id":"5435d9af.214928","type":"sonos-universal","z":"55805384.a4695c","confignode":"f166c7c9.fa00c8","command":"message","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":320,"y":800,"wires":[["ac614d5e.307e2","12acadd6.dddd92"]]},{"id":"ac614d5e.307e2","type":"xml","z":"55805384.a4695c","name":"","property":"payload","attr":"tagAtt","chr":"","x":470,"y":800,"wires":[["9336fa5c.635468"]]},{"id":"9336fa5c.635468","type":"debug","z":"55805384.a4695c","name":" after xml","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":600,"y":800,"wires":[]},{"id":"1dce8629.fb58aa","type":"comment","z":"55805384.a4695c","name":"Modify","info":"Please modify config and use your ip address","x":330,"y":780,"wires":[],"icon":"font-awesome/fa-arrow-down"},{"id":"12acadd6.dddd92","type":"debug","z":"55805384.a4695c","name":"raw","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":470,"y":740,"wires":[]},{"id":"f166c7c9.fa00c8","type":"sonos-config","name":"yourplayer","serialnum":"","ipaddress":"192.168.178.35"}]`

**Comment by My-Random-Thoughts** [comment]
This works and produces output for both, with `after xml` looking good showing all three of my players in their correct groups

**Comment by hklages** [comment]
... please send both output.

**Comment by My-Random-Thoughts** [comment]
RAW:

`{"_msgid":"e3624d8.8761cb","payload":"<ZoneGroups><ZoneGroup Coordinator=\"RINCON_000E58CEE32801400\" ID=\"RINCON_000E58CEE32801400:111\"><ZoneGroupMember UUID=\"RINCON_B8E93739465001400\" Location=\"http://192.168.42.232:1400/xml/device_description.xml\" ZoneName=\"Lounge\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"36.4-42130\" MinCompatibleVersion=\"35.0-00000\" LegacyCompatibleVersion=\"25.0-00000\" BootSeq=\"432\" WirelessMode=\"1\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2472\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"2\"/><ZoneGroupMember UUID=\"RINCON_000E58CEE32801400\" Location=\"http://192.168.42.231:1400/xml/device_description.xml\" ZoneName=\"Kitchen\" Icon=\"x-rincon-roomicon:kitchen\" Configuration=\"1\" SoftwareVersion=\"36.4-42130\" MinCompatibleVersion=\"35.0-00000\" LegacyCompatibleVersion=\"25.0-00000\" BootSeq=\"319\" WirelessMode=\"1\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2472\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"...","topic":"player.test","nrcspCmd":"player.test"}`

AFTER XML:

`{"_msgid":"e3624d8.8761cb","payload":{"ZoneGroups":{"ZoneGroup":[{"tagAtt":{"Coordinator":"RINCON_000E58CEE32801400","ID":"RINCON_000E58CEE32801400:111"},"ZoneGroupMember":[{"tagAtt":{"UUID":"RINCON_B8E93739465001400","Location":"http://192.168.42.232:1400/xml/device_description.xml","ZoneName":"Lounge","Icon":"x-rincon-roomicon:living","Configuration":"1","SoftwareVersion":"36.4-42130","MinCompatibleVersion":"35.0-00000","LegacyCompatibleVersion":"25.0-00000","BootSeq":"432","WirelessMode":"1","WirelessLeafOnly":"0","HasConfiguredSSID":"1","ChannelFreq":"2472","BehindWifiExtender":"0","WifiEnabled":"1","Orientation":"0","RoomCalibrationState":"4","SecureRegState":"2"}},{"tagAtt":{"UUID":"RINCON_000E58CEE32801400","Location":"http://192.168.42.231:1400/xml/device_description.xml","ZoneName":"Kitchen","Icon":"x-rincon-roomicon:kitchen","Configuration":"1","SoftwareVersion":"36.4-42130","MinCompatibleVersion":"35.0-00000","LegacyCompatibleVersion":"25.0-00000","BootSeq":"319","WirelessMode":"1","WirelessLeafOnly":"0","HasConfiguredSSID":"1","ChannelFreq":"2472","BehindWifiExtender":"0","WifiEnabled":"1","Orientation":"0","RoomCalibrationState":"4","SecureRegState":"2"}}]},{"tagAtt":{"Coordinator":"RINCON_5CAAFD2336FC01400","ID":"RINCON_5CAAFD2336FC01400:12"},"ZoneGroupMember":[{"tagAtt":{"UUID":"RINCON_5CAAFD2336FC01400","Location":"http://192.168.42.233:1400/xml/device_description.xml","ZoneName":"Bedroom","Icon":"x-rincon-roomicon:bedroom","Configuration":"1","SoftwareVersion":"36.4-42130","MinCompatibleVersion":"35.0-00000","LegacyCompatibleVersion":"25.0-00000","BootSeq":"285","WirelessMode":"1","WirelessLeafOnly":"0","HasConfiguredSSID":"1","ChannelFreq":"2472","BehindWifiExtender":"0","WifiEnabled":"1","Orientation":"0","RoomCalibrationState":"4","SecureRegState":"2"}}]}]}},"topic":"player.test","nrcspCmd":"player.test"}`

**Comment by hklages** [comment]
Please try 5.0.6

**Comment by My-Random-Thoughts** [comment]
That is currently (limited testing) working perfectly, thank you very much

**Comment by hklages** [comment]
You are welcome. 

It is a special fix for very old firmware :-) 

Please consider to upgrade your firmware to the newest version.  There may be more issues come up. 

If you intend to use node-red-contrib-sonos-events for the event handling you have to wait a bit until I implement the fix there.

**Comment by hklages** [comment]
Thanks for the cappuccin- thats very kind!
