### ISSUE TITLE
is there a way to switch player groups mid playback?

### ISSUE THREAD

**Issue by stoneobscurity** [hklages/node-red-contrib-sonos-plus#15]
i play my audio (via spotify) to my sonos "office" group, but i wanna switch it to the "bedroom" group seamlessly. is there a way to do that?

**Comment by hklages** [comment]
I googled a bit but could not find any solution for that. It looks like a handover.

An idea would be: you add bedroom group to the office group. I hope that that will work seamlessly. 
You can then mute all members of the office group. 
That comes close to your use case but has to be verified. You have to keep in mind that you still need to control the "office group coordinator" to change channels, play, stop, .... etc.

Later you rearrange everything to the original state - but that will not work seamlessly.

**Comment by Heursqem** [comment]
> i play my audio (via spotify) to my sonos "office" group, but i wanna switch it to the "bedroom" group seamlessly. is there a way to do that?

How does the grouping work in SonosPlus. I have two Sonos Play1, but cannot get it to work as a group within SonosPlus Node red on Hassio?

**Comment by hklages** [comment]
Hi, import the following flow and edit the configuration nodes. It will play the station SWR3 in sync on both players. 
Take care: Manage Radio and Get Status use the "leading player". Ctrl Player uses the following player in config file. 

![group flow](https://user-images.githubusercontent.com/17273119/69439471-5221b000-0d47-11ea-84d0-7dd83ab7bc1d.png)


`[{"id":"74efaec6.7c31a","type":"sonos-get-status","z":"4318847d.0693cc","confignode":"32a98882.56e1c8","name":"Get Status Lead Player","x":652,"y":1700,"wires":[["8af22d58.53aff"]]},{"id":"62a1b89.7509d48","type":"change","z":"4318847d.0693cc","name":"play swr3 on leader","rules":[{"t":"set","p":"payload","pt":"msg","to":"play_tunein","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"s24896","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":310,"y":1660,"wires":[["7df282b4.10f7ac"]]},{"id":"ad8671c9.08f85","type":"inject","z":"4318847d.0693cc","name":"trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":143,"y":1660,"wires":[["62a1b89.7509d48"]]},{"id":"7df282b4.10f7ac","type":"sonos-manage-radio","z":"4318847d.0693cc","confignode":"32a98882.56e1c8","name":"Manage Radio Lead Player","x":360,"y":1700,"wires":[["25dbf732.65c418"]]},{"id":"8af22d58.53aff","type":"change","z":"4318847d.0693cc","name":"join_group with new topic","rules":[{"t":"set","p":"topic","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"join_group","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":906,"y":1660,"wires":[["bf85277a.dc7898"]]},{"id":"bf85277a.dc7898","type":"sonos-control-player","z":"4318847d.0693cc","confignode":"8d44022c.adb65","name":"Ctrl Player Following Player","x":961,"y":1700,"wires":[[]]},{"id":"25dbf732.65c418","type":"change","z":"4318847d.0693cc","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"get_name","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":599,"y":1660,"wires":[["74efaec6.7c31a"]]},{"id":"32a98882.56e1c8","type":"sonos-config","z":"","name":"bad","serialnum":"00-0E-58-FE-3A-EA:5","ipaddress":"192.168.178.35"},{"id":"8d44022c.adb65","type":"sonos-config","z":"","name":"wz","serialnum":"94-9F-3E-C1-3B-99:8","ipaddress":"192.168.178.36"}]`

**Comment by Heursqem** [comment]
Thanks hklages, this helps!

**Comment by hklages** [comment]
Thanks for your feedback. I close this topic.
