### ISSUE TITLE
Play Spotify Playlists error

### ISSUE THREAD

**Issue by KoenigTH** [hklages/node-red-contrib-sonos-plus#152]
Since a few weeks I have the issue that I can't play my spotify playlists. In the beginning everythind works fine. The errors show up without any changes on the flows. Querying an album URI still works.

I use group.query.urispotify and as payload I send the following: spotify:user:spotify:playlist:37i9dQZF1DX1htCFhfVtyK

I get the following error message:
"group.queue.urispotify:Sonos error on AddURIToQueue UPnPError 804 (undefined) :: Details: {"stack":"SonosError: Sonos error on AddURIToQueue UPnPError 804 (undefined)\n    at AVTransportService.handleErrorResponse (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/base-service.js:231:23)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async AVTransportService.handleRequestAndParseResponse (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/base-service.js:204:15)\n    at async AVTransportService.SoapRequestWithBody (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/base-service.js:97:16)\n    at async AVTransportService.AddURIToQueue (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/av-transport.service.js..."

**Comment by hklages** [comment]
Hi. 

Does the following flow play the above playlist (ZuHause)? 
What Node-RED version is installed, what node-red-contrib-sonos-plus version?

`[{"id":"7f687dbf.64ec84","type":"inject","z":"ebb42d9b.e3e99","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":1400,"wires":[["4af49319.ea646c"]]},{"id":"4af49319.ea646c","type":"sonos-universal","z":"ebb42d9b.e3e99","confignode":"5a07e409.17a1ec","command":"group.clear.queue","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":300,"y":1400,"wires":[["f47df327.0494a"]]},{"id":"2e871489.84fecc","type":"sonos-universal","z":"ebb42d9b.e3e99","confignode":"5a07e409.17a1ec","command":"group.play.export","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":708,"y":1400,"wires":[[]]},{"id":"f47df327.0494a","type":"change","z":"ebb42d9b.e3e99","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"uri\":\"x-rincon-cpcontainer:1006206cspotify%3aplaylist%3a37i9dQZF1DX1htCFhfVtyK?sid=9&amp;flags=8300&amp;sn=26\",\"metadata\":\"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;1006206cspotify%3aplaylist%3a37i9dQZF1DX1htCFhfVtyK&quot; parentID=&quot;00020000playlist:Zuhause&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Zuhause&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.playlistContainer&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON2311_X_#Svc2311-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;\",\"queue\":true}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":503,"y":1400,"wires":[["2e871489.84fecc"]]},{"id":"2e24ddb0.ae1872","type":"comment","z":"ebb42d9b.e3e99","name":"Modify","info":"use your ip address","x":340,"y":1374,"wires":[],"icon":"font-awesome/fa-arrow-down"},{"id":"ce1c2e6d.ba8ea","type":"comment","z":"ebb42d9b.e3e99","name":"Modify","info":"use your ip address","x":747,"y":1372,"wires":[],"icon":"font-awesome/fa-arrow-down"},{"id":"5a07e409.17a1ec","type":"sonos-config","name":"yourPlayer","serialnum":"","ipaddress":"192.168.178.37"}]`

**Comment by hklages** [comment]
I just got the response from sonos-ts. This issue will be solved in the next release 2.4.1 and has been fixed yesterday with v2.4.1-beta.3. The node-red-contrib-sonos-plus release 5.1.1 will include that fix.

**Comment by KoenigTH** [comment]
> Hi.
> 
> Does the following flow play the above playlist (ZuHause)?
> What Node-RED version is installed, what node-red-contrib-sonos-plus version?
> 
> `[{"id":"7f687dbf.64ec84","type":"inject","z":"ebb42d9b.e3e99","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":1400,"wires":[["4af49319.ea646c"]]},{"id":"4af49319.ea646c","type":"sonos-universal","z":"ebb42d9b.e3e99","confignode":"5a07e409.17a1ec","command":"group.clear.queue","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":300,"y":1400,"wires":[["f47df327.0494a"]]},{"id":"2e871489.84fecc","type":"sonos-universal","z":"ebb42d9b.e3e99","confignode":"5a07e409.17a1ec","command":"group.play.export","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":708,"y":1400,"wires":[[]]},{"id":"f47df327.0494a","type":"change","z":"ebb42d9b.e3e99","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"uri\":\"x-rincon-cpcontainer:1006206cspotify%3aplaylist%3a37i9dQZF1DX1htCFhfVtyK?sid=9&amp;flags=8300&amp;sn=26\",\"metadata\":\"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;1006206cspotify%3aplaylist%3a37i9dQZF1DX1htCFhfVtyK&quot; parentID=&quot;00020000playlist:Zuhause&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Zuhause&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.playlistContainer&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON2311_X_#Svc2311-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;\",\"queue\":true}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":503,"y":1400,"wires":[["2e871489.84fecc"]]},{"id":"2e24ddb0.ae1872","type":"comment","z":"ebb42d9b.e3e99","name":"Modify","info":"use your ip address","x":340,"y":1374,"wires":[],"icon":"font-awesome/fa-arrow-down"},{"id":"ce1c2e6d.ba8ea","type":"comment","z":"ebb42d9b.e3e99","name":"Modify","info":"use your ip address","x":747,"y":1372,"wires":[],"icon":"font-awesome/fa-arrow-down"},{"id":"5a07e409.17a1ec","type":"sonos-config","name":"yourPlayer","serialnum":"","ipaddress":"192.168.178.37"}]`

This one is working, Thanks!

**Comment by KoenigTH** [comment]
> I just got the response from sonos-ts. This issue will be solved in the next release 2.4.1 and has been fixed yesterday with v2.4.1-beta.3. The node-red-contrib-sonos-plus release 5.1.1 will include that fix.

And thank you for the information. I think I can wait till the new release. Then I doensn't have to change my config :)
For me the issue can be marked as solved

**Comment by hklages** [comment]
Thanks for the feedback - i will keep it open as reminder until I have published 5.1.1

**Comment by hklages** [comment]
5.1.1 is published - earlier then planned. I close this issue.
