### ISSUE TITLE
Missing group.restore.snapshot

### ISSUE THREAD

**Issue by schwabelbauch** [hklages/node-red-contrib-sonos-plus#156]
The `universal node` documentation for `group.create.snap` says that it can be restored with `group.restore.snapshot` but this method doesn't exists.
I could use of it to restore a snap without start playing

### Versions and Infrastructure

**what system:** docker/unraid
**node-red-contrib-sonos-plus version:** 5.1.1
**Node-RED version:** 1.3.5
**NodeJS version:** v10.24.1

**Comment by hklages** [comment]
Hi. Thanks for making me aware of that.  The command is "group.play.snap". I updated the documentation. 

If you only want to restore but not playing, submit a "group.stop" before doing the restore. That this state is restored. 

Let me know if it works.

**Comment by schwabelbauch** [comment]
Works for me, thank you

**Comment by hklages** [comment]
Thanks for your feedback!
