### ISSUE TITLE
Syntax error after update of node-red to 1.3.5

### ISSUE THREAD

**Issue by ammawel** [hklages/node-red-contrib-sonos-plus#157]
After updating node-red to version 1.3.5, node-red-contrib-sonos-plus (5.1.1) no longer works.
I get the following error messages in the pallet administration:

```
SyntaxError: Invalid regular expression: /^[\p{L}0-9]+([: -._]{0,1}[\p{L}0-9]+)*(,[\p{L}0-9]+([: -._]{0,1}[\p{L}0-9])*)*$/: Invalid escape (line:13)
SyntaxError: Invalid regular expression: /^[\p{L}0-9]+([: -._]{0,1}[\p{L}0-9]+)*(,[\p{L}0-9]+([: -._]{0,1}[\p{L}0-9])*)*$/: Invalid escape (line:17)
SyntaxError: Invalid regular expression: /^[\p{L}0-9]+([: -._]{0,1}[\p{L}0-9]+)*(,[\p{L}0-9]+([: -._]{0,1}[\p{L}0-9])*)*$/: Invalid escape (line:18)
```

thanks for any help,
Achim

![image](https://user-images.githubusercontent.com/51128844/123539922-76701a80-d73c-11eb-8dee-af151e03327c.png)

**Comment by hklages** [comment]
Hi. 
What environment? iobroker?  what node.JS version?
When does the error occur - during restart node-red?

**Comment by ammawel** [comment]
Hi,

- raspberry pi, stretch
- no iobroker
- node v14.17.1

- back to node-red 1.3.4 and all is fine
- I'm able to edit a file

Thank you 
Achim

**Comment by hklages** [comment]
Hi. 

On Windows Node-Red 1.3.5 works without problems. I will check on Raspberry and NAS on Wednesday, when I return from my short trip. 

You could make a copy  of Globals.js in subdirectory src and the replace the content of " REGEX_CSV (thats what you see in your error message) with the content of "REGEX_ANYCHAR_BLANK". REGEX_CSV is used for   "household.create.goup" and validates the list of players.

**Comment by ammawel** [comment]
Hi, 

very strange: I did the update of node-red with the script from https://nodered.org/docs/getting-started/raspberrypi - afterwards node.js had version 8.17!
A subsequent update of node.js made the error disappear; with node.js version 14.17.1 everything works again.
The error is therefore clearly not in your Sonos module but in the update script from node-red. Until now, the script has worked perfectly.

Please excuse the inconvenience.
Many thanks
Achim

**Comment by hklages** [comment]
Kein Problem. Don't worry - can happen.

Thanks for your feedback
