### ISSUE TITLE
New Function "TEST Sonos Online"?

### ISSUE THREAD

**Issue by gitpower2017** [hklages/node-red-contrib-sonos-plus#16]
Hello,

is it possible to integrate a "TEST Sonos Online" as "Input"?
The function "test_connected" with "Get Status" is not reliable.

The function "TEST Sonos Online" could first perform a PING test. Important would be, that if the PING fails, an OFFLINE comes immediately.

Gruß

**Comment by hklages** [comment]
Hi. Sure -  I am interested to have a reliable function. 

Help me to understand. What does "not reliable" exactly mean?
a) Does NodeRED crashes or throws an exception? In what cases?
b) Is the issue when checking a non-reachable player? Wrong result or "slow"?
c) Is the issue when checking a reachabel player? Wrong result or "slow"?
d) something else. 
Grüße zurück  (gern - falls es einfacher ist - auch in Deutsch)

**Comment by hklages** [comment]
There is also the possibility to send a simple "http://192.168.178.37:1400/info" to check whether a player is available and a SONOS player. As it is fast a request with very short timeOut could solve your issue.

**Comment by hklages** [comment]
... timed out.
