### ISSUE TITLE
Calling "group.play.library.album" with "clearQueue = faslse" resets play position

### ISSUE THREAD

**Issue by My-Random-Thoughts** [hklages/node-red-contrib-sonos-plus#160]
### Description
When calling `group.play.library.album` and setting `clearQueue = false`, selected tracks are added to the queue correctly, but the currently playing track is reset to the start of the queue. 

### What node/command (topic)/state (payload)

node: Universal
command: group.play.library.album
state: ?

### In case of a bug: Are you able to reproduce the error
Yes

### Versions and Infrastructure

**what system:** docker on Linux  -->
**node-red-contrib-sonos-plus version:** 5.11
**Node-RED version:** 2.0.3
**NodeJS version:** 14.17.3

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
It works as designed but maybe the design is not the best :-)
 I use the command `AddURIToQueue`  and parameter `DesiredFirstTrackNumberEnqueued` with value 0
[description](https://svrooij.io/sonos-api-docs/services/av-transport.html#adduritoqueue)

I will return from my trip beginning of next week and then check, what I can do. 
Question: Your queue is playing. You want to add songs to that queue (at beginning? at end?) and the current song should continue to play. 

Maybe for that we need group.queue.library.album without the play /switch to queue command

**Comment by hklages** [comment]
It works as designed but maybe the design is not the best :-)
 I use the command `AddURIToQueue`  and parameter `DesiredFirstTrackNumberEnqueued` with value 0
[description](https://svrooij.io/sonos-api-docs/services/av-transport.html#adduritoqueue)

I will return from my trip beginning of next week and then check, what I can do. 
Question: Your queue is playing. You want to add songs to that queue (at beginning? at end?) and the current song should continue to play. 

Maybe for that we need group.queue.library.album wihthout the play.

**Comment by My-Random-Thoughts** [comment]
I am adding songs to the end of the queue, yes, the currently playing track should not change in state or playing time

Thanks

**Comment by My-Random-Thoughts** [comment]
If you want to have a play with what I am trying to do (with this an #161), the code is below.  It's an album picker to add to or replace the current Sonos queue.  It's still a work in progress, but most of it works.

[{"id":"fa21f67cc8782fbe","type":"tab","label":"Sonos Album Browse","disabled":false,"info":""},{"id":"0b34bee38793a4ba","type":"group","z":"fa21f67cc8782fbe","name":"Return Folder Or Album Data","style":{"stroke":"#0070c0","fill":"#bfdbef","fill-opacity":"0.25","label":true,"color":"#000000"},"nodes":["43bfdfafd2ec84a9","4fabb08ed5718d03","5f21622982e01d8f","788dcbe22360eb3e","205fb101bbe21f41","28cb5a060443c56a","f265ff7f79c03411"],"x":14,"y":719,"w":1092,"h":82},{"id":"26299b2c0e5b86f0","type":"group","z":"fa21f67cc8782fbe","name":"Complie Album / Arists Data From Sonos","style":{"stroke":"#777777","fill":"#d1d1d1","fill-opacity":"0.25","label":true,"color":"#000000"},"nodes":["05e1d93f277db6cb","d2282bb87ad57f8f","b8dbc9136952c9ec","9673d48542d59b24","7f8c35111baa40c1","34a8d90e0e8c3360","1c63b089b7ea9ca1","45129a7cf15949ab","804c3bf3ca515b34","4c9ef48f66064c5c","74d7c3d102b5296d","ac6e3f8c2a6b3764","43285661b29bc646","b2e82774021bda09","3db49bbf5b18c42a","239e8b18c7dc0831","0c86a398524f9c78"],"x":14,"y":119,"w":1092,"h":302},{"id":"3c92b203c044544a","type":"group","z":"fa21f67cc8782fbe","name":"Sonos Music Select (Using Sonos Album Data)","style":{"stroke":"#ffC000","fill":"#ffefbf","fill-opacity":"0.25","label":true,"color":"#000000"},"nodes":["055f3ecf15f89c32","c41a38c30675be86","e9bc4cced5f79e46","2b681d632d7253e8","0e71d1a0b7d5856d","a9549732f8235f1a","62ee2ab90db2df58","dca22beb5abac4b2","50e11dd977477843","3bff05fbb1f0a33f","304c4a5a53ea1f6d","8242763f95e8cfd2","c615526c7e60f330","bfc253a1d80f871d","d409f691b9540db8","f4c3c54bec29d348","fbd6dfe0d6e63c81","f04a30319ee29444","c65d631e340483c3","11a558bb1537068d","48b276972c2b4971","db5fcbcd58f06809"],"x":14,"y":439,"w":1092,"h":262},{"id":"055f3ecf15f89c32","type":"inject","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Go Home","props":[{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"(!home!)","x":180,"y":500,"wires":[["50e11dd977477843"]]},{"id":"c41a38c30675be86","type":"function","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Format List","func":"var list   = [];\nvar path   = flow.get(\"pathSON\");\nvar font1  = `<font size=\"-1\">`;\nvar font2  = `</font>`;\n\nif (path === \"(!home!)\") {\n    flow.set(\"parentSON\", []);\n}\nelse {\n    list.push({\n        \"icon_name\": \"reply\",\n        \"title\": \" ...\",\n        \"menu\": [\n            \"Select\",\n        ]\n    });\n}\n\nmsg.payload.forEach(item => {\n    var newListItem = {};\n    var menu = [\"Add To Queue\", \"Replace Queue\"];\n\n//    if (item.endsWith(\".mp3\")) {\n//        item = item.replace(/(?:.+) - (?:.+) - (.+).mp3/i, \"$1\");\n//        newListItem.icon_name = \"audiotrack\";\n//        menu = [\"Play Next\"];\n//    }\n//    else {\n//        menu.unshift(\"Select\");\n//    }\n\n    if (typeof item === \"string\") {\n        newListItem.title = `${font1}${item}${font2}`;\n        newListItem.icon_name = \"album\";\n        menu.unshift(\"Select\");\n    }\n    else {\n        item.artUri = decodeURIComponent(item.artUri);\n        item.artUri = item.artUri.replace(/&apos;/g, \"'\");\n        item.artUri = item.artUri.replace(/\\+/g, \"%2B\");\n\n        newListItem.title = `${font1}${item.title}${font2}`;\n        newListItem.icon = item.artUri; \n    }\n\n    newListItem.menu = menu;\n    list.push(newListItem);\n});\n\nreturn [\n    {payload: list.length - 1},\n    {payload: list}\n];\n","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":730,"y":540,"wires":[["11a558bb1537068d"],["0e71d1a0b7d5856d"]]},{"id":"e9bc4cced5f79e46","type":"link in","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Set Path","links":["dca22beb5abac4b2"],"x":360,"y":560,"wires":[["2b681d632d7253e8","fbd6dfe0d6e63c81","c65d631e340483c3"]],"l":true},{"id":"2b681d632d7253e8","type":"ui_list","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","group":"f6b99f0cabf72e46","name":"List","order":3,"width":7,"height":9,"lineType":"one","actionType":"menu","allowHTML":true,"outputs":1,"topic":"List","x":530,"y":640,"wires":[["a9549732f8235f1a"]]},{"id":"0e71d1a0b7d5856d","type":"change","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Sort","rules":[{"t":"set","p":"payload","pt":"msg","to":"[payload^(title)]","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":890,"y":560,"wires":[["2b681d632d7253e8"]]},{"id":"a9549732f8235f1a","type":"switch","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Switch","property":"payload.selected","propertyType":"msg","rules":[{"t":"eq","v":"Select","vt":"str"},{"t":"else"}],"checkall":"false","repair":true,"outputs":2,"x":690,"y":640,"wires":[["62ee2ab90db2df58"],["3bff05fbb1f0a33f"]]},{"id":"62ee2ab90db2df58","type":"function","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Select","func":"var path   = flow.get(\"pathSON\");\nvar parent = flow.get(\"parentSON\") || [];\n\nvar title  = msg.payload.title.replace(/<\\/?!?(font)[^>]*>/g, \"\");\n\nif (title === \" ...\") {\n    path = parent.pop();\n}\nelse {\n    parent.push(path);\n    path = title;\n}\n\nflow.set(\"pathSON\", path);\nflow.set(\"parentSON\", parent);\nmsg.topic = path;\nmsg.payload = [];\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":850,"y":620,"wires":[["dca22beb5abac4b2"]]},{"id":"dca22beb5abac4b2","type":"link out","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Set Path","links":["e9bc4cced5f79e46"],"x":1020,"y":620,"wires":[],"l":true},{"id":"50e11dd977477843","type":"change","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Set Path","rules":[{"t":"set","p":"pathSON","pt":"flow","to":"topic","tot":"msg"},{"t":"set","p":"parentSON","pt":"flow","to":"[]","tot":"json"},{"t":"set","p":"payload","pt":"msg","to":"[]","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":360,"y":520,"wires":[["2b681d632d7253e8","fbd6dfe0d6e63c81","c65d631e340483c3"]]},{"id":"3bff05fbb1f0a33f","type":"function","z":"fa21f67cc8782fbe","d":true,"g":"3c92b203c044544a","name":"Operation","func":"// THIS DOES NOT WORK YET\n// STILL A WORK IN PROGRESS\n\nswitch (msg.payload.selected) {\n    case \"Add To Queue\": {\n        msg.topic = \"group.play.library.album\";\n        msg.clearQueue = false;\n        break;\n    }\n\n    case \"Replace Queue\": {\n        msg.topic = \"group.play.library.album\";\n        msg.clearQueue = true;\n        break;\n    }\n\n//    case \"Play Next\": {\n//        msg.topic = \"group.play.library.track\";\n//        msg.clearQueue = false;\n//        break;\n//    }\n\n    default: {\n        msg.topic = \"player.get.volume\";\n    }\n}\n\nmsg.playerName = flow.get(\"playerName\") || null;\nmsg.payload = msg.payload.title;\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":860,"y":660,"wires":[["8242763f95e8cfd2"]]},{"id":"304c4a5a53ea1f6d","type":"ui_dropdown","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Sonos Select","label":"Sonos","tooltip":"","place":"","group":"f6b99f0cabf72e46","order":2,"width":6,"height":1,"passthru":true,"multiple":false,"options":[{"label":"Study","value":"Bedroom","type":"str"},{"label":"Kitchen","value":"Kitchen","type":"str"},{"label":"Lounge","value":"Lounge","type":"str"}],"payload":"","topic":"topic","topicType":"msg","x":110,"y":640,"wires":[["c615526c7e60f330"]]},{"id":"8242763f95e8cfd2","type":"sonos-universal","z":"fa21f67cc8782fbe","d":true,"g":"3c92b203c044544a","confignode":"2fb67e61a2b0d13e","command":"message","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1020,"y":660,"wires":[[]]},{"id":"c615526c7e60f330","type":"change","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Set Player","rules":[{"t":"set","p":"playerName","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":640,"wires":[[]]},{"id":"bfc253a1d80f871d","type":"ui_button","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Go Home","group":"f6b99f0cabf72e46","order":1,"width":1,"height":1,"passthru":false,"label":"","tooltip":"","color":"{{textColors.white}}","bgcolor":"{{backColors.blue}}","icon":"home","payload":"","payloadType":"str","topic":"(!home!)","topicType":"str","x":180,"y":540,"wires":[["50e11dd977477843"]]},{"id":"d409f691b9540db8","type":"link in","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Colour Insert","links":["3ff7b365.0d2e6c"],"x":55,"y":540,"wires":[["bfc253a1d80f871d"]]},{"id":"f4c3c54bec29d348","type":"ui_text","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","group":"f6b99f0cabf72e46","order":5,"width":7,"height":2,"name":"Current Path","label":"Path","format":"{{msg.payload}}","layout":"col-center","x":730,"y":480,"wires":[]},{"id":"f04a30319ee29444","type":"link in","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Return Folder/Album Data","links":["7a0fd38c1f1fccbc","205fb101bbe21f41"],"x":575,"y":540,"wires":[["c41a38c30675be86"]]},{"id":"fbd6dfe0d6e63c81","type":"link out","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Get Folder/Album Data","links":["16b63ba65dcaafd2","788dcbe22360eb3e"],"x":495,"y":540,"wires":[]},{"id":"c65d631e340483c3","type":"function","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Format Path","func":"var path    = flow.get(\"pathSON\");\nvar parent  = flow.get(\"parentSON\");\nvar current = \"\";\n\nif (parent.length > 0) {\n    current = parent.join(\"/\") + `/${path}`;\n}\nelse {\n    current = path;\n}\n\ncurrent = current.replace(\"(!home!)\", \"Home\");\nreturn {payload: current};\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":550,"y":480,"wires":[["f4c3c54bec29d348"]]},{"id":"43bfdfafd2ec84a9","type":"file in","z":"fa21f67cc8782fbe","g":"0b34bee38793a4ba","name":"Load Data","filename":"","format":"utf8","chunk":false,"sendError":false,"encoding":"utf8","allProps":false,"x":370,"y":760,"wires":[["5f21622982e01d8f"]]},{"id":"4fabb08ed5718d03","type":"function","z":"fa21f67cc8782fbe","g":"0b34bee38793a4ba","name":"Return Items","func":"var func = global.get(\"func\");\nvar folderList = [];\n\n// `msg.topcic`  holds the value we are looking for \n// `msg.payload` holds the contents of the loaded JSON file (album (JSON) / artist (STRING))\n\nmsg.payload.forEach(item => {\n    if (typeof item === \"string\") {\n        // ARTIST list\n        item = item.replace(/\\./g, \"\");  // <-- Strange edge case\n        var firstChar = item.substring(0, 1).toUpperCase();\n\n        if ((typeof msg.topic === \"undefined\") || (msg.topic === \"(!home!)\")) {\n            // GET ROOT A-Z Folders\n            firstChar = firstChar.replace(/\\d/, \"#\");    // Change numbers to \"#\"\n            folderList.push(firstChar);\n        }\n        else if (msg.topic.length === 1) {\n            // Get Specific Artist List\n            if (msg.topic === \"#\") {\n                if (firstChar.match(/\\d/)) {\n                    folderList.push(item);\n                }\n            }\n            else {\n                if (firstChar === msg.topic.toUpperCase()) {\n                    folderList.push(item);\n                }\n            }\n        }\n    }\n\n    else if (typeof item === \"object\") {\n        // ALBUM list\n        item.artist = item.artist.replace(/\\./g, \"\");  // <-- Strange edge case\n\n        if (item.artist === msg.topic) {\n            folderList.push(item);\n        }\n    }\n\n    else {\n        // Broken!\n        node.error(\"WTF\", msg);\n    }\n});\n\nvar unique = [...new Set(folderList)];\nunique.sort();\n\nreturn {payload: unique}\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":750,"y":760,"wires":[["205fb101bbe21f41"]]},{"id":"5f21622982e01d8f","type":"json","z":"fa21f67cc8782fbe","g":"0b34bee38793a4ba","name":"Convert JSON","property":"payload","action":"","pretty":false,"x":560,"y":760,"wires":[["4fabb08ed5718d03"]]},{"id":"788dcbe22360eb3e","type":"link in","z":"fa21f67cc8782fbe","g":"0b34bee38793a4ba","name":"Get Folder/Album Data","links":["8102dbccbc3f4c77","d4d52cec5e07cd16","fbd6dfe0d6e63c81"],"x":55,"y":760,"wires":[["28cb5a060443c56a"]]},{"id":"205fb101bbe21f41","type":"link out","z":"fa21f67cc8782fbe","g":"0b34bee38793a4ba","name":"Return Folder/Album Data","links":["f04a30319ee29444","f66f2c3a06d6cbbf"],"x":875,"y":760,"wires":[]},{"id":"28cb5a060443c56a","type":"function","z":"fa21f67cc8782fbe","g":"0b34bee38793a4ba","name":"Select JSON","func":"var parent = flow.get(\"parentSON\") || \"(!home!)\" ;\nvar dataPath = flow.get(\"dataPath\") || \"/data\";\ndataPath = `${dataPath}/music-`;\n\nif (msg.topic.match(/^([#A-Z]|\\(\\!home\\!\\))$/ig)) {\n    if (parent.length <= 1) {\n        msg.filename = `${dataPath}artists.json`;\n    }\n    else {\n        msg.filename = `${dataPath}albums.json`;\n    }\n}\nelse {\n    msg.filename = `${dataPath}albums.json`;\n}\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":190,"y":760,"wires":[["43bfdfafd2ec84a9"]]},{"id":"11a558bb1537068d","type":"ui_text","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","group":"f6b99f0cabf72e46","order":4,"width":0,"height":0,"name":"Count","label":"Result Count","format":"{{msg.payload}}","layout":"row-spread","x":890,"y":520,"wires":[]},{"id":"804c3bf3ca515b34","type":"sonos-manage-mysonos","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","confignode":"2fb67e61a2b0d13e","command":"library.get.albums","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"Get Albums","x":610,"y":220,"wires":[["ac6e3f8c2a6b3764"]]},{"id":"4c9ef48f66064c5c","type":"function","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Get Albums","func":"var index = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\nvar dataPath = flow.get(\"dataPath\") || \"/data\";\ndataPath = `${dataPath}/music-`;\n\nindex.split(\"\").forEach(item => {\n    msg.topic = \"library.get.albums\";\n    msg.payload = `${item}`;\n    msg.searchFor = `${item}`;\n    msg.filename = `${dataPath}raw.json`;\n    node.send(msg);\n});\n\nnode.done();\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":210,"y":220,"wires":[["43285661b29bc646"]]},{"id":"74d7c3d102b5296d","type":"inject","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Update SONOS Albums","props":[{"p":"payload"}],"repeat":"","crontab":"00 04 * * 1","once":false,"onceDelay":0.1,"topic":"","payloadType":"date","x":170,"y":160,"wires":[["4c9ef48f66064c5c"]]},{"id":"ac6e3f8c2a6b3764","type":"function","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Parse Data","func":"var albums = [];\nvar dataPath = flow.get(\"dataPath\") || \"/data\";\ndataPath = `${dataPath}/music-`;\n\nnode.status({\n    fill:  \"blue\",\n    shape: \"ring\",\n    text:  `${msg.searchFor} : ${msg.payload.length}`\n});\n\nmsg.payload.forEach(item => {\n    albums.push({\n        \"id\":     item.id,\n        \"title\":  item.title,\n        \"artist\": item.artist,\n        \"uri\":    item.uri,\n        \"artUri\": item.artUri\n    })\n})\n\nmsg.payload = albums;\nmsg.filename = `${dataPath}raw.json`\nnode.status({});\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":810,"y":220,"wires":[["b2e82774021bda09"]]},{"id":"43285661b29bc646","type":"delay","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":410,"y":220,"wires":[["804c3bf3ca515b34","05e1d93f277db6cb"]]},{"id":"b2e82774021bda09","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Save RAW","filename":"","appendNewline":false,"createDir":false,"overwriteFile":"false","encoding":"utf8","x":1010,"y":220,"wires":[[]]},{"id":"d2282bb87ad57f8f","type":"file in","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Load RAW","filename":"","format":"utf8","chunk":false,"sendError":false,"encoding":"utf8","allProps":false,"x":310,"y":340,"wires":[["b8dbc9136952c9ec"]]},{"id":"b8dbc9136952c9ec","type":"change","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Fix JSON","rules":[{"t":"change","p":"payload","pt":"msg","from":"[]","fromt":"str","to":"","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"][","fromt":"str","to":",","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":",,","fromt":"str","to":",","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":480,"y":340,"wires":[["7f8c35111baa40c1"]]},{"id":"9673d48542d59b24","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Save Albums","filename":"","appendNewline":false,"createDir":false,"overwriteFile":"true","encoding":"utf8","x":1010,"y":340,"wires":[[]]},{"id":"7f8c35111baa40c1","type":"json","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Convert","property":"payload","action":"","pretty":false,"x":640,"y":340,"wires":[["34a8d90e0e8c3360"]]},{"id":"34a8d90e0e8c3360","type":"function","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Get Unique","func":"function getUniqueList(array, key, returnAll) {\n    if (returnAll === true) {\n        // Return ALL objects \n        return [...new Map(array.map(item => [item[key], item])).values()];\n    }\n    else {\n        // Return just the item\n        return [...new Map(array.map(item => [item[key], item[key]])).values()];\n    }\n}\n\nvar albums = {};\nvar artists = {};\nvar dataPath = flow.get(\"dataPath\") || \"/data\";\ndataPath = `${dataPath}/music-`;\n\nalbums.payload = getUniqueList(msg.payload, \"id\", true);\nartists.payload = getUniqueList(albums.payload, \"artist\", false);\n\nalbums.filename = `${dataPath}albums.json`;\nartists.filename = `${dataPath}artists.json`;\n\nnode.status({\n    fill:\"green\",\n    shape:\"dot\",\n    text:`Albums: ${albums.payload.length}, Artists: ${artists.payload.length}`\n});\n\nreturn [\n    {\"filename\": `${dataPath}raw.json`},\n    albums,\n    artists,\n];\n","outputs":3,"noerr":0,"initialize":"","finalize":"","libs":[],"x":810,"y":340,"wires":[["1c63b089b7ea9ca1"],["9673d48542d59b24"],["45129a7cf15949ab"]]},{"id":"05e1d93f277db6cb","type":"trigger","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Trigger","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"5","extend":true,"overrideDelay":false,"units":"s","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":420,"y":280,"wires":[["d2282bb87ad57f8f"]]},{"id":"1c63b089b7ea9ca1","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Delete RAW","filename":"","appendNewline":true,"createDir":false,"overwriteFile":"delete","encoding":"none","x":1010,"y":300,"wires":[[]]},{"id":"45129a7cf15949ab","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Save Artists","filename":"","appendNewline":false,"createDir":false,"overwriteFile":"true","encoding":"utf8","x":1010,"y":380,"wires":[[]]},{"id":"3db49bbf5b18c42a","type":"inject","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"RESET","props":[{"p":"reset","v":"true","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":230,"y":260,"wires":[["43285661b29bc646"]]},{"id":"239e8b18c7dc0831","type":"comment","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"What This Does","info":"## TOP ROW\nNOTE: This should only need to run once a week or so depending on how often you update your Sonos library.\n\nFirst this runs though the `0-9`/`A-Z` list and passes that as a search to the \"`library.get.albums`\" topic of the MySonos node.\nThe node will then return all albums that contain the specified character - maxing out at 1000.\nThis of course will create a lot of duplicate entries.\n\nSpecific details are then saved to a file called \"`/data/music-raw.json`\"\n\n---\n\n## TRIGGER\nOnce the list as been completed, the trigger will fire after 5 seconds and kick off the second part of the group.\n\n---\n\n## BOTTOM ROW\nFirst the raw file from earlier is loaded as plain text.\nIt then fixes the JSON issues that are present and converts it in to an object.\n\nNext, using a simple function we remove all duplicate enries using the album art URL as the unique key.\n\nThe list of artists and albums are then separated and saved into \"`/data/music-artists.json`\" and \"`/data/music-albums.json`\"\n","x":1000,"y":160,"wires":[]},{"id":"f265ff7f79c03411","type":"comment","z":"fa21f67cc8782fbe","g":"0b34bee38793a4ba","name":"What This Does","info":"## INPUT\n`msg.payload` comes in as an object to search for.  Using rules we can determine if we should search the Albums or Artists list.\nOnce a list is determined, it's then loaded and searched, returning any and all results.\n\n---\n\n## OUTPUT\nZero or more items that match the input query","x":1000,"y":760,"wires":[]},{"id":"48b276972c2b4971","type":"comment","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"What This Does","info":"Magic","x":1000,"y":480,"wires":[]},{"id":"db5fcbcd58f06809","type":"comment","z":"fa21f67cc8782fbe","g":"3c92b203c044544a","name":"Branch to group below","info":"","x":535,"y":540,"wires":[],"icon":"font-awesome/fa-arrow-down","l":false},{"id":"516b92a66a6c49cd","type":"comment","z":"fa21f67cc8782fbe","name":"IMPORTANT","info":"- Make sure the \"`Get Albums`\" SONOS node is configured for your system.\n\n- Ensure the data path is available and writtable.\nThe default is `/data`, but you can choose any local path at all.\nMust start with a slash\n\n","x":110,"y":60,"wires":[]},{"id":"c2d7416e736734ba","type":"inject","z":"fa21f67cc8782fbe","name":"START","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":310,"y":60,"wires":[["6305dd22e238f632"]]},{"id":"6305dd22e238f632","type":"change","z":"fa21f67cc8782fbe","name":"SET DATA PATH","rules":[{"t":"set","p":"dataPath","pt":"flow","to":"/data","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":490,"y":60,"wires":[["ecb794aa9393720c"]]},{"id":"ecb794aa9393720c","type":"link out","z":"fa21f67cc8782fbe","name":"Start","links":["0c86a398524f9c78"],"x":635,"y":60,"wires":[]},{"id":"0c86a398524f9c78","type":"link in","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Start","links":["ecb794aa9393720c"],"x":75,"y":220,"wires":[["4c9ef48f66064c5c"]]},{"id":"889d962e585c08a5","type":"ui_spacer","z":"fa21f67cc8782fbe","name":"spacer","group":"","order":1,"width":1,"height":1},{"id":"f6b99f0cabf72e46","type":"ui_group","name":"Sonos (Sonos)","tab":"3a7528249e158cdf","order":3,"disp":true,"width":7,"collapse":false},{"id":"2fb67e61a2b0d13e","type":"sonos-config","name":"Sonos 1","serialnum":"","ipaddress":"1.2.3.4"},{"id":"3a7528249e158cdf","type":"ui_tab","name":"Sonos","icon":"speaker","order":1,"disabled":false,"hidden":false}]

**Comment by hklages** [comment]
The next release 5.2.0 has a new command: group.queue.library.album. 
That will enqueue the songs at the end of the queue and does not change the current position. 

Most likely 5.2.0 will be available end of this week.

**Comment by hklages** [comment]
5.2.0 is available. 
Does it solve your issue?

**Comment by My-Random-Thoughts** [comment]
Sorry no, it is replacing the entire queue

`{"_msgid":"3d6087dcea578a8d","playerName":"Bedroom","payload":"Fever Dream","topic":"group.queue.library.album","nrcspCmd":"group.queue.library.album"}`

**Comment by hklages** [comment]
grrrr- there was a typo. Please try 5.2.1

**Comment by My-Random-Thoughts** [comment]
Thanks again, but same issue - it's replacing the queue.

**Comment by hklages** [comment]
Do you use clearQueue false?

**Comment by My-Random-Thoughts** [comment]
Doh, I am so sorry.
It works now that I am using it correctly.

Thank you very much for the quick fix!
