### ISSUE TITLE
Mute state is not restored by snapshot restore

### ISSUE THREAD

**Issue by johnekarlsson** [hklages/node-red-contrib-sonos-plus#162]
### Description
If I create a snapshot (including mute states) and then restores the same speakers using that snapshot (while verifying that the mute states was indeed saved as expected) everything except mute state is restored.

### What node/command (topic)/state (payload)

node: Universal
command: group.play.snap

### In case of a bug: Are you able to reproduce the error
Yes. See below.

[{"id":"4b4c1b5d.861abc","type":"inject","z":"9b6d0e72.53658","name":"","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":150,"y":880,"wires":[["eda3da6c.58512"]]},{"id":"eda3da6c.58512","type":"change","z":"9b6d0e72.53658","name":"Inputs","rules":[{"t":"set","p":"snapVolumes","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"snapMutestates","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":880,"wires":[["4bffcef7.8e497"]]},{"id":"4bffcef7.8e497","type":"sonos-universal","z":"9b6d0e72.53658","confignode":"5840e176.b33fa8","command":"group.create.snap","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"Create snapshot","x":470,"y":880,"wires":[["575fd7d5.46bfe8"]]},{"id":"575fd7d5.46bfe8","type":"sonos-universal","z":"9b6d0e72.53658","confignode":"5840e176.b33fa8","command":"group.play.snap","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"Play snapshot","x":660,"y":880,"wires":[[]]},{"id":"5840e176.b33fa8","type":"sonos-config","name":"LivingRoom","serialnum":"5C-AA-FD-11-06-E3:A","ipaddress":"192.168.0.243"}]

### Versions and Infrastructure

**what system:** Raspberry pi, running Home assistant (Linux 5.10.17-v8 aarch64)
**node-red-contrib-sonos-plus version:** 5.1.1
**Node-RED version:** 1.3.5
**NodeJS version:** v14.17.1

**Comment by hklages** [comment]
Right now I dont have access to my systems - will check it beginning of next week.

**Comment by hklages** [comment]
Thanks for reporting it. 

Yes, it is a bug, will be fixed in 5.2.0 available latest end of this week

**Comment by johnekarlsson** [comment]
Fantastic! Thanks, and thanks for a great component!

**Comment by hklages** [comment]
5.2.0 is now availalble.
Does ist solve your issue?

**Comment by johnekarlsson** [comment]
Yes! Perfect! Thanks again!
