### ISSUE TITLE
Request:   All SONOS states in return message

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hklages/node-red-contrib-sonos-plus#167]
Hi,

I'm using your node now for a while and have realized that for some flows I have to request different states in individual calls.

Would it be possible to return ALL Sonos states in a single return message?

Thanks for considering

**Comment by hklages** [comment]
Hi. 

What is "all"? 
Which do you need?

**Comment by hklages** [comment]
> The more the better ;)

The more the slower ;). 

To get all states with each command is not feasible. That will totally overload the SONOS system. 

Option 1: 
You use this [node ](https://flows.nodered.org/node/node-red-contrib-sonos-events) in addition. You subscribe to all needed events (states) and store them in one or more local node-red variables (JSON). On a change you just update that variable.   

In you flows you then don't need to send any "get state" command to your SONOS player, instead you just read your local variable. Thats ultra fast and could be convenient. That should also work for multiply player without overloading the system.  

Would that option work for you? 

Option 2: 
I create a compound command, where you can specify the states you need and provide the results in JSON. So everyone can choose what works for them - taking performance in account. 
Right now I think Option 1 is better. 

Your opinion?

**Comment by xX-Nexus-Xx** [comment]
Option 1 is exactly what I already have done and works well .. but with any of your changes I have to review and revise :(

I can live with that , I understand the Option 2 has a performance impact

thanks for considering
