### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by GeorgeCastanza** [hklages/node-red-contrib-sonos-plus#168]
Love this integration, however, my upgrade failed, and I'm not sure where to go from here.

![image](https://user-images.githubusercontent.com/30585632/134282994-6f510644-cf5d-4874-b735-3ec51b1fc426.png)

I did rename that directory, and it didnt work.  The subsequent Sonos update still failed. 

Currently on 5.2.5 and upgrading to 5.2.6 

This seems to be the relevant info from the debug file.

205 warn node-red-project@0.0.1 No repository field.
206 warn node-red-project@0.0.1 No license field.
207 verbose stack Error: Refusing to delete /home/mike/.node-red/node_modules/.bin/xml2js: is outside /home/mike/.node-red/node_modules/fast-xml-parser and not a link
207 verbose stack     at clobberFail (/usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:121:12)
207 verbose stack     at isSafeToRm (/usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:114:15)
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:54:5
207 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:180:7
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
207 verbose stack     at _readAllLinks (/usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:215:28)
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
207 verbose stack     at resolveSymlink (/usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:226:22)
207 verbose stack     at _readAllLinks (/usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:217:5)
207 verbose stack     at readAllLinks (/usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:212:3)
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:179:5
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
207 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
207 verbose stack     at /usr/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:153:16
208 verbose cwd /home/mike/.node-red
209 verbose Linux 5.10.60-meson64
210 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix=~" "--production" "--engine-strict" "node-red-contrib-sonos-plus@5.2.6"
211 verbose node v14.17.6
212 verbose npm  v6.14.15
213 error code EEXIST
214 error path /home/mike/.node-red/node_modules/.bin/xml2js
215 error Refusing to delete /home/mike/.node-red/node_modules/.bin/xml2js: is outside /home/mike/.node-red/node_modules/fast-xml-parser and not a link
216 error File exists: /home/mike/.node-red/node_modules/.bin/xml2js
217 error Remove the existing file and try again, or run npm
218 error with --force to overwrite files recklessly.
219 verbose exit [ 1, true ]

I'm unsure what the **npm --force** command should be, since that doesnt work.

**Comment by hklages** [comment]
What node-red version do you use? 

npm recommends to either
- delete /home/mike/.node-red/node_modules/.bin/xml2js

or

- use the npm command in addition to these option
`"install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix=~" "--production" "--engine-strict" "node-red-contrib-sonos-plus@5.2.6"`
with additional option --force

Do you have access to command level in that directory?

**Comment by GeorgeCastanza** [comment]
Thanks, that worked. Appreciate the prompt reply!
