### ISSUE TITLE
Play one song and stop

### ISSUE THREAD

**Issue by mpsamuels** [hklages/node-red-contrib-sonos-plus#17]
Maybe a niche request but is it possible to implement a 'Play one song and then stop' function?

More specifically, I'd like to be able to pass a playlist in, shuffle it, then play just the top song in the newly shuffled queue. Passing a playlist in is now easy enough, as is setting the play mode to shuffle, however I had hoped that the 'play_song' (described as 'Plays a specific song in queue') would play the specific song position in the queue and stop once the song is complete rather than continue to play the remainder of the playlist.

My particular use case is that I'd like a selection of Christmas songs to play when I turn on my tree lights (using a smart plug to allow automation) but having a single song playlist would find the same song getting boring quickly while I've no need to hear every Christmas song ever written each time I turn my lights on!

It may be possible to achieve using a loop to remove all but one items from the queue once playing has started but coupling Sonos Plus with other nodes within Node Red but I'm struggling to think where to begin with that at the moment so it'd be great if the option was added to Sonos Plus natively if it isn't too difficult to do?

Thanks

**Comment by mpsamuels** [comment]
After a bit of playing around with this I've found a solution for what I'm after. 

After the Manage Queue node that starts playing the first track of my playlist I progress to a 2 second Stoptimer node followed by a Change node with Payload 'remove_song' and Topic '2' which removes the 2nd song in the queue. The exit point of Change node then feeds back to the entry point of the Manage Queue node which was used to begin the playlist earlier thus creating a loop that infinitely removes the 2nd song in the queue until there are no more entries in the queue and the Manage Queue node errors to stop the loop. It's not ideal to rely on an error to stop the loop but does work with no obvious negative impact on node red itself.

On a side note, since upgrading to the latest version of Sonos Plus (which I hadn't done in some time) I've noticed that applying the Activate Queue Payload to the Managed Queue node against a queue with just one song in it now results in the same song being played endlessly on loop rather than playing once and stopping as it had in previous versions. I added the above fix to the end of my existing node-red flow to restore the original behaviour too.

**Comment by hklages** [comment]
Hi, maybe by Thursday evening I can publish a new release. Most likely I will add a property to remove_song to specify the number of entries to be deleted 1(default if nothing specified)  ... all. 

Regarding "playing endlessly": What parameter for `set_queuemode` do you use? SHUFFLE, SHUFFLE_NOREPEAT, SHUFFLE_REPEAT_ONE?

**Comment by hklages** [comment]
I just publish 1.0.1 with remove_song and numberOfSongs property. With that you can remove all songs up position 2 (by specifying 10000 as nuberOfSongs) .  Does it help?

**Comment by hklages** [comment]
Havent heard from you long time - so i close this issue. please reopen if it is still open
