### ISSUE TITLE
Direct Play Amazon Music Album per URL

### ISSUE THREAD

**Issue by svenflender** [hklages/node-red-contrib-sonos-plus#170]
Is it possible to play an Amazon Music Album directly per URL?

exmaple:

i want to play an Amazon Music Album on trigger without having it in my Library: 

https://music.amazon.de/albums/B0916RJW6M?marketplaceId=A1PA6795UKMFR9&musicTerritory=DE&ref=dm_sh_YHJDGDJ33YBqNEI5RIufBokFs

i want to build an RFID Card Reader that plays an Amazon Music Album for my daughter. So she can have some cards to play Audiobooks from Amazon.

**Comment by hklages** [comment]
no response - closed
