### ISSUE TITLE
instable when using dns names from hosts

### ISSUE THREAD

**Issue by pvklink** [hklages/node-red-contrib-sonos-plus#171]
### Description
The sonos universal nodes are instable when using dns names from /etc/hosts
I use this config in within a docker container with network = host instead of bridge

### What node/command (topic)/state (payload)

Universal node config with dns name
command: group play tune in 
state: s2733

### In case of a bug: Are you able to reproduce the error

yes by starting stoppling a lot

### Versions and Infrastructure

**what system:** <Raspberry Pi ? 4b
latest
latest
?
error in node-red/debug :
"create and subscribe:Unknown error/ exception -see node.error :: Details: "could not discover player by serial""

**Comment by hklages** [comment]
I close this as with ip addresses you should get a stable solution and for the "host name resolution" you just opened another issue.
