### ISSUE TITLE
Name resolution nodes in nodered

### ISSUE THREAD

**Issue by pvklink** [hklages/node-red-contrib-sonos-plus#175]
Wish: Name resolution sonos nodes in nodered.
In config sonos node use a host name as specified in dns (/etc/hosts) in stead of a ip-adress

All sonos nodes in Nodered

latest nodered / sonos versions on docker raspberry pi

**Comment by hklages** [comment]
Havent forgotten it :-) 

sonos-plus is based on [sonos-ts](https://github.com/svrooij/node-sonos-ts). Last week I already asked Stephan whether sonos ts supports host names - waiting for an answer. 

You mentioned that some nodes already support that - could you please provide the names. Maybe I can "copy" how they did it.

**Comment by hklages** [comment]
From Stephan (owner of sonos-ts) I received the feedback that his library supports domain name. My extensions dont work with domain names. During the cold and ugly time (December/January) I will spend time to remove my extension and try to implement domain name support.

**Comment by LuukML** [comment]
Cool! If you need a place to test this new version you can let me know!
will love to have domains instead of IP's.

Met vriendelijke groet,

Luuk Visser

06 81191485




Kastanjelaan 400 (Microlab)

5616LZ Eindhoven

Door mijn dyslexie maak ik spelfouten. De spellingchecker corrigeert die
helaas niet allemaal. Mocht de inhoud van mijn mail daardoor onduidelijk of
onbegrijpelijk zijn, verzoek ik u mij daarop te wijzen. Ik dank u alvast
voor uw medewerking!



Op ma 8 nov. 2021 om 09:38 schreef H. Klages ***@***.***>:

**Comment by hklages** [comment]
Thanks Luuk - I definitely need a tester as that is a new field for me. 
I will come back to you end of December, latest beginning of January.

**Comment by hklages** [comment]
@LuukML  Happy New Year.
Hi Luuk. Could you please check the following flow and let me know the results. 

Change the ip address in the flow with one of your SONOS players ip address and in a second run with the DNS name for that player. Does it work with your DNS name?  I use a fritzbox router/dns server and the DNS name sonosplay5.fritz.box unfortunately does not work. 

`[{"id":"3ffd4c6c4be71cf4","type":"http request","z":"55805384.a4695c","name":"","method":"GET","ret":"txt","paytoqs":"ignore","url":"http://192.168.178.35:1400/xml/device_description.xml","tls":"","persist":false,"proxy":"","authType":"","senderr":false,"credentials":{},"x":374,"y":2420,"wires":[["c2a15452950ad70e","f63e6d12ea6f2d9d"]]},{"id":"154f83b83504d044","type":"inject","z":"55805384.a4695c","name":"trigger","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"date","x":230,"y":2420,"wires":[["3ffd4c6c4be71cf4"]]},{"id":"c2a15452950ad70e","type":"xml","z":"55805384.a4695c","name":"","property":"payload","attr":"","chr":"","x":518,"y":2420,"wires":[["8115607db2156a44"]]},{"id":"8115607db2156a44","type":"change","z":"55805384.a4695c","name":"devicelist","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.root.device[0].deviceList[0].device","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":652,"y":2420,"wires":[["4f6a83cd4da48beb"]]},{"id":"4f6a83cd4da48beb","type":"change","z":"55805384.a4695c","name":"endpoint device","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.serviceList.service.controlURL","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":816,"y":2420,"wires":[["2d1b369f75306ddb"]]},{"id":"2d1b369f75306ddb","type":"debug","z":"55805384.a4695c","name":"service points","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1000,"y":2420,"wires":[]},{"id":"f63e6d12ea6f2d9d","type":"debug","z":"55805384.a4695c","name":"http result","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":540,"y":2380,"wires":[]}]`

**Comment by LuukML** [comment]
hey @hklages ill try to test it out this weekend and let you know! @SamMicrolab can you also have a look at this?

**Comment by hklages** [comment]
closed as now response - it works fine in my environment
