### ISSUE TITLE
IP not reachable

### ISSUE THREAD

**Issue by jfreak80** [hklages/node-red-contrib-sonos-plus#179]
### Description
after the latest update of my ccu3 to 3.61.5 the IP of my sonos is not reachable. 
--

<br class="Apple-interchange-newline">

### What node/command (topic)/state (payload)

node: Universal | My Sonos 
command:  config.node 
state: IP not reachable

### In case of a bug: Are you able to reproduce the error

yes 

### Versions and Infrastructure

**what system:** redmatic on ccu3 
**node-red-contrib-sonos-plus version:** 5.2.7 
**Node-RED version:** 7.2.1
**NodeJS version:** ?

**Comment by hklages** [comment]
Hi.

How to you select the player on your config node: Via up address or serial?

Does your flow works if you untic the "check availabilt" box?

**Comment by jfreak80** [comment]
Hi, 
I set up the correct IP. 
 I get an timeout: 
![image](https://user-images.githubusercontent.com/85195076/141980043-950bcc2b-2380-43a2-b177-ef9bd94996fb.png)

**Comment by jfreak80** [comment]
i am sorry. Just realized, that the sonos box is not working with the sonos app either. So the problem is not in your nice node!!!

**Comment by hklages** [comment]
OK- thanks for the feedback. I close the issue.
