### ISSUE TITLE
Manual restart of the event listener node because the SONOS device is not always online

### ISSUE THREAD

**Issue by rliegmann** [hklages/node-red-contrib-sonos-plus#187]
Hello and first of all, thank you very much for the great node. :-)

The following initial situation:
I currently only have one SONOS Connect.
Since this unfortunately does not have a power switch, I switch it on and off via my smart home system. (Save electricity and so :-) )
Now I have the problem that if I work on the Node-Red system and e.g. change something in another flow and then publish it, I get the following error message at the "sonos event" node.
![Bildschirmfoto 2022-01-10 um 20 40 06](https://user-images.githubusercontent.com/16445478/148828495-1ccb9548-b7d2-441d-bdf3-536969e49f2a.png)

I can only bring this back to normal when I publish it again and the SONOS is available.

I recognize that SONOS can be reached via the smart home control.
My idea now would be that I can restart the control node via a flow and get events again?
Is there a possibility or can this be implemented?

Thank you very much

**Comment by hklages** [comment]
Hi. 

What happen if you put the above event node in a separate flow ( node-red tab) and use the "only modified flows" when deploying? The the above node is not being deployed and should keep its status.

Regards, Grüße, Henning

**Comment by rliegmann** [comment]
Hi Henning, thanks (Danke) for the quick feedback.
Unfortunately, I've only just got around to working on it.
All SONOS stories are already in their own flows (2 pieces).
The "only modified flows" function was not even known until now. Thanks for that :-)
I'll try it.

I still have the question, what happens if the config node loses the connection to the SONOS device? Does it then try to reconnect in the interval or does it stay in failure mode?

Regards, Grüße, Ralf

**Comment by hklages** [comment]
There is not a "real" connection - neither for sonos-plus nor for sonos-events. 

### sonos-plus
When a message arrives at the node one ore more HTTP requests (SOAP format, REST API) are being send to the SONOS-Player and its response is being received/processed. Thats all.  It is connectionless. Similiar to a Firefox/Chrome/ call to a webside.

But:  When deployed (DEPOY button in Node-RED) the node checks whether the SONOS-Player is reachable (a simple http://<playerip>:1400/info) and if the SONOS-Player does not respond the node stops working. 
You can avoid this check by ticking "Do NOT check the availability of Sonos-Player." 

### sonos-events
When the node is deployed a small webserver (if not already exist) is being created. This webserver subscribes to the SONOS-Player events. The SONOS-Player sends the "news" to  subscribers - that means to the webserver and this webserver processes the data and send them to the node output. 
So also hier is now permanent "connection" but the SONOS-Player stores the list of subscribers (for a specific time duration  - then a new subscription is necessary).

Does that answer your question?
