### ISSUE TITLE
Request for Crossfade and Sleep

### ISSUE THREAD

**Issue by bdormael** [hklages/node-red-contrib-sonos-plus#19]
Is there a possibility to add CROSSFADE and SLEEP as queue or player functions ?

**Comment by hklages** [comment]
Hi. 

Regarding CROSSFADE I understand the request and will have a closer look. 

Regarding SLEEP: The First idea would be to use the following nodes: 
inject -> delay -> control player. 
Inject sets msg.delay to the "sleep time" and then trigger a stop in the control player. 
Sleep is nothing then a timer - right?

**Comment by bdormael** [comment]
Hi,

Thx for the answer, Sleep is Sleeptimer yes, I’ll try this with your suggestion.

Kind regards,

Benny

**Comment by bdormael** [comment]
One more question :-)

I’m trying to replace node-sonos-http-api by your node-red plugin so I don’t need a separate install/server.

I know you support notifications just like node-sonos-http-api does.
But do you also support a function like “clipall” so it plays a notification on all speakers and then returns to the state before (how it was grouped or not grouped before) ?

I know I can first group all speakers, then play the notification but I want to make sure the original state returns afterwards, including groupings, volumes, queues

Kindest regards,

Benny

**Comment by hklages** [comment]
This package is based on `https://github.com/bencevans/node-sonos`. I could not find anything similar to clipall there. 
What about: Play notification on all single players and the leader of each group? With that you will have the notification on all players played and the previous state will be restored.

**Comment by bdormael** [comment]
Hi,

The http version I was talking about is:
https://github.com/jishi/node-sonos-http-api

clipall will in fact group all speakers, then play the file, then restore the previous setting.

When grouping first, the sound is played in sync, when playing on each separate player or leader, the sound is not in sync.

Kindest regards,

Benny

**Comment by hklages** [comment]
I can not use the jishi package. That requires a http server being available. 
When I am back (in Febuar) I will check whether I can provide new commands to save and restore the state of a player and to group multiple players. Would that help?

**Comment by bdormael** [comment]
That would be perfect, thx

**Comment by hklages** [comment]
Hi, i just published 1.1.0. This release will NOT include CROSSFADE but the **next** one will. HOpe to finish that in 2 weeks.

**Comment by hklages** [comment]
I just published 1.2.0 - this includes set_crossfade and get_crossfade. 
Be aware that some streams (radio stations) does not support crossfade On and therefore an error message is thrown. 
Let me know if it works for your.

**Comment by hklages** [comment]
By the way: I used the information from https://github.com/jishi/node-sonos-http-api and send the SOAP package direct to the SONOS player. So most of the above package I can now "simulate".

**Comment by bdormael** [comment]
Hi,

Perfect :-)

If simulating jishi’s package, would there be a possibility then to also add sleep timer ?
This way I’m not dependent on the timer function in NodeRed.
Then your package would be totally awesome :-)

Kind regards,

Benny

**Comment by hklages** [comment]
Hi

set_sleeptime and get_timer seems to be easy. Is that's what you need?

best regards, Henning

**Comment by bdormael** [comment]
Yes, that’s it

**Comment by hklages** [comment]
Hi. I just published 1.3.0 including set_sleeptimer, get_sleeptimer in node Control Player. 
It nicely decreases the volumen and stops the player. 

Does it work for you?

**Comment by bdormael** [comment]
Hi,

Sorry for the late answer, I will test this weekend as I'm very busy this
week.
I'll keep you posted.

Kinde regards,

Benny

Op zo 9 feb. 2020 om 15:59 schreef H. Klages <notifications@github.com>:

**Comment by hklages** [comment]
Haven't heard from you for while - please open a new issue, if the issue still exist.
