### ISSUE TITLE
Start a Sonos list in a random song every time

### ISSUE THREAD

**Issue by danielccm** [hklages/node-red-contrib-sonos-plus#195]
This was referenced a while back in this quote:

"Not now but I guess Node-RED can do that. Use get.items and store it in a flow variable. Then use other Node-RED nodes to create "random" number between 1 and get.items array length."

_Originally posted by @hklages in https://github.com/hklages/node-red-contrib-sonos-plus/issues/60#issuecomment-628074640_

I was wondering if there's been any advances in this idea and if not, could you help a newbie out in achieving this?

Thanks!

**Comment by hklages** [comment]
Hi. It should be possible with Node-RED. Lets try. 

What is your detailed request? 
In My Sonos, you store many playlists (how many?). Should all be included or only "some"
You want to play one out of them? What should happen after that is played?
How is the process triggered - do you use a button in the Node-RED dashboard? 

get all items, filter playlists, store them as array in flow or global variable. 
Then use [random](https://flows.nodered.org/node/node-red-node-random) to get a random number. Retrieve the title with that number as index from flow variable and us it in group.play.mysonos.

**Comment by danielccm** [comment]
I currently have a flow that turns on/off several lights (not finished yet, but works) and also plays a certain playlist called relax on a Sonos.

![image](https://user-images.githubusercontent.com/9162711/150702091-4147e87a-f911-4c7c-a496-1f326e84067b.png)

Basically I want to have that one playlist be on random... right now it's got only a couple of songs, but as time goes by I'll be adding more and more... so that I don't get bored just listening to the same 3 hour long song every time..

**Comment by hklages** [comment]
Hi. 

Playing the songs of one playlist in random order is a build in function of the SONOS-Queue. You only have to activate the "SHUFFLE" mode (instead of "NORMAL") to do that. 

In you flow you should  
- remove group.clear.queue as group.play.mysonos does that by default. 
- remove group.play.queue as group.play.mysonos does that automatically. 
- set the queue to shuffle mode (maybe with a delay) try it. 

![shuffle](https://user-images.githubusercontent.com/17273119/150822538-12226b4f-72c6-4369-91ce-e98b664b731b.jpg)

Here is the flow in  export format. You have to use Node-RED import and change the grey nodes to use your player and you playlist from My Sonos. 

Does it work in your environment? 


```
[{"id":"0cb12a259087b29e","type":"debug","z":"f1e9954c32e7d4fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":390,"y":240,"wires":[]},{"id":"69d1b4e51648cee2","type":"inject","z":"f1e9954c32e7d4fe","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":100,"y":80,"wires":[["8ef287cd392b5dd9"]]},{"id":"8ef287cd392b5dd9","type":"sonos-universal","z":"f1e9954c32e7d4fe","confignode":"2fb67e61a2b0d13e","command":"group.play.mysonos","state":"HERZ","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":180,"y":120,"wires":[["992669d7df7e333b"]]},{"id":"992669d7df7e333b","type":"sonos-universal","z":"f1e9954c32e7d4fe","confignode":"2fb67e61a2b0d13e","command":"group.set.queuemode","state":"SHUFFLE","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":280,"y":180,"wires":[["0cb12a259087b29e"]]},{"id":"2fb67e61a2b0d13e","type":"sonos-config","name":"Kitchen","serialnum":"","ipaddress":"192.168.178.51"}]
```

**Comment by danielccm** [comment]
It sort of works... that is, it starts playing... but it only loads one song from the playlist... ignoring the rest (there's 4 right now) and therefore not doing the shuffle... ideas?

**Comment by hklages** [comment]
Hmmmm. Lets have a look at your "queue". 

Try this and send me the output of the debug node: 

```
[{"id":"0cb12a259087b29e","type":"debug","z":"f1e9954c32e7d4fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":430,"y":240,"wires":[]},{"id":"69d1b4e51648cee2","type":"inject","z":"f1e9954c32e7d4fe","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":100,"y":80,"wires":[["8ef287cd392b5dd9"]]},{"id":"8ef287cd392b5dd9","type":"sonos-universal","z":"f1e9954c32e7d4fe","confignode":"2fb67e61a2b0d13e","command":"group.play.mysonos","state":"HERZ","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":180,"y":120,"wires":[["992669d7df7e333b"]]},{"id":"992669d7df7e333b","type":"sonos-universal","z":"f1e9954c32e7d4fe","confignode":"2fb67e61a2b0d13e","command":"group.set.queuemode","state":"SHUFFLE","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":220,"y":180,"wires":[["33ae18d699f9853a"]]},{"id":"33ae18d699f9853a","type":"sonos-universal","z":"f1e9954c32e7d4fe","confignode":"2fb67e61a2b0d13e","command":"group.get.queue","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":240,"y":240,"wires":[["0cb12a259087b29e"]]},{"id":"2fb67e61a2b0d13e","type":"sonos-config","name":"Kitchen","serialnum":"","ipaddress":"192.168.178.51"}]
```

**Comment by danielccm** [comment]
![image](https://user-images.githubusercontent.com/9162711/150966230-c40d5fc6-c911-4412-95c5-7ac9a122c5e0.png)

**Comment by danielccm** [comment]
![Screenshot_20220125-121046_Sonos.jpg](https://user-images.githubusercontent.com/9162711/150966419-180296c8-4c3d-406e-aaf3-55769d8e44e8.jpg)

**Comment by danielccm** [comment]
That's what I have... a playlist called Relax with those 4 songs...

But it only imports the second one

**Comment by hklages** [comment]
Could you please rename the playlist to something more unique such as  "My Relax Playlist" and use that title in the group.play.mysonos. 

group.play.mysonos uses the "first" partial matching item and if you have any other item with "Relax" in its name it might be used.

**Comment by danielccm** [comment]
Genius! That name change did it... (as well as the flow, which I obviously had wrong...)

Thanks!

**Comment by martinjuhasz** [comment]
@hklages i tried this but without luck.
It always starts with the first item of the playlist and doesn't activate shuffle.
The `set.queuemode` node also says `Queue is empty`.

Any ideas? Also even if this is working, woudn't it always start with the first song of the playlist and only then suffle afterwards?
```
[{"id":"ce94d963bccce4ac","type":"inject","z":"14db225ac2e36dd8","name":"trigger","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"date","x":330,"y":440,"wires":[["f2a57fa26e7ab4bd"]]},{"id":"f2a57fa26e7ab4bd","type":"sonos-universal","z":"14db225ac2e36dd8","confignode":"88e9fa70.4a53e8","command":"household.create.group","state":"Arbeitszimmer","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":550,"y":440,"wires":[["90e88f598304db6d"]]},{"id":"0b168950b92dd086","type":"sonos-universal","z":"14db225ac2e36dd8","confignode":"b09be450f3bbbcc8","command":"group.play.mysonos","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1040,"y":460,"wires":[["179a0d195e745bc2"]]},{"id":"90e88f598304db6d","type":"change","z":"14db225ac2e36dd8","name":"Set Properties","rules":[{"t":"set","p":"payload","pt":"msg","to":"Matz Favs","tot":"str"},{"t":"set","p":"volume","pt":"msg","to":"10","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":800,"y":460,"wires":[["0b168950b92dd086"]]},{"id":"179a0d195e745bc2","type":"sonos-universal","z":"14db225ac2e36dd8","confignode":"88e9fa70.4a53e8","command":"group.set.queuemode","state":"SHUFFLE","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1300,"y":460,"wires":[["74e5687a4166cb33"]]},{"id":"74e5687a4166cb33","type":"sonos-universal","z":"14db225ac2e36dd8","confignode":"b09be450f3bbbcc8","command":"group.get.queue","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":1560,"y":460,"wires":[["37b0575ed13e38c4"]]},{"id":"37b0575ed13e38c4","type":"debug","z":"14db225ac2e36dd8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1770,"y":460,"wires":[]},{"id":"88e9fa70.4a53e8","type":"sonos-config","name":"Sonos Arc","serialnum":"","ipaddress":"10.0.20.20"},{"id":"b09be450f3bbbcc8","type":"sonos-config","name":"Sonos Arbeitszimmer","serialnum":"","ipaddress":"10.0.20.7"}]
```

**Comment by hklages** [comment]
Hi. 
SONOS does not allow to set the queue mode in case of an empty queue. So first you have to "fill" the queue and if that is done (that may take some seconds depending on the source) and then you should be able to set the mode. 
For instance you can use the my sonos queue item to add to the queue without start playing and then set the mode. 

Does that work for you?

**Comment by martinjuhasz** [comment]
would you mind pointing me to where i can add mysonos items to the queue? when i use # `group.play.mysonos` it seems nothing is added to the queue. at least it tells me the queue is empty afterwards. nevertheless since it's a spotify album i added it to queue by [group.queue.urispotify](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A.1-Universal-Node#groupqueueurispotify) which seems to do the trick

**Comment by hklages** [comment]
Try this: 
In the SONOS app: 
- use the "Browse" tab, select "Spotify" and select your playlist
- there is small menu with that you can add that playlist to "My Sonos"
- you can check it in the My Sonos tab / favorities of the app

Then use group.play.mysonos with the title of the playlist as payload. 

Here is a link to the [wiki ](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A.1-Universal-Node#groupplaymysonos)

That should work for almost every source such as Music library, Deezer, Amazon, Spotify, YouTube, ... (except podcasts)
