### ISSUE TITLE
group.play.notification Error after playing Radiostream

### ISSUE THREAD

**Issue by 199Kay** [hklages/node-red-contrib-sonos-plus#196]
### Problem with group.play.notification

After playing the notification, the stream is not continued and the following error message is displayed. 
group.play.notification: statusCode 500 & upnpErrorCode 402. upnpErrorMessage >>Invalid Args :: Details: none

When I play a playlist from Spotfy it works without problems that the playlist continues.

Very nice node. And a very good readme :)

Thx for help!

### What node/command (topic)/state (payload)

node: Universal 
command: group.play.notification

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

**what system:** Raspberry Pi 4, 8G
**node-red-contrib-sonos-plus version:** 6.0.1
**Node-RED version:** 1.3.7
**NodeJS version:** V12.22.7

Platform Betriebssystem:linux
Architektur : arm
CPUs:4
Geschwindigkeit:1500 MHz
Modell:ARMv7 Processor rev 3 (v7l)
RAM:7.7 GB
Node.js:v12.22.7
NPM:6.14.15
Datenträgergröße:116.9 GB
Festplatte frei:112.6 GB
Adapter-Anzahl:385
Betriebszeit:29 T. 00:32:24
Aktive Instanzen:11
Pfad:/opt/iobroker/

**Comment by hklages** [comment]
> Very nice node. And a very good readme :)

Thanks! There is also a wiki - more detailed information about usage.

> the stream is not continued a ....

What stream was it? How did you activate that stream?

**Comment by 199Kay** [comment]
Thanks for answering :)

I start the stream in the Sonos app. Then I want to play an mp3 via the notification. After playing it goes into the error message.
![image](https://user-images.githubusercontent.com/98274613/150870377-8dd932ab-294e-4798-b3ee-52e0b6e0fe9d.png)

`[
    {
        "id": "95486fd5.5c6d",
        "type": "inject",
        "z": "6366b5b6.cffbfc",
        "name": "Mp3",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "http://192.168.178.62:8081/files/0_userdata.0/Sprachbefehle/Der_TK_angeschaltet.mp3",
        "payloadType": "str",
        "x": 980,
        "y": 120,
        "wires": [
            [
                "b28ad401.b38b88"
            ]
        ]
    },
    {
        "id": "b28ad401.b38b88",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.play.notification",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 1240,
        "y": 120,
        "wires": [
            []
        ]
    },
    {
        "id": "43047f63.25063",
        "type": "sonos-config",
        "name": "Schlafzimmrt",
        "serialnum": "",
        "ipaddress": "192.168.178.32"
    }
]`

I noticed that once he has a queue, does not bring this error. The webradio does not create a queue.

I have come up with a workaround, but it is "very" elaborate. And my knowledge in Node is still very rudimentary.

![image](https://user-images.githubusercontent.com/98274613/150872734-01214251-a8bd-46a0-aef5-641373e1017b.png)


`[
    {
        "id": "59a321c8.51cd2",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.play.notification",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 2220,
        "y": 520,
        "wires": [
            [
                "d40ebf2.a31514"
            ]
        ]
    },
    {
        "id": "93a0db23.c21838",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "Gespeicherte Werte",
        "rules": [
            {
                "t": "move",
                "p": "ttssatz",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            },
            {
                "t": "move",
                "p": "volumesatz",
                "pt": "msg",
                "to": "volume",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1980,
        "y": 520,
        "wires": [
            [
                "59a321c8.51cd2"
            ]
        ]
    },
    {
        "id": "866f93.66c3407",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.play.tunein",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 2670,
        "y": 520,
        "wires": [
            []
        ]
    },
    {
        "id": "d40ebf2.a31514",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "Gespeicherte Werte",
        "rules": [
            {
                "t": "move",
                "p": "payload1.radioId",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            },
            {
                "t": "move",
                "p": "volume1",
                "pt": "msg",
                "to": "volume",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 2440,
        "y": 520,
        "wires": [
            [
                "866f93.66c3407"
            ]
        ]
    },
    {
        "id": "fc65a840.b329f8",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.play.queue",
        "state": "Liste",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 1750,
        "y": 520,
        "wires": [
            [
                "93a0db23.c21838"
            ]
        ]
    },
    {
        "id": "21c5ded7.ae5e52",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "Gespeicherte Werte",
        "rules": [
            {
                "t": "move",
                "p": "payload",
                "pt": "msg",
                "to": "volume1",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1720,
        "y": 620,
        "wires": [
            [
                "fc65a840.b329f8"
            ]
        ]
    },
    {
        "id": "29df95d8.df4b1a",
        "type": "inject",
        "z": "6366b5b6.cffbfc",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 2450,
        "y": 420,
        "wires": [
            [
                "866f93.66c3407"
            ]
        ]
    },
    {
        "id": "f368cb69.612588",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.play.notification",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 1400,
        "y": 320,
        "wires": [
            []
        ]
    },
    {
        "id": "540b7965.fe5bd8",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "Gespeicherte Werte",
        "rules": [
            {
                "t": "move",
                "p": "ttssatz",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            },
            {
                "t": "move",
                "p": "volumesatz",
                "pt": "msg",
                "to": "volume",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1160,
        "y": 320,
        "wires": [
            [
                "f368cb69.612588"
            ]
        ]
    },
    {
        "id": "74d38ae0.dde564",
        "type": "switch",
        "z": "6366b5b6.cffbfc",
        "name": "",
        "property": "payload.queueActivated",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "1",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "0",
                "vt": "num"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 910,
        "y": 380,
        "wires": [
            [
                "540b7965.fe5bd8"
            ],
            [
                "bca1c18c.f9542"
            ]
        ]
    },
    {
        "id": "bca1c18c.f9542",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.get.trackplus",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 1130,
        "y": 420,
        "wires": [
            [
                "9d06ce75.29f95",
                "f4ffbb0b.92dde8"
            ]
        ]
    },
    {
        "id": "9d06ce75.29f95",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.stop",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 1350,
        "y": 440,
        "wires": [
            [
                "a8fe7a8.eccb688"
            ]
        ]
    },
    {
        "id": "f4ffbb0b.92dde8",
        "type": "debug",
        "z": "6366b5b6.cffbfc",
        "name": "was",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1330,
        "y": 380,
        "wires": []
    },
    {
        "id": "a8fe7a8.eccb688",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "Gespeicherte Werte",
        "rules": [
            {
                "t": "move",
                "p": "payload",
                "pt": "msg",
                "to": "payload1",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1260,
        "y": 560,
        "wires": [
            [
                "a5d496e8.69e538"
            ]
        ]
    },
    {
        "id": "a5d496e8.69e538",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.get.volume",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 1510,
        "y": 620,
        "wires": [
            [
                "21c5ded7.ae5e52"
            ]
        ]
    },
    {
        "id": "13ff0fe1.c04ee",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "TK_AN",
        "rules": [
            {
                "t": "set",
                "p": "ttssatz",
                "pt": "msg",
                "to": "http://192.168.178.62:8081/files/0_userdata.0/Sprachbefehle/Der_TK_angeschaltet.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 480,
        "y": 140,
        "wires": [
            [
                "fca54d25.8b9b"
            ]
        ]
    },
    {
        "id": "8ee104df.bc38d8",
        "type": "inject",
        "z": "6366b5b6.cffbfc",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 280,
        "y": 40,
        "wires": [
            [
                "13ff0fe1.c04ee"
            ]
        ]
    },
    {
        "id": "4c732986.c20b88",
        "type": "switch",
        "z": "6366b5b6.cffbfc",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "true",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "false",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 250,
        "y": 180,
        "wires": [
            [
                "13ff0fe1.c04ee"
            ],
            [
                "4773a0b2.14076"
            ]
        ]
    },
    {
        "id": "4773a0b2.14076",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "TK_aus",
        "rules": [
            {
                "t": "set",
                "p": "ttssatz",
                "pt": "msg",
                "to": "http://192.168.178.62:8081/files/0_userdata.0/Sprachbefehle/Der_TK_ausgeschaltet.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 480,
        "y": 180,
        "wires": [
            [
                "fca54d25.8b9b"
            ]
        ]
    },
    {
        "id": "fca54d25.8b9b",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "Vollumen",
        "rules": [
            {
                "t": "set",
                "p": "volumesatz",
                "pt": "msg",
                "to": "20",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 720,
        "y": 260,
        "wires": [
            [
                "7d2af7dc.bcad58"
            ]
        ]
    },
    {
        "id": "25e5043e.e397bc",
        "type": "switch",
        "z": "6366b5b6.cffbfc",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "true",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "false",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 250,
        "y": 300,
        "wires": [
            [
                "9dfe0154.8791"
            ],
            [
                "6011feaf.230db"
            ]
        ]
    },
    {
        "id": "9dfe0154.8791",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "WM_AN",
        "rules": [
            {
                "t": "set",
                "p": "ttssatz",
                "pt": "msg",
                "to": "http://192.168.178.62:8081/files/0_userdata.0/Sprachbefehle/Die_WM_angeschaltet.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 480,
        "y": 280,
        "wires": [
            [
                "fca54d25.8b9b"
            ]
        ]
    },
    {
        "id": "6011feaf.230db",
        "type": "change",
        "z": "6366b5b6.cffbfc",
        "name": "WM_aus",
        "rules": [
            {
                "t": "set",
                "p": "ttssatz",
                "pt": "msg",
                "to": "http://192.168.178.62:8081/files/0_userdata.0/Sprachbefehle/Die_WM_ausgeschaltet.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 480,
        "y": 320,
        "wires": [
            [
                "fca54d25.8b9b"
            ]
        ]
    },
    {
        "id": "7d2af7dc.bcad58",
        "type": "sonos-universal",
        "z": "6366b5b6.cffbfc",
        "confignode": "43047f63.25063",
        "command": "group.get.state",
        "state": "",
        "stateType": "str",
        "avoidCheckPlayerAvailability": false,
        "name": "",
        "x": 740,
        "y": 360,
        "wires": [
            [
                "79d02321.e7571c",
                "74d38ae0.dde564"
            ]
        ]
    },
    {
        "id": "79d02321.e7571c",
        "type": "debug",
        "z": "6366b5b6.cffbfc",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 890,
        "y": 320,
        "wires": []
    },
    {
        "id": "47f4ad3f.987b54",
        "type": "ioBroker in",
        "z": "6366b5b6.cffbfc",
        "name": "TK on/off",
        "topic": "0_userdata.0.Keller.TRan",
        "payloadType": "value",
        "onlyack": "",
        "func": "rbe",
        "gap": "",
        "fireOnStart": "false",
        "x": 80,
        "y": 180,
        "wires": [
            [
                "4c732986.c20b88"
            ]
        ]
    },
    {
        "id": "4ae33f36.f5f04",
        "type": "ioBroker in",
        "z": "6366b5b6.cffbfc",
        "name": "WM on/off",
        "topic": "0_userdata.0.Keller.WMan",
        "payloadType": "value",
        "onlyack": "",
        "func": "rbe",
        "gap": "",
        "fireOnStart": "false",
        "x": 80,
        "y": 300,
        "wires": [
            [
                "25e5043e.e397bc"
            ]
        ]
    },
    {
        "id": "43047f63.25063",
        "type": "sonos-config",
        "name": "Schlafzimmrt",
        "serialnum": "",
        "ipaddress": "192.168.178.32"
    }
]`

**Comment by hklages** [comment]
Please upgrade to 6.1.0 and test your original flow again.

**Comment by hklages** [comment]
Please update to 6.1.1. 

Does it work now?

**Comment by 199Kay** [comment]
Brilliant it works now after the update from 6.1.0 to 6.1.1.
Very ingenious that it now works. Thank you for the super fast solution.
Now I can delete the workaround :)

Thank you very much
