### ISSUE TITLE
How to select "Line-In"

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#2]
I love your work with the SONOS, really well done!

I have the soundbar as well a few Play5 with Line-In capability which I was using so far. At moment I'm not able to switch-back to Line-In with your node!... How can I achieve this ??

I'm also using the node [SonosPollyTTS ](https://flows.nodered.org/node/node-red-contrib-sonospollytts)successfully .. it would be great if your two modules could merge

Keep going with the great work!

**Comment by hklages** [comment]
... thanks :-) 

... line in: Could be an interesting additional feature. In the next 2 weeks I will have a closer look into it.  For what do you need it. I saw there is an "autoplay" feature in SONOS. Is that an option for you? 

... SonosPollyTTS is an interesting node. I agree one package would be more comfortable and also we could safe some disk space as we both use node-sonos.  I put in on the long term "vision" list.

**Comment by tsprivate** [comment]
Hi there,

i tried the autoplay feature but it does not work reliable.  

I have used Line-In to connect to a TV with media-player.  During the day, internet radio is switching on (using your node)  when somebody is in the room and in the evening the TV is playing via the Line-in.
Whenever there is an home-automation announcement (via SonosPollyTTS) like weather-update or entrance-alarm, or the dogs wanna get out, than any ongoing streaming is paused for the announcement and than resumed (using your node)  .... this feature does not work with AUTOPLAY.

Would be awesome if you can get the Line-In working!

**Comment by hklages** [comment]
Tomorow you can try the following: 

0. Update to newest version 0.3.7 (tomorrow)
1. Get the stream.
Activate line in and use "Get Status" node with payload "get_mediainfo"
Copy the media.CurrentURI
For Play5 it should be something like: x-rincon-stream:RINCON_5CAAFD00223601400

2. Switch to some other radio stream

3. Try to switch to line in
Use "Control Player node" and send as payload "activate_avtransport" 
with topic the data "x-rincom-....". 

4. Adjust the volume - it is very quite 

On my play5 it did work.

**Comment by tsprivate** [comment]
Great work .. I'm looking forward to test it !

**Comment by tsprivate** [comment]
I just completed my test and the Line-In switch does work perfectly this way.

Thanks a lot for the quick update!

**Comment by hklages** [comment]
Ok - then I will close that topic.
