### ISSUE TITLE
Help with Spotify

### ISSUE THREAD

**Issue by zer03Four** [hklages/node-red-contrib-sonos-plus#20]
Hello, I have read through all you documentation, but  cannot seem to get a spotify playlist to play using the URI. When i deliver the msg to the node I receive this error:

insert spotify uri - Request failed with status code 500 :: Details: {"stack":"Error: Request failed with status code 500\n    at createError (/config/node-red/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/config/node-red/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/config/node-red/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1184:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","message":"Request failed with status code 500","config":{}}

Any help would be great. 

Thank you.

**Comment by hklages** [comment]
Hi. 
What Sonos plus version do you use?
Do you have a regular Spotify account?
Can you add the playlist to my Sonos and try the play mysonos command. Does that work?
What is the exact payload?

**Comment by zer03Four** [comment]
Thanks for the reply,
1. I have installed node-red-contrib-sonos-plus v1.0.1
2. I have a spotify premium account.
3. No this does not seem to be working either. I can use the get_spotify command and this will deliver a message containing all the playlists in "Sonos Favorites", but when i try the insert_spotify with a topic of one of the playlists, i get the same error.
4. I have tried a few different payloads.
-msg.payload = insert_spotify
-msg.topic - songs  (this is the name of a playlist that can be retrieved using get_spotify)

also tried:

-msg.payload = insert_spotify_uri
-msg.topic = spotify:playlist:4RcwKn7T78qa8XF5M0F3Iy  (this is the URI retrieved from the spotify windows application)


For all of this i have just been using inject nodes for testing. 

Thank you for the help.

**Comment by hklages** [comment]
Hi. The playlist format seems to be wrong: the user is missing. For general playlist it is spotify. 
Example: `spotify:user:spotify:playlist:37i9dQZEVXbMDoHDwVN2tF`

Regarding My Sonos: Did you add the playlist in the following way: 
a) in Sonos use Browse or Search
b) add playlist from results. 
or did you type in the playlist?

**Comment by zer03Four** [comment]
hello again,
Adding spotify:user: to the beginning does not seem to make a difference.

I have added the playlist from the results, however sonos does not supply a uri. i have retrieved his from the spotify windows application. In any case, this uri should point to the playlist. 

insert_spotify_uri with a topic of "spotify:track:5AdoS3gS47x40nBNlNmPQ8"  returns error: 

insert spotify uri - Request failed with status code 500 :: Details: {"stack":"Error: Request failed with status code 500\n    at createError (/config/node-red/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/config/node-red/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/config/node-red/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1184:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","message":"Request failed with status code 500","config":{}}



insert_spotify_uri with a topic of "spotify:user:spotify:track:5AdoS3gS47x40nBNlNmPQ8"  returns error: 

insert spotify uri - topic must be track, album, artistTopTracks or playlist :: Details: none

**Comment by hklages** [comment]
Understand. For tracks there is no need to add the user. That's only for playlists. 

Summary: It is not possible to play any Spotify object (track, album, playlist). Neither with insert_spotify nor insert_spotify_uri.

Another idea is that there are issues with the region. Could you check Sonos country and Spotify country (or region). They should be the same.

You can try to send the msg with property msg.region set to 3079 for US. Default is Europe 2311.
But I am not sure, whether the region parameter is still needed. 

If that does not work we can schedule skype in February as mentioned in your email.

**Comment by hklages** [comment]
I am closing that issue now. Please update to 2.x.x and try to use "My Sonos". 

As agreed in email, you are welcome to come back when your time allows it.
