### ISSUE TITLE
Possible to add power source of Sonos Move/Roam?

### ISSUE THREAD

**Issue by mac89muc** [hklages/node-red-contrib-sonos-plus#200]
Hello,

thanks for your effort in creating this node.
Is it possible to add the power source of the Sonos Move/Roam in addition to the Batterylevel which already exists?
Would be nice to integrate into a flow if the Move/Roam is not USB powered and is playing music battery powered to get the Batterylevel in a defined loop.

The power source is provided e.g. via web request http://192.168.178.125:1400/status/batterystatus

![image](https://user-images.githubusercontent.com/69312437/152115209-588dfc17-4bbd-4a87-8848-3d44b8c421ac.png)

![image](https://user-images.githubusercontent.com/69312437/152115765-19f5016a-05fc-415a-8949-7109be0aff04.png)

![image](https://user-images.githubusercontent.com/69312437/152115831-f7a9f17e-4a2e-42b6-8156-b2ef0c1d5fe9.png)

Regards

**Comment by hklages** [comment]
Hi. 

That should be possible. I can add a msg.powerSource to the output. 
Das Wetter in München ist aktuell nicht so gut - also ideal um zu Hause das nächste Release fertigzustellen. 
Dauert 3 bis 5 Tage. Bis dann.

**Comment by hklages** [comment]
Hi. 
I just published 6.3.0 - the powerSource should be available now. 

Greetings, Henning

**Comment by mac89muc** [comment]
wow... many thanks for the fast implementation - works perfect.

Vielen Dank & Grüße aus der Nachbarschaft....
