### ISSUE TITLE
Improvement request:    get.state for Player  & Houshold

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hklages/node-red-contrib-sonos-plus#202]
Hi there,

I'm using your node for a while with great sucess, all works seamlessly .. thx a lot

You currently have a node Group.get.state ... is it possible to have the same for Player & Houshold ?? 

e.g.  Player.get.state  ... Household.get.state

this would simplify the collection of state information dramatically , avoiding several get calls

thanks for considering

goog wook .. keep going

**Comment by hklages** [comment]
Hi. For what do you need it?

There is no single SONOS command to get the state. group.get.state sends 6 requests to the SONOS-Player, extracts the relevant information and output them. Most other group.* commands take 2 requests.

For a better understanding: 

player.get.state: All data are group related (playbackstate, group volume, group mutestated, ....) so a player.get.state for any player in a group would provide the same data as the the group.get.state. 
If you are interested in the player volume and player mute state you can already now get these data for all player in a group with group.create.snap

householde.get.state: I could implement it by sending group.get.state to all group coordinator. It will take some time as everything is serial and each command needs 6 request. With nodeRED split/join it is parallel, therefore much faster and already now available with node-red split/join. See this example: [example 9](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-Examples#examples---complex)
