### ISSUE TITLE
Problems since homeassistant update to 2022.3

### ISSUE THREAD

**Issue by Marrut** [hklages/node-red-contrib-sonos-plus#208]
Hi,
I've been using your node for quite some time and I'm extremely satisfied with it, thank you. 
So far it has always worked perfectly. 
However, since the update of homeassistant to 2022.3, I get the message that the device is not reachable/rejected. Any idea what the problem could be?
![Node-RED – Home Assistant](https://user-images.githubusercontent.com/15934336/158458810-a2b2f7df-a3b4-46f4-a4a5-ffd24f2c1546.jpg)

**Comment by hklages** [comment]
Hi. Thanks. 

I also use Home Assistant (2022.3.5) and everything works find. 
Could it be that you have changes in your network? 

Please go to your configuration node and und use the "search" button. Is your player being shown in the list? 

Is the SONOS device available in your network? You can check it in any browse with the request: 
`http://{sonosip}:1400/xml/device_description.xml.`  (replace {sonosip} with your ipv4 address

Maybe you network is overloaded during deployment. For this case you could tick the box 
"Reachability  Do NOT check the availability of Sonos-Player."

**Comment by Marrut** [comment]
Thanks for your reply. With the tip to look via configuration node, I found out that the ip addresses were no longer correct. Everything works correctly again. many thanks.
