### ISSUE TITLE
TuneIn RadioStation no Album/Cover Url

### ISSUE THREAD

**Issue by Missenberger79** [hklages/node-red-contrib-sonos-plus#21]
Hi,

for TuneIN Radiostation i have the Problem that there is the most time no Url for the Album/Cover Url. 
To Use this in a vis it is necessary to have the url to show the Logo of the RadioStation.

Thanks

**Comment by hklages** [comment]
Hi. Please provide an example. 
How do you activate the station: play_mysonos and search string or play_tunein with radio id?

**Comment by Missenberger79** [comment]
I have tried play_tunein and the RadioID
Here for example with s42824 and s17494. 
Here remains the albumArtURL: null

Same thing when I change the channels vom TuneIN on the Sonos APP.
I have also tested radio.net and again the value remains null

When I select a song from AMAZON or Spotify via the APP, albumArtURL gets a value and I can display it in the Visa under ioBroker

**Comment by tobi-coder** [comment]
I see the same issue

**Comment by hklages** [comment]
Currently, for all TuneIn stations, I can NOT provide neither AlbumURL nor the station logo. The base api (node-sonos) does not support it. 
Beginning of February, when I am back from vacation, I will have a closer look at it.

**Comment by hklages** [comment]
Hi. I just published 1.3.0 including: 
- `get_songmedia` and `get_songinfo` will have a new property `msg.radioId`. 
- 'get_mysonos' in "Manage Radio" will have a new property at each item: logo apart from radioId
---- you need to have your station added to My Sonos (is easy)

Radio id example: s57109
logo exampel: http://cdn-profiles.tunein.com/s57109/images/logoq.png

Unfortunately there are several pattern for different stations: 
http://cdn-profiles.tunein.com/s42824/images/logoq.png?t=151377
http://cdn-profiles.tunein.com/s25005/images/logoq.jpg?t=1
http://cdn-radiotime-logos.tunein.com/s260120q.png

So you can send an http request to the either cdn-radiotime or cdn-profiles and fetch it. 
My experience is that you can omit the '?t=xxxx'. 

If you want to be sure: Add the TuneIn Station to My Sonos and use in `get_mysonos` in node "Manage Radio". The output will show the exact link and the item includes also the Radio ID. 

Does it help?

**Comment by Missenberger79** [comment]
Hello it works. Thanks a lot.

A question, to keep the visualization up to date, is there a limit how often (time interval) I can do a get_xxx?

**Comment by hklages** [comment]
Hi. 
1) sorry - it is in get_mediainfo
2) that you can do with Node-red. see the flow. 
3) no idea. I guess only the Sonos player may get "exhausted". I would try first every minute. If that is stable, you can reduce. By the way: Ralf M send me some code for a node which could send a msg when title, etc changed. I intend to implement  -but dont now exactly when. 

`[{"id":"ca52f4c.ebb3f08","type":"inject","z":"55805384.a4695c","name":"trigger","topic":"","payload":"get_mediainfo","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":980,"wires":[["60af36c5.7ff848"]]},{"id":"1413e200.433aee","type":"change","z":"55805384.a4695c","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"get_mysonos","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":980,"wires":[["4057d604.719b58"]]},{"id":"4057d604.719b58","type":"sonos-manage-radio","z":"55805384.a4695c","confignode":"88e9fa70.4a53e8","name":"","x":360,"y":1020,"wires":[["5f80c798.8e1158"]]},{"id":"60af36c5.7ff848","type":"sonos-get-status","z":"55805384.a4695c","confignode":"88e9fa70.4a53e8","name":"","x":150,"y":1020,"wires":[["1413e200.433aee"]]},{"id":"82e1a63f.5053b8","type":"debug","z":"55805384.a4695c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":730,"y":1020,"wires":[]},{"id":"5f80c798.8e1158","type":"function","z":"55805384.a4695c","name":"map radioId - Logo","func":"const mySonosArray= msg.payload;\nfor (let i = 0; i < mySonosArray.length; ++i) {\n    if (mySonosArray[i].radioId === msg.radioId) {\n        msg.payload = mySonosArray[i].logo;\n        break;\n    }\n}\nreturn msg;","outputs":1,"noerr":0,"x":570,"y":1020,"wires":[["82e1a63f.5053b8"]]},{"id":"88e9fa70.4a53e8","type":"sonos-config","z":"","name":"sonos","serialnum":"5C-AA-FD-00-22-36:1","ipaddress":"192.168.178.37"}]`

**Comment by hklages** [comment]
I am closing this issue. Please open a new one, if the problem still insist.

**Comment by hklages** [comment]
closed - timed out :-)
