### ISSUE TITLE
How to play radio station from BBC Sounds integration

### ISSUE THREAD

**Issue by watchforstock** [hklages/node-red-contrib-sonos-plus#213]
### Description
I'd like to get the Sonos to play a radio station that comes from the BBC Sounds integration. When I play it via the sonos app and then do trackplus it gives me a URI of `x-sonosapi-hls:stations~playable~~bbc_radio_two~~urn:bbc:radio:network:bbc_radio_two?sid=325&flags=288&sn=6`. Is there a way I can use this information (or other information?) to play the radio station using NodeRed?

### Versions and Infrastructure

**what system:** 
**node-red-contrib-sonos-plus version:** 6.3.0
**Node-RED version:** 1.3.3
**NodeJS version:** 12.22.12

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
What is "BBC Sound Integration"? 

Anyway: When selecting that source their should be somewhere an option to "Add to My Sonos" or "Add to Favorites". 
After having done that you should be able to use the group.play.mysonos command with the title. 

Does it work? 

Is the station BBC Radio 2? Thats seemed to be available at TuneIn. (Sonos APP, Search with category Stations)

**Comment by watchforstock** [comment]
Thanks for the quick response!  BBC Sounds is a (new) service I can add to Sonos as they've removed the ability to play BBC radio via TuneIn (it's still there, but doesn't work). I can add the station to "My Stations", but it appears as a "BBC Sounds Station" rather than a "TuneIn station" under "My stations". 

Having done that, the "group.play.mysonos" worked so I'm up and running again! Many thanks
