### ISSUE TITLE
msg.playername command not executing when Config Node for a different device is OFFLINE

### ISSUE THREAD

**Issue by amilanov75** [hklages/node-red-contrib-sonos-plus#222]
I have noticed that when one of my Sonos devices is offline, a universal node that has that player setup as the Config Node, fails to execute, despite the msg.playername being passed through is for another player on the network.
In this example I am using topic = "mysonos.export.item" in the Universal Node. The intent being to send a new playlist to the msg.playername.

I can't see a way to setup a generic player in the Config Node drop down of the universal node, so am assuming this is a bug.

I am running node-red-contrib-sonos-plus 6.0.1 and node-red 3.0.0 beta 2 and nodejs 14.18.3

**Comment by hklages** [comment]
Hi. The reason for that behavior is: 
playername is only stored in the  SONOS-Player. For commands I need the ip address of that player.  The config node (it holds an ip address of a player) helps to get the mapping playername to ip address (and also the whole group structure with coordinator). 

Try to create another config node (you can create as many as you like) with ip address of an "always on" player. Use that config node (for universal or for my sonos) in combination with msg.playername.  

Does that work for your?

**Comment by hklages** [comment]
Thanks for the cup of coffee :-)

**Comment by amilanov75** [comment]
Ok, so it's a "feature" then that can't be avoided.

If that's the case I'll do as suggested and create a node for each player and then route the messages accordingly. 

Thanks!

**Comment by amilanov75** [comment]
I guess you are going to say it's not possible,  but can't you lookup the info you need based on msg.playername?

i.e. allow in the drop down to select "message" as the input, rather then forcing a playername to be selected and then make it a requirement that msg.playername has a valid Sonos device name, as configured in your node.

This way the nodes become dynamic and more flexible.

**Comment by hklages** [comment]
Node-RED config nodes are special. It is not possible to use the message to change the config data. 
But your are right - the config nodes are not really flexible.  

In fact I don't need the config node anymore and could replace them - but that would break any flow and every users has to change their flow. 

Idea: 
I consider to create an option to choose to use either a config node (same as now, and that is the default) or provide the data direct in the node - either as "message" or entering the DNS name. In that case there would not be any availability check.
You could then tic that option, choose message but must provide always the DNS name of the player with msg.playerDNS. 
msg.playerName would not work as I need the DNS (means IP) address.

It s an idea - i have to check in detail the impact on the code/users/testing. 

Do you use DNS names? For what do you need the "flexibilty"?

**Comment by amilanov75** [comment]
Hi,

Do you use DNS names?
Yes, I use DNS names (static IP addresses) for all Sonos players.

For what do you need the "flexibilty"?
I have a Sonos panel that allows for control of multiple devices.
TBH, you have given me enough info to workaround the issue. 
I will just use a switch node to direct message for each player to a custom configured universal node. That way, if one player is offline, only that player will be impacted.

Cheers!

**Comment by hklages** [comment]
OK - so I put that change on the "long term improvement" list. 
Again thanks for the feedback - I close this issue.
