### ISSUE TITLE
Cannot read property 'nodes' of null

### ISSUE THREAD

**Issue by jfreak80** [hklages/node-red-contrib-sonos-plus#223]
### Description
 i can not install the new version 

### Versions and Infrastructure

**what system:** <!--- CCU3 with Redmatic 
**node-red-contrib-sonos-plus version:** <!--- 6.3 is now away. And 6.4 will not install 
**Node-RED version:** <!--- 7.2.1 
**NodeJS version:** <!--- ?

see: [

**Comment by hklages** [comment]
Yes, sonos-plus now requires at least NodeRED Version 2 And redmatic hasn't been updated for months. 

Do you know how to login to the ccu? You have to submit the npm command to reinstall 6.3. it is still available at GitHub as all the other releases.

**Comment by jfreak80** [comment]
Thank you for the answer. 
i know how to login via Putty.

but i need help with the command line.

i have downloaded the package for 6.3 and tried to upload it with the palette manager but this failed either

**Comment by hklages** [comment]
good. You have to go to the node-red user directory and then use the base npm command

```
source /usr/local/addons/redmatic/home/.profile
cd /usr/local/addons/redmatic/var
```
You should see all installed nodes with 

`npm list` 

and you can install any package with 

`npm update --no-package-lock --global-style --save-prefix="~" --only=prod <paket-name>`

In this case us as package 
`node-red-contrib-sonos-plus@6.3.0`
