### ISSUE TITLE
"get current song" Warning

### ISSUE THREAD

**Issue by tobi-coder** [hklages/node-red-contrib-sonos-plus#23]
Thank you very much for this great Sonos nodes!

Is there a way to hide this warning message from the debug output?

Just a warning: get current song - invalid combination artist title received :: Details: received-> {"id":null,"parentID":null,"title":"aacp?aw_0_1st.playerid=tunein.com","artist":null,"album":null,"albumArtURI":null,"position":0,"duration":0,"albumArtURL":null,"uri":"aac://https://s7-webradio.rockantenne.de/rockantenne/stream/aacp?aw_0_1st.playerid=tunein.com","queuePosition":1}

**Comment by hklages** [comment]
I can add a property `suppressWarning `with default value "false". You can then send "get_songmedia" or "get_songinfo" together with `suppressWarning=true`  to avoid the message. 

Would that help? 

I will implement that in the first week in February (after vacation).

**Comment by tobi-coder** [comment]
That would be a great solution. Thank you!

**Comment by hklages** [comment]
I have just published 1.1.0 with the suppressWarnings. Please check and let me know whether it works for you.

**Comment by tobi-coder** [comment]
It works perfect for me. Thank you!

**Comment by Missenberger79** [comment]
Can you pls make a example. I didn't know how this will work

**Comment by hklages** [comment]
I can not find that comment. Do you still need an example?
