### ISSUE TITLE
Event node shows connected:6329 but nothing in debug

### ISSUE THREAD

**Issue by Mikee1234K** [hklages/node-red-contrib-sonos-plus#235]
I edited the config as per instructions, and the node says connected:6329 but nothing coming through on any of the debugs. (I downloaded the example flow)
I have treid various player IPs, none of them seem to work. I have got the 'standard' sonos nodes, and they are all working fine. I have also tried changing the hostname, I first tried leaving it blank, then changed to the IP of my Node Red (its running on a different PC to the one I use for editing)

![image](https://user-images.githubusercontent.com/72687610/208251403-917cd894-888d-484d-9d8a-7686ce72d270.png)

**Comment by hklages** [comment]
Hi. 
- Please make a screen shot of your node and your configuration node - or export it. 
- Go to the config node and press the lens (listener ip address field). What addresses are shown - any?  
- What kind of installation do you use? Raspberry Pi, Docker based, ...?

**Comment by Mikee1234K** [comment]
`[{"id":"e2d97ed43a6efb0c","type":"sonosevents-selection","z":"fc1278284082ef71","name":"","confignode":"fe83534eec428ecf","playerHostname":"192.168.0.77","events":[{"fullName":"ZoneGroupTopologyService.allGroups"}],"outputs":1,"x":710,"y":860,"wires":[["9a10f6d90a45c091"]]},{"id":"9a10f6d90a45c091","type":"debug","z":"fc1278284082ef71","name":"debug 123","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":950,"y":860,"wires":[]},{"id":"fe83534eec428ecf","type":"sonosevents-config","name":"Mike Sonos Events","listenerHostname":"x.x.x.x","listenerPort":"","portType":"num"}]`

When I press the lens, it shows 3 IP addresses. The top one is 192.168.56.1, I have no idea where that came from, not an IP I use. The other 2 addresses are from teh PC running node red, and the next one is the node red IP. My node red uses zerotier to make it accessible outside my network. I have edited out that IP in the flow above and replaced with x.x.x.x
I have tried all 3 IP addresses, also tried leaving the listeneer IP blank
My node red runs on a Windows 10 PC, in iobroker

**Comment by hklages** [comment]
For your privacy you can send the answer to my email "nrcsplus@gmail.com"

If you leave the listener ip blank, then the software uses the first ip address (in your case 192.168.56.1), assumes that node.js / node-red is installed there and creates a small server. This server subscribes to the SONOS player (in your case 192.168.0.77), receives the events, transfers them to node-red. 

First we should be sure about the ip address of your node red instance. 
- can you check the node-red log file. There is usually something like
`18 Dec 15:27:24 - [info] Server now running at http://127.0.0.1:46836/`
- usually you can access node red with <ip>:1880 
- what do you mean with "PC running node red, and the next one is the node red IP" 

Unfortunately I dont have any experience with zerotier.

**Comment by hklages** [comment]
Summary from email communication: In general sonos-events works in iobroker and also Home Assistant environment. But here in this specific situation (zerotier) we used a work around (reacting on iobroker changes, using sonos-plus to get the artwork.
