### ISSUE TITLE
Installation von node-red-contrib-sonos-plus mehrfach fehlgeschlagen

### ISSUE THREAD

**Issue by Schorsch9** [hklages/node-red-contrib-sonos-plus#237]
homematic CCU3 - Version 3.65.11 (aktuellste Version)
RedMatic - Version 7.2.1 (aktuellste Version)

Hey,
bei der Installation der Palette "node-red-contrib-sonos-plus" aus der Palettenverwaltung von RedMatic erhalte ich immer eine Fehlermeldung.

Ich habe es dann auch per ssh-Verbindung und über manueller Installation gemäß Anleitung versucht (siehe Anlage - letztes Bild).
Im Verzeichnis /usr/local/addons/redmatic/var/node_modules/ ist ein Verzeichnis mit dem Namen der Palette vorhanden. Nachdem ich es manuell deinstalliert hatte, war das Verzeichnis weg. Nach erneuter Installation war es wieder da, jedoch ist nach dem Neustart von RedMatic auf der CCU3 die Palette nicht verfügbar.

Könnt ihr mir bitte bei der Installation der Palette helfen?
Ich habe vom homematic-System und von RedMatic vorher ein backup angelegt.
[Dok.pdf](https://github.com/hklages/node-red-contrib-sonos-plus/files/10344760/Dok.pdf)

Vielen Dank im Voraus
Schorsch

**Comment by hklages** [comment]
Hi Schorch, RedMatic ist problematisch, da es seit geraumer Zeit nicht mehr aktualisiert wird. Es sind alte Versionen von NodeRED und npm im Einsatz (siehe auch Dein Dok File mit dem Versionsunterschied von npm) 

Bitte vorher CCU Backup erstellen!

Du kannst versuchen eine alte sonos-plus Version manual zu installieren. Der link ist hier - [downgrade](https://github.com/hklages/node-red-contrib-sonos-plus/discussions/228) ... und dann die CCU neu booten. 

Du kannst dann links sehen, ob Universal node, etc installiert wurden (falls die Palette immernoch nicht zu sehen ist.

**Comment by Schorsch9** [comment]
Hey,
ich konnte die Palette der Version 6.1.0 installieren. Die Nodes stehen mir jetzt zur Verfügung. Ich werde mal sehen, wie ich damit klarkomme. Schon einmal vielen Dank.

**Comment by hklages** [comment]
Gut. Danke für das Feedback.
