### ISSUE TITLE
Alarm is not enable/disable

### ISSUE THREAD

**Issue by Donni1966** [hklages/node-red-contrib-sonos-plus#239]
### Description
I try to enable oder disable the alarm of one or more Sonos Play One/1

### What node/command (topic)/state (payload)
first i get the Alarm with the household command get alarms. 
`{"ID":"904","StartTime":"06:30:00","Duration":"02:00:00","Recurrence":"WEEKDAYS","Enabled":"1","RoomUUID":"RINCON_542A1B46881A01400","ProgramURI":"x-sonosapi-stream:s142194?sid=254&amp;flags=8224&amp;sn=0","ProgramMetaData":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;R:0/0/26&quot; parentID=&quot;R:0/0&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Absolut Radio (Alternative Rock)&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast.sonos-favorite&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON65031_&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","PlayMode":"SHUFFLE","Volume":"25","IncludeLinkedZones":"0"}`

i try to sent with a inject an 904 type Number and get all the time the result : 

`[{"id":"aa8f8076db6a648e","type":"inject","z":"4017e5c7.708454","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"904","payloadType":"num","x":300,"y":2040,"wires":[["6fdc63259ef72d65"]],"l":false},{"id":"37eed94f8b2dbc8f","type":"debug","z":"4017e5c7.708454","name":"debug 18","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":585,"y":2040,"wires":[],"l":false},{"id":"6fdc63259ef72d65","type":"sonos-universal","z":"4017e5c7.708454","confignode":"759eb3bd339b0819","command":"household.disable.alarm","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":495,"y":2040,"wires":[["37eed94f8b2dbc8f"]],"l":false},{"id":"759eb3bd339b0819","type":"sonos-config","name":"Mobil","serialnum":"54-2A-1B-46-88-1A:4","ipaddress":"192.168.2.53"}]`

`msg : string[92]
"household.disable.alarm: enable alarm max is not type number or bigger 9999 :: Details: none"`

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

running in a node-red Docker 3,02 and newest Sonos version 6.4.1

i changed type, try different numbers ( Array Number 3 , ID Number, try 1-10, changed to string, put number in the Sonos Flow, and what ever - no effect. 
in the Example from the plugin is looks so simple. But not works for me. All other commands runs fine with this speaker, but the Alarm feature noch works für all 4 Speakers with alarm activate. 
Any Idea?

**Comment by hklages** [comment]
Right - it is a bug. I am going to fix it today and send and update.

**Comment by Donni1966** [comment]
Cool. Wait for it. Many thanx

**Comment by hklages** [comment]
Thanks for reporting that bug! Version 6.4.2 fixes it.

**Comment by Donni1966** [comment]
Great thanx. Works fine.
