### ISSUE TITLE
Help with grouping

### ISSUE THREAD

**Issue by sparky-Ol** [hklages/node-red-contrib-sonos-plus#24]
Hi,
i want to play every morning my favourite radiostation in the kitchen (Sonos Play1, master) and the living room (Sonos Play 5, slave). The event is triggered by a schedule node.
I tried to design a flow that first advises the living room in the kitchen group and then after a delay starts the radio in the kitchen: [Flow.txt](https://github.com/hklages/node-red-contrib-sonos-plus/files/4077505/Flow.txt)
I'm not able to join living room into the kitchen group, although the contoller node replies: ok: join_group. 
Where ist the missing link?
Thanks for help, Sascha

**Comment by hklages** [comment]
Have you seen the example in the Wiki? 

`[{"id":"40508b27.d41c94","type":"comment","z":"fdd26dc0.e6647","name":"::: J ::: Group to players","info":"","x":104,"y":3437,"wires":[]},{"id":"5d45a6bf.8cda08","type":"sonos-get-status","z":"fdd26dc0.e6647","confignode":"35a9048e.475dec","name":"Get Status Lead Player","x":578,"y":3511,"wires":[["fe6eadcb.76b1"]]},{"id":"3f30b432.6e699c","type":"change","z":"fdd26dc0.e6647","name":"play swr3 on leader","rules":[{"t":"set","p":"payload","pt":"msg","to":"play_tunein","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"s24896","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":250,"y":3471,"wires":[["4bf5c84a.7d62b8"]]},{"id":"5021e7a7.691cf8","type":"inject","z":"fdd26dc0.e6647","name":"trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":89,"y":3471,"wires":[["3f30b432.6e699c"]]},{"id":"4bf5c84a.7d62b8","type":"sonos-manage-radio","z":"fdd26dc0.e6647","confignode":"35a9048e.475dec","name":"Manage Radio Lead Player","x":300,"y":3511,"wires":[["fc769216.4f2b8"]]},{"id":"fe6eadcb.76b1","type":"change","z":"fdd26dc0.e6647","name":"join_group with new topic","rules":[{"t":"set","p":"topic","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"join_group","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":816,"y":3471,"wires":[["93d957a.44167a8"]]},{"id":"93d957a.44167a8","type":"sonos-control-player","z":"fdd26dc0.e6647","confignode":"5ce40f7c.5fc25","name":"Ctrl Player Following Player","x":871,"y":3511,"wires":[[]]},{"id":"fc769216.4f2b8","type":"change","z":"fdd26dc0.e6647","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"get_name","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":525,"y":3471,"wires":[["5d45a6bf.8cda08"]]},{"id":"35a9048e.475dec","type":"sonos-config","z":"","name":"bad","serialnum":"00-0E-58-FE-3A-EA:5","ipaddress":"192.168.178.35"},{"id":"5ce40f7c.5fc25","type":"sonos-config","z":"","name":"wz","serialnum":"94-9F-3E-C1-3B-99:8","ipaddress":"192.168.178.36"}]`

**Comment by sparky-Ol** [comment]
Solved, with your flow it works!
Thx hklages
