### ISSUE TITLE
player.adjust.volume:Request timed out :: Details: Validate players IP address 

### ISSUE THREAD

**Issue by Mikee1234K** [hklages/node-red-contrib-sonos-plus#246]
I have 5 players, and I set the current player to a flow variable, which I then use to send via a change node to various Sonos nodes (via playerName). Suddenly I could not control volume of the player any more, I see a error player.adjust.volume:Request timed out :: Details: Validate players IP address . If I change the player in the config node (in the universal node) to the correct player, it works. I use another node to request the loudness state of the player. Again, I get an error player.get.loudness - request timed out.
It was all working fine for a few weeks. I have not used Sonos for a couple of weeks, and not changed anything. I think there might have been a pallette update which I applied in the meantime. Could that have 'broken' it ?

**Comment by Mikee1234K** [comment]
It looks to me as if the Sonos universal node is ignoring the playerName. I checked, and playerName is set to the correct player, but I get that error from the Sonos node. If I set it manually in config, it works

**Comment by hklages** [comment]
Hi Mike.
Please let me know the output of household.get.groups and the flow.

**Comment by Mikee1234K** [comment]
I think I have found the issue. I had a player in the config node, which I unplugged as its not used very often. If I set that to a player which is on permenently, it all works as expected. So the issue others might have too, if you specify a player in the universal config node which is offline, things do not work.
maybe thats something you could catch in a future release ?

**Comment by hklages** [comment]
I decided to do the check, when you deploy the node - but I guess you did disable that check ("Do NOT check the availability of Sonos-Player."). 

After deployment you will receive an error message, if there is something wrong and you can react on it.
