### ISSUE TITLE
Status in SONOS-Box zurückschreiben, ohne Play-Funktion - geht das?

### ISSUE THREAD

**Issue by Schorsch9** [hklages/node-red-contrib-sonos-plus#247]
homematic CCU3 - Version 3.67.10 (aktuellste Version)
RedMatic - Version 7.2.1 (aktuellste Version)

Hallo,
schon einmal vielen Dank für deine Arbeit hinsichtlich dieser nodes.

Seit ein paar Tagen verbeiße ich mich an folgendem Problem:
Ich gebe mit TTS-ultimate einige mp3-files auf einer SONOS-One aus. Die files sind dann in der SONOS-Box gespeichert und werden bei der nächsten manuellen Betätigung des Power-Buttons wieder abgespielt.
Ich möchte nun gerne den Status der SONOS-Box vorher sichern, das file abspielen und dann den Status wieder in die SONOS-Box zurückschreiben, jedoch ohne Play-Funktion.

Kannst du mir da eine Lösung aufzeigen?

Danke
Schorsch

**Comment by hklages** [comment]
Hallo. 

SONOS kann keine Dateien speichern. Wahrscheinlich liegen Deine MP3 Dateien auf der CCU (das Verzeichnis gibt TTS Ultimate vor) und TTS Ultimate nutzt einen Webservice um die Dateien SONOS ONE per http zur Verfügung zu stellen. Der Link zu der Datei ist in SONOS ONE gespeichert - als letzte "Quelle" oder als Element der Queue.

Kennst du das [Beispiel 3 - es ist unter Import/Examples](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-Examples). Wenn der Status der SONOS Box einfach eine Queue (Playlist, Album, ...) ist, könnte es funktionieren. Du könntest die Queue vorher mit group.save.queue speichern und wieder "restaurieren". 

Was ist der Anwendungsfalls: Ein "Gute Nachtgruß" mit Stopp der Musik und am Morgen soll die Musik wieder spielen?

**Comment by Schorsch9** [comment]
Hey,
richtig, die mp3-files liegen in einem speziellen Ordner, vorgegeben von TTS Ultimate. Ich dachte, die würden an die SONOS-Box überspielt.
Das Beispiel 3 hatte ich noch nicht gesehen. Ich habe es ausprobiert, es würde meiner Vorstellung entsprechen. Es scheint jedoch nicht für Radiosender zu funktionieren. Für Playlisten, Alben etc. funktioniert es. Ich werde damit noch experimentieren.
Wahrscheinlich wird es darauf hinauslaufen, dass ich kurz das Radio als "Gute Nachtgruß" anspielen werde.
Ich werde auch noch ausprobieren, wie es sich verhält, wenn ich das Einschalten der SONOS-Box abfange - prüfen ob ein mp3-File abgespielt wird und in dem Fall einen festgelegten Radiosender abspielen lassen. Muss ich nächste Tage machen, wenn ich alleine im Haus bin ;-)
Nochmals, vielen Dank für dein Engagement.

**Comment by hklages** [comment]
Gern. Bei Radiosendern könntest du auf stumm stellen, dann den Radiosender auswählen/spieln, dann stoppen und wieder unmute. Etwas umständlich. 
Es gibt auch noch group.create.snap und Play.snap. 
Das könnte auch funktionieren. 

Wenn du nicht weiterkommst, bitte melden.

**Comment by hklages** [comment]
no response - closed.
