### ISSUE TITLE
Play Notification does not work in https environment

### ISSUE THREAD

**Issue by Josov** [hklages/node-red-contrib-sonos-plus#25]
My Pi is used for iot purposes and as such accessible from the Internet. I use a certificate generated through Letsencrypt to secure the connection. I can fetch the mp3 files from the Pi using a HTTP request but I need to enable "Use authentication". I cannot manage the Sonos to fetch the mp3 using authentication. Is there a work around available?

**Comment by hklages** [comment]
Oh. I am not sure whether Sonos is able to fetch with authentication. 

Do you "serve" the mp3 file on PI / NodeRed with http node? 

I remember someone uses Google to store the mp3 and then streams that data via Google service. 
But i never tried.

**Comment by Josov** [comment]
Do you "serve" the mp3 file on PI / NodeRed with http node? YES, correct... this is how I was thinking and along the HTTP GET I can obtain the mp3's.

I was thinking about a 'local' SAMBA server on my Pi. Could this work using such a server? 
Or, would it be possible to pass on the URI and authentication data embedded in a moustache object?

**Comment by Josov** [comment]
@hklages  : I managed to resolve the problem using an Apache2 server listening on port xxxx. I then created a new directory /var/www/html/**mp3** and copied the .mp3 notifications to this directory. Now I can use HTTP GET to retrieve mp3 files from the local Pi and use them as Notification on the Sonos devices.
