### ISSUE TITLE
Getting Error - CurrentUri is invalid :: Details: none for group.set.queuemode

### ISSUE THREAD

**Issue by craigs66** [hklages/node-red-contrib-sonos-plus#261]
Using the Universal Node and group.set.queuemode. I have SHUFFLE entered in the PAYLOAD field. The logs show:

[sonos-universal:Shuffle Mode] group.set.queuemode: CurrentUri is invalid :: Details: none

I get the same error if I enter the other valid values like NORMAL.

This has worked fine for awhile. I've restarted Home Assistant and NodeRed.

Sonos Plus version - 6.7.3

<img width="493" alt="Screen Shot 2023-04-05 at 4 41 14 PM" src="https://user-images.githubusercontent.com/47399804/230218374-8860a897-a696-496e-9b02-91ec1fcdd23b.png">

**Comment by hklages** [comment]
Hi. 

Please check in the Sonos  app whether  the command was succesfull and maybe the track in position 1 is invalid. You can also use group.get.queuemode and group.get.queue
