### ISSUE TITLE
Please, add nodes for favorites

### ISSUE THREAD

**Issue by feuerbeere** [hklages/node-red-contrib-sonos-plus#262]
Feature Request:
I need a node for getting favorites: https://developer.sonos.com/reference/control-api/favorites/

node: Universal
command: household.get.favorites

**Comment by hklages** [comment]
Hi. 

> The Sonos app filters favorites into different swim lanes in My Sonos. See`    **My Sonos**     `in the Explore our products, ...

SONOS favorites are stored in "My Sonos". In my package you can find the "favorites" in "my sonos". 
Please use "group.play.mysonos" to play any favorite or mysonos.get.items to view all your favorites. There are also mysonos.export.item and group.play.export. 

Let me know if that works for your. 

cheers Henning
