### ISSUE TITLE
Error by playing mp3 File with group.play.notification

### ISSUE THREAD

**Issue by BuchbergerFlorian** [hklages/node-red-contrib-sonos-plus#268]
Hallo vielen Dank für die bereitgestellte Sonos integration für Node Red.

Ich möchte gerne auffbauend auf deinem Beispiel Nr.7 eine eigene MP3 datei abspielen. Diese habe ich als GET-Endpoint aufgesetzt und wenn ich diese im Browser aufrufe wird der Song gleich abgespielt.
Jetzt habe ich gedacht ich schreibe einfach den Payload in Beispiel Nr.7 um, also statt https://soundbible.com/mp3/foghorn-daniel_simon.mp3 auf meinen Endpoint http://localhost:1880/mp3. 
Das funktioniert jedoch nicht und es kommt im Sonos Universal Node die Fehlermeldung "group.play.notification:Sonos error on SetAVTransportURI UPnPError 714 (Illegal MIME-Type)".

Hast du eine Ahnung was ich falsch mache?

Ich verwende Node Red 3.0.2 mit einem Raspberry Pi4 B+ im gleichen Netzwerk wie die Sonos Geräte.
Vielen Dank im Vorhinein für eine Antwort!

**Comment by hklages** [comment]
... dein Endpreise sieht merkwürdig aus.

http://localhost:1880/mp3

Benenn die Datei um in sound.mp3 und dann

http://localhost:1880/sound.mp3

Grüße Henning

**Comment by BuchbergerFlorian** [comment]
Vielen Dank für deine Hilfe! Jetzt funktioniert es!
