### ISSUE TITLE
What is needed to support Napster?

### ISSUE THREAD

**Issue by Markus-** [hklages/node-red-contrib-sonos-plus#27]
I use Napster for the source of my music - what is needed to get support for it in this node?

Is there a list of things you need for an implementation?

Regards
Markus

**Comment by hklages** [comment]
What "kind of source" does Napster provide? Song, album, playlist (all using the queue)  and also radio stations (as stream)? 

For song and album I found some infos in another package. Maybe I can copy that. 
Is every song / album identified by an unique id? 

Do you know the Didl light description

**Comment by Markus-** [comment]
This is ONE object when I hit get_queue and listening to songs from Napster.

Anything else?


`{"id":"0/1","parentID":"0","title":"Only for the Weak","artist":"In Flames","album":"Clayman (Reissue 2014)","albumArtURI":"http://10.10.0.7:1400/getaa?s=1&u=x-sonos-http%3aondemand_track%253a%253atra.171682676%257cv1%257cCHART%257calb.171682673.mp4%3fsid%3d203%26flags%3d8224%26sn%3d1","uri":"x-sonos-http:ondemand_track%3a%3atra.171682676%7cv1%7cCHART%7calb.171682673.mp4?sid=203&flags=8224&sn=1"}`

**Comment by hklages** [comment]
Hi, can you please do the following: 

In the SONOS up, use browse, select napster, select a song and use the menue to "add song to My Sonos" and note the name of that song. 
Do the same for an album, and playlist. 

Then use `get_mysonos` command and send to the "Get Status" node. 
Send the array or at least the three items (song, album, paylist to me.

**Comment by Markus-** [comment]
Playlist:
{"id":"2/5","parentID":"2","title":"20 Jahre Napster: 1999","artist":null,"album":null,"albumArtURI":"http://direct.rhapsody.com/imageserver/v2/playlists/pp.382494011/artists/images/230x153.jpg?order=frequency","uri":"x-rincon-cpcontainer:100e004cexplore%3aplaylist%3a%3app.382494011?sid=203&flags=76&sn=1"}

Album:
{"id":"2/7","parentID":"2","title":"Church [Explicit]","artist":null,"album":null,"albumArtURI":"http://direct-ns.rhapsody.com/imageserver/images/Alb.441376240/300x300.jpg","uri":"x-rincon-cpcontainer:100420ecexplore%3aalbum%3a%3aAlb.441376240?sid=203&flags=8428&sn=1"}

Song:
{"id":"2/6","parentID":"2","title":"Mambo No. 5 (a Little Bit of...)","artist":null,"album":null,"albumArtURI":"http://direct-ns.rhapsody.com/imageserver/images/Tra.290276864/300x300.jpg","uri":"x-sonos-http:ondemand_track%3a%3atra.290276864%7cv1%7cPLAYLIST%7cpp.382494011.mp4?sid=203&flags=8224&sn=1"}

**Comment by hklages** [comment]
Hi, insert song, artist, playlist work on my test system with a 1 month test account. 
My intention is to go via My Sonos. That means you have to add the album, song, playlist first to my sonos and then are able to select that by specifying parts of the title. For instance `play mambo`.

Does that fit to your use case?

**Comment by Markus-** [comment]
I think so. Sounds good.

Is this different from the implementations of Spotify and Amazon Music or do they work in the same way?

**Comment by hklages** [comment]
Hi, I have just published 2.0.0 with a new node "My Sonos". This node should support Napster, Amazon, Spotify, TuneIn, Radioplayer (tested) but also Apple, Deezer, .... 
In your SONOS App you have to add albums, playlist, streams, etc to My Sonos and then you can choose them in this package via command `queue` or `stream`. 

Does it work for you?

**Comment by Markus-** [comment]
Sorry for the delay.
I just tried the new "My Sonos" Node and got the following error:

`"get My Sonos items - xml2js.parseStringPromise is not a function :: Details: {"stack":"TypeError: xml2js.parseStringPromise is not a function\n at Object.parseSoapBody (/data/node-red/node_modules/node-red-contrib-sonos-plus/src/Soap.js:195:19)\n at Object.getAllMySonosItems (/data/node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:33:33)\n at process._tickCallback (internal/process/next_tick.js:68:7)","message":"xml2js.parseStringPromise is not a function"}"`

My Testflow:
`[
    {
        "id": "d0355063.8ccac",
        "type": "tab",
        "label": "Flow 6",
        "disabled": false,
        "info": ""
    },
    {
        "id": "4a269ab8.6fde54",
        "type": "sonos-manage-mysonos",
        "z": "d0355063.8ccac",
        "confignode": "1298581.c93bfa8",
        "name": "",
        "x": 360,
        "y": 108,
        "wires": [
            [
                "198d6508.24382b"
            ]
        ]
    },
    {
        "id": "198d6508.24382b",
        "type": "debug",
        "z": "d0355063.8ccac",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 694,
        "y": 109,
        "wires": []
    },
    {
        "id": "8a642b7.12835d8",
        "type": "inject",
        "z": "d0355063.8ccac",
        "name": "",
        "topic": "",
        "payload": "get_items",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 122,
        "y": 107,
        "wires": [
            [
                "4a269ab8.6fde54"
            ]
        ]
    },
    {
        "id": "1298581.c93bfa8",
        "type": "sonos-config",
        "z": "",
        "name": "SONOS-AZM",
        "serialnum": "",
        "ipaddress": "10.10.0.7"
    }
]`

I have quite old libraries / versions, because this is my production system and I just patch if I have to (separate network, extensive testing...) - Is this there a module which is too old or is there any bug?

Regards
Markus

**Comment by hklages** [comment]
Hi. How do you install the code? Do you copy the files from Github or do you use the palette manager in NodeRED?

Could it be that you copied the NOT finished branch "code optimization"? 
There I can reproduce the error. I use branches to have a remote backup of my work. Maybe that causes confusion. The branches are not working.

Please use 2.0.0

**Comment by hklages** [comment]
... sorry I accidentially closed it - now again open.

**Comment by Markus-** [comment]
I used the palette-manager. So I thought this would be the correct version. 
Palette-Manager shows 2.0.0.

**Comment by hklages** [comment]
Please open a terminal session, go to directory `node-red-contrib-sonos-plus`, submit `npm list` and send me the screen shot. It should show the tree of all installed libraries with their version. 

On Raspberry Pi 4 it is unter 
`~/.node-red/node_modules/node-red-contrib-sonos-plus`.

**Comment by Markus-** [comment]
Mmh. Multiple UNMET dependencies.
I just used palette-manager.

node-red-contrib-sonos-plus@2.0.0 /data/node-red/node_modules/node-red-contrib-sonos-plus
└─┬ sonos@1.12.6
  ├── UNMET DEPENDENCY axios@^0.19.0
  ├── UNMET DEPENDENCY debug@^4.1.1
  ├── UNMET DEPENDENCY ip@^1.1.5
  └── UNMET DEPENDENCY xml2js@^0.4.19

npm ERR! missing: axios@^0.19.0, required by sonos@1.12.6
npm ERR! missing: debug@^4.1.1, required by sonos@1.12.6
npm ERR! missing: ip@^1.1.5, required by sonos@1.12.6
npm ERR! missing: xml2js@^0.4.19, required by sonos@1.12.6

**Comment by hklages** [comment]
There should be a subdirectory `node_modules` in `node-red-contrib-sonos-plus`. In that directory there shoud be subdirectories for all packages: sonos, axios, debug, .... 
And each directory should have a package.JSON showing the current version. 

I am not an npm expert. You can try to completely reinstall node-red-contribut-sonos-plus, or try to fix the the installatoin witn `npm update sonos`, even npm `update axios` - but all only local. Dont use the g flag for global.

**Comment by hklages** [comment]
You can now use My Sonos node - command export.item together with Universal node  - command play.export to play your Napster playlist, songs, ... 

Does it work for you?

**Comment by Markus-** [comment]
To be clear: I can use My Sonos playlists which contains songs from Napster and not Playlists which I have IN Napster, correct?

I always get an empty list wen I query get.items. In the SONOS App I have 4 Playlists and 1 Radio Stream...

**Comment by hklages** [comment]
Many people are confused regarding "My Sonos" and Sonos playlist. 

"My Sonos" is similar to favorites and you can find My Sonos in the SONOS App (see the screen shot). In the SONOS App you first have to select your Napster playlist, album,... what ever and 
use the "Add to My Sonos" menu item. 

After that you can see that object in My Sonos and get.items should show all items. With export.item you can export a single one. See this example [1 2](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-How-To-and-Examples)

**Comment by hklages** [comment]
... timed out.
