### ISSUE TITLE
group.play.mysonos no longer working

### ISSUE THREAD

**Issue by fredrikeder** [hklages/node-red-contrib-sonos-plus#274]
### Description
After months of flawless usage, the group.play.mysonos started to throw: "group.play.mysonos:Sonos error on AddURIToQueue UPnPError 800 (Command not supported or not a coordinator)".

### What node/command (topic)/state (payload)

node: Universal
command: group.play.mysonos
payload: Title of any item in My Sonos

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

**what system:** Raspberry Pi
**node-red-contrib-sonos-plus version:** 6.7.3
**Node-RED version:** 3.1.0
**NodeJS version:** ?

**Comment by hklages** [comment]
Hi.

Pleased send the Outcome of
mysonos.get.items
You can send  it to ***@***.***

Best regards, Henning

**Comment by fredrikeder** [comment]
Hi, Of course.

group.play.mysonos:Sonos error on AddURIToQueue UPnPError 800 (Command not supported or not a coordinator) :: Details: {"stack":"SonosError: Sonos error on AddURIToQueue UPnPError 800 (Command not supported or not a coordinator)\n    at AVTransportService.handleErrorResponse ***@***.***/sonos/lib/services/base-service.js:242:23)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AVTransportService.handleRequestAndParseResponse ***@***.***/sonos/lib/services/base-service.js:215:15)\n    at AVTransportService.SoapRequestWithBody ***@***.***/sonos/lib/services/base-service.js:105:16)\n    at AVTransportService.AddURIToQueue ***@***.***/sonos/lib/services/av-transport.service.js:75:41)\n    at Object.groupPlayMySonos [as group.play.mysonos] (/config/node_modules/node-red-contrib-sonos-plus/src/sonos-universal.js:1129:7)","message":"Sonos error on AddURIToQueue UPnPError 800 (Command …

Br
Fredrik

**Comment by fredrikeder** [comment]
Sorry. That was the debug-message. Here's the outcome of mysonos.get.items:

[{"id":"FV:2/4","title":"Apple Music 1","artist":"","album":"","description":"Apple Music-station","uri":"x-sonosapi-hls:hls%3ara.978194965?sid=204&amp;flags=8224&amp;sn=3","artUri":"https://is2-ssl.mzstatic.com/image/thumb/Features114/v4/e5/10/76/e5107683-9e51-ebc5-3901-d8fbd65f2c2a/source/400x400cc.jpeg","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10092020hls%3ara.978194965&quot; parentID=&quot;10fe2064grouping%3a170437-adamId%3a1453609755&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Apple Music 1&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.item.audioItem.audioBroadcast","processingType":"stream"},{"id":"FV:2/3","title":"Apple Music 1","artist":"","album":"","description":"Från Apple Music","uri":"","artUri":"https://apps.mzstatic.com/content/static-resources/sonos/v2/MainIconMyMusic-legacy.png","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10fe2064grouping%3a170310-adamId%3a1567384878&quot; parentID=&quot;10fe2064grouping%3a170310-adamId%3a1567384878&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Apple Music 1&lt;/dc:title&gt;&lt;upnp:class&gt;object.container&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"","serviceName":"","upnpClass":"object.container","processingType":"queue"},{"id":"FV:2/12","title":"Favoriter","artist":"","album":"","description":"Från Sonos Radio","uri":"","artUri":"","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10fe2064%2fstations%2fSONOS_FAVORITES&quot; parentID=&quot;00080004%2fstations%2fSONOS_FAVORITES&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;&lt;/dc:title&gt;&lt;upnp:class&gt;object.container&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON77575_X_#Svc77575-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"","serviceName":"","upnpClass":"object.container","processingType":"queue"},{"id":"FV:2/16","title":"Good Morning","artist":"","album":"","description":"Apple Music Playlist","uri":"x-rincon-cpcontainer:1006206cplaylist%3apl.a8645f7491bf4ce0a6c98b911f9c1a8b?sid=204&amp;flags=8300&amp;sn=3","artUri":"https://is1-ssl.mzstatic.com/image/thumb/Features112/v4/a7/60/18/a76018a1-414e-e38f-832c-e9fcb7f32e48/ae31812b-ccad-49f6-a5d9-0c83d7fbf58e.png/400x400cc.jpeg","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;1006206cplaylist%3apl.a8645f7491bf4ce0a6c98b911f9c1a8b&quot; parentID=&quot;search:category:playlist&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Good Morning&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.playlistContainer.#PlaylistView&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.container.playlistContainer.#PlaylistView","processingType":"queue"},{"id":"FV:2/5","title":"Grammofon: Skivspelare","artist":"","album":"","description":"Linjeingång","uri":"x-rincon-stream:RINCON_48A6B822982201400","artUri":"","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;RINCON_48A6B822982201400&quot; parentID=&quot;&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Grammofon: Skivspelare&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.linein&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"","serviceName":"","upnpClass":"object.item.audioItem.linein","processingType":"queue"},{"id":"FV:2/7","title":"Heartbreak Pop","artist":"","album":"","description":"Apple Music-spellista","uri":"x-rincon-cpcontainer:1006206cplaylist%3apl.91f43a875d694022ba4b338fce6a8c48?sid=204&amp;flags=8300&amp;sn=3","artUri":"https://is5-ssl.mzstatic.com/image/thumb/Features115/v4/e2/df/40/e2df40c0-c4cd-58f6-b2b2-489acdf01cdc/U0MtTVMtV1ctSGVhcnRicmVha19Qb3AtQURBTV9JRD05NzY0NDczMjUucG5n.png/400x400SC.DN01.jpeg?l=sv-SE","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;1006206cplaylist%3apl.91f43a875d694022ba4b338fce6a8c48&quot; parentID=&quot;00020000playlist:heartbreak&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Heartbreak Pop&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.playlistContainer.#PlaylistView&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.container.playlistContainer.#PlaylistView","processingType":"queue"},{"id":"FV:2/8","title":"Library","artist":"","album":"","description":"Från Apple Music","uri":"","artUri":"","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10fe2066browseviewlibraryroot%3alibraryroot&quot; parentID=&quot;00080020browseviewlibraryroot%3alibraryroot&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Bibliotek&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.#LibraryListView&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"","serviceName":"","upnpClass":"object.container.#LibraryListView","processingType":"queue"},{"id":"FV:2/2","title":"P3","artist":"","album":"","description":"Sveriges Radio-station","uri":"x-sonosapi-hls:channel%3a164?sid=235&amp;flags=32&amp;sn=2","artUri":"https://static-cdn.sr.se/images/164/2186756_512_512.jpg?preset=api-default-square","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10090020channel%3a164&quot; parentID=&quot;0009002cchannel%3a164&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;P3&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON60167_&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"235","serviceName":"Sveriges Radio","upnpClass":"object.item.audioItem.audioBroadcast","processingType":"stream"},{"id":"FV:2/0","title":"Populärt just nu","artist":"","album":"","description":"Från Sonos Radio","uri":"","artUri":"","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10fe0044%2fstations%2fsv-SE%2fSE%2fc2Q6U0U6dHJlbmRpbmctbm93&quot; parentID=&quot;00081004%2fstations%2fsv-SE%2fSE%2fc2Q6U0U6dHJlbmRpbmctbm93&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;&lt;/dc:title&gt;&lt;upnp:class&gt;object.container&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON77575_X_#Svc77575-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"","serviceName":"","upnpClass":"object.container","processingType":"queue"},{"id":"FV:2/14","title":"Pure Meditation","artist":"","album":"","description":"Apple Music-spellista","uri":"x-rincon-cpcontainer:1006206cplaylist%3apl.e896478fdf824a93ab2f99165c3a1422?sid=204&amp;flags=8300&amp;sn=3","artUri":"https://is1-ssl.mzstatic.com/image/thumb/Features115/v4/3e/a3/7e/3ea37ed4-945e-7937-0791-dc0c9c9df9c3/U0MtTVMtV1ctUHVyZV9NZWRpdGF0aW9uLUFEQU1fSUQ9OTc2NDQ3NjgzLnBuZw.png/400x400SC.DN01.jpeg?l=sv-SE","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;1006206cplaylist%3apl.e896478fdf824a93ab2f99165c3a1422&quot; parentID=&quot;search:category:playlist&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Pure Meditation&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.playlistContainer.#PlaylistView&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.container.playlistContainer.#PlaylistView","processingType":"queue"},{"id":"FV:2/6","title":"Rain","artist":"","album":"","description":"Sonos Radio-station","uri":"x-sonosapi-radio:sonos%3a153171?sid=303&amp;flags=8232&amp;sn=1","artUri":"https://sali.sonos.radio/image?w=60&amp;image=https%3A%2F%2Fsonosradio.imgix.net%2Fstation-images%2F67e41092-f0d4-428b-ba56-b58e0b685f7f.png%3Fw%3D200%26auto%3Dformat%2Ccompress&amp;partnerId=sonos","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;100c2028sonos%3a153171&quot; parentID=&quot;00020000station:rain&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Rain&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON77575_X_#Svc77575-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"303","serviceName":"Sonos Radio","upnpClass":"object.item.audioItem.audioBroadcast","processingType":"stream"},{"id":"FV:2/9","title":"Red Rock Riviera","artist":"","album":"","description":"Med (Sea Power)","uri":"x-sonos-http:librarytrack%3ai.gelJ45AULP4Gpm.mp4?sid=204&amp;flags=8232&amp;sn=3","artUri":"https://is5-ssl.mzstatic.com/image/thumb/Music122/v4/7b/ab/c7/7babc788-7e9d-b4f3-8b20-3328cc31e46d/883870067966.png/400x400bb.png","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10032028librarytrack%3ai.gelJ45AULP4Gpm&quot; parentID=&quot;00032028librarytrack%3ai.gelJ45AULP4Gpm&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Red Rock Riviera&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.item.audioItem.musicTrack","processingType":"queue"},{"id":"FV:2/13","title":"Replay 2023","artist":"","album":"","description":"Apple Music-spellista","uri":"x-rincon-cpcontainer:1006206cplaylist%3apl.rp-eRR6FVzvolE?sid=204&amp;flags=8300&amp;sn=3","artUri":"https://is1-ssl.mzstatic.com/image/thumb/Features112/v4/4e/b5/c0/4eb5c0ab-ba82-94db-968c-1fe6d159709f/b3c2ee62-d839-4c60-bfa4-806917b2e16a.png/400x400cc.jpeg","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;1006206cplaylist%3apl.rp-eRR6FVzvolE&quot; parentID=&quot;recommendation%3a15-7FV4cdVz9i7cMROBIaQwhq&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Replay 2023&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.playlistContainer.#PlaylistView&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.container.playlistContainer.#PlaylistView","processingType":"queue"},{"id":"FV:2/10","title":"Station för Fredrik Eder","artist":"","album":"","description":"Apple Music-station","uri":"x-sonosapi-radio:radio%3ara.u-7ad1343afa5f53881abb70ff757aa95f?sid=204&amp;flags=44&amp;sn=3","artUri":"https://is1-ssl.mzstatic.com/image/thumb/Features124/v4/7b/1d/f0/7b1df048-0017-8ac0-98c9-735f14849606/mza_7507996640781423701.png/400x400bb.jpg","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;000c002cradio%3ara.u-7ad1343afa5f53881abb70ff757aa95f&quot; parentID=&quot;0&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Station för Fredrik Eder&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.item.audioItem.audioBroadcast","processingType":"stream"},{"id":"FV:2/15","title":"Upptäck mer musik","artist":"","album":"","description":"Apple Music-station","uri":"x-sonosapi-radio:radio%3ara.q-GAI6IDdhZDEzNDNhZmE1ZjUzODgxYWJiNzBmZjc1N2FhOTVm?sid=204&amp;flags=44&amp;sn=3","artUri":"https://is1-ssl.mzstatic.com/image/thumb/Features126/v4/11/ad/7b/11ad7bad-df4f-42d1-4235-996800055de7/661dbb46-6f09-40f9-8789-7591387fdb93.png/400x400sr.jpg","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;000c002cradio%3ara.q-GAI6IDdhZDEzNDNhZmE1ZjUzODgxYWJiNzBmZjc1N2FhOTVm&quot; parentID=&quot;recommendation%3a19-7Mvo724kmp9kHbZrAW5WzA&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Upptäck mer musik&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast#BrowseItem&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON52231_X_#Svc52231-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"204","serviceName":"Apple Music","upnpClass":"object.item.audioItem.audioBroadcast#BrowseItem","processingType":"stream"},{"id":"FV:2/1","title":"Upptäck Sonos Radio","artist":"","album":"","description":"Från Sonos Radio","uri":"","artUri":"","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10fe0044%2fstations%2fsv-SE%2fSE%2fc2Q6U0U6ZGlzY292ZXItc29ub3MtcmFkaW8&quot; parentID=&quot;00081004%2fstations%2fsv-SE%2fSE%2fc2Q6U0U6ZGlzY292ZXItc29ub3MtcmFkaW8&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;&lt;/dc:title&gt;&lt;upnp:class&gt;object.container&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON77575_X_#Svc77575-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"","serviceName":"","upnpClass":"object.container","processingType":"queue"},{"id":"FV:2/11","title":"WAVES FOR SLEEP","artist":"","album":"","description":"Sonos Radio-station","uri":"x-sonosapi-stream:tunein%3a180066?sid=303&amp;flags=8232&amp;sn=1","artUri":"https://sali.sonos.radio/image?w=60&amp;image=https%3A%2F%2Fcdn-profiles.tunein.com%2Fs321182%2Fimages%2Flogog.jpg%3Ft%3D1666199956000&amp;partnerId=tunein","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10092028tunein%3a180066&quot; parentID=&quot;00092028tunein%3a180066&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;WAVES FOR SLEEP&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON77575_X_#Svc77575-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","sid":"303","serviceName":"Sonos Radio","upnpClass":"object.item.audioItem.audioBroadcast","processingType":"stream"}]

**Comment by hklages** [comment]
Ok. So there are some items. That's good.

Are you able to play these items from inside the official SONOS app. If
not, please reauthorize the appe service.

Best regards, Henning

**Comment by fredrikeder** [comment]
I am not! Seems like I have to “Update the app”, even though I’m on the latest version on all devices. I get a 1101 when updating, which essentially means I need to restart everything that can get restarted. So the problem is way beyond node-red. Thanks for you help!

Br
Fredrik

**Comment by fredrikeder** [comment]
Powering off and on and then updating the speaker solved the problem. Not an issue with this project.
