### ISSUE TITLE
Error when trying to add Sonos AMP or any other speaker as satellite to Sonos RAY....

### ISSUE THREAD

**Issue by CKL1976** [hklages/node-red-contrib-sonos-plus#276]
I am getting this error when trying to add Sonos AMP or any other speaker as satellite to my Sonos RAY.... Not sure if this is Sonos related.

household.add.satellites:Sonos error on AddHTSatellite UPnPError 402 (Invalid args) :: Details: {"stack":"SonosError: Sonos error on AddHTSatellite UPnPError 402 (Invalid args)\n    at DevicePropertiesService.handleErrorResponse (/root/.node-red/node_modules/@svrooij/sonos/lib/services/base-service.js:243:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DevicePropertiesService.handleRequest (/root/.node-red/node_modules/@svrooij/sonos/lib/services/base-service.js:200:16)\n    at async DevicePropertiesService.SoapRequestWithBodyNoResponse (/root/.node-red/node_modules/@svrooij/sonos/lib/services/base-service.js:134:16)\n    at async DevicePropertiesService.AddHTSatellite (/root/.node-red/node_modules/@svrooij/sonos/lib/services/device-properties.service.js:35:42)\n    at async Object.householdAddSatellites [as household.add.satellites] (/root/.node-red/node_modules/node-red-contrib-sonos-plus/src/sonos-universal.js:2394:5)","message":"...

**Comment by hklages** [comment]
Please send me your flow to see the used  payload / properties

**Comment by hklages** [comment]
no response -> closed.
