### ISSUE TITLE
Support artistRadio

### ISSUE THREAD

**Issue by danielvandenberg95** [hklages/node-red-contrib-sonos-plus#277]
### Description
Support artistRadio, as supported in https://github.com/svrooij/node-sonos-ts/blob/de5e822a952666380a5acf81bc7ae1e0678abcfd/src/helpers/metadata-helper.ts#L258

### What node/command (topic)/state (payload)

node: Universal
command: group.queue.urispotify
state: ehh, any?

### In case of a bug: Are you able to reproduce the error

Not a bug

### Versions and Infrastructure

**what system:** docker on linux
**node-red-contrib-sonos-plus version:** 6.3.0
**Node-RED version:** 3.0.2
**NodeJS version:** I honestly don't know but don't think it matters....

### Code to be adjusted:
https://github.com/hklages/node-red-contrib-sonos-plus/blob/20a12a76b3c368e83786e8bc39e74404134df49b/src/sonos-universal.js#L1798
Needs an extra line, spotify:artistRadio. Should then magically work?

**Comment by hklages** [comment]
... thanks for your precise information. I will try to implement it. It
will take a few days as I have to rebuild my test environment.

best regards, Henning

**Comment by hklages** [comment]
Hi, I added the line of code - please be so kind and test it. I dont have a spotify account.

**Comment by danielvandenberg95** [comment]
Radio does not seem to be a playlist, nor appear in a playlist. When playing a radio station, my queue remains untouched.

Perhaps you could show me what you mean using screenshots?

**Comment by hklages** [comment]
Maybe I dont understand artistRadio. What artistRadio do you want to use? Is it something like "Eminem Radio" or "Tayloer Swift Radio" or something different? 



![Eminem 1Plus](https://github.com/hklages/node-red-contrib-sonos-plus/assets/17273119/a70faa25-e4a3-40a8-b70f-2584c717a734)
![Eminem 2Plus](https://github.com/hklages/node-red-contrib-sonos-plus/assets/17273119/a8c08afb-888f-4716-ab34-ca2bf4672449)
![Eminem 3plus](https://github.com/hklages/node-red-contrib-sonos-plus/assets/17273119/7b42cb3f-f0d9-49f8-9658-55506b80f63d)

**Comment by danielvandenberg95** [comment]
![Screenshot_20240218-161231](https://github.com/hklages/node-red-contrib-sonos-plus/assets/8654023/1481a197-5ca7-479e-94bd-bc0875f0552f)
Text incoming, editing this on my laptop...

**Comment by hklages** [comment]
Ok. First I have to fix another issue regarding the mysonos commands.
Hopefully on Monday


Then we can continue.

**Comment by hklages** [comment]
Hi, there is now a new release. Please install it and let's see what error
messages shows up in your flow.

**Comment by hklages** [comment]
Does not work - currently no solution available.
