### ISSUE TITLE
can not connect to player - refused

### ISSUE THREAD

**Issue by DeepHyperspace** [hklages/node-red-contrib-sonos-plus#28]
Hi,

i get an error when i simply want to send a play command to control the player. Is there anything i can do? I'm sure the ip adress is correct, i've selected one player from the dropdown when i click on search in the configuration node.

_Error-Message: "play - can not connect to player - refused :: Details: Validate ip address of player"_

**Comment by hklages** [comment]
Try it without entering the IP address. That should also work.

**Comment by DeepHyperspace** [comment]
> Try it without entering the IP address. That should also work. Do you use static IP addresses for your player?

nope doesnt work
"play - can not connect to player - refused :: Details: Validate ip address of player"

**Comment by hklages** [comment]
Take any browser and enter: 
http://<your sonos ip address>:1400/info
What do you get?

Example for 192.168.178:37: 
`http://192.168.178.37:1400/info`

**Comment by hklages** [comment]
... as it is solved - i close.

**Comment by DeepHyperspace** [comment]
Yes i get that ...
`{"websocketUrl":"wss:\/\/192.168.178.30:1443\/websocket\/api","playerId":...`
`{"websocketUrl":"wss:\/\/192.168.178.27:1443\/websocket\/api","playerId":...`

weird now it is working also with the ip adress entered, maybe you were right.. there was a blank. But i defenitly used the search button and just selected the entries from the dropdown.
Anyway thanks for your help :-)
