### ISSUE TITLE
group.play.notification  doesn't work with server .mp3 

### ISSUE THREAD

**Issue by Hinti73** [hklages/node-red-contrib-sonos-plus#287]
Since version 6.7.7 the group.play.notification no longer works via network share
Example: msg.payload = "x-file-cifs://nasserver/music/help.mp3"

node: Universal
command: group.play.notification
state: msg.payload = "x-file-cifs://nasserver/music/help.mp3"

With 6.7.3 it runs perfectly, even on Node-RED version: v3.1.8
I can therefore also confirm that the server share works via the SONOS music library

Has anything changed with the latest version that I missed?
Can anyone check and verify this?

the error occurs in several installations for me

what system:  docker on Synology 7.2
node-red-contrib-sonos-plus version: 6.7.7
Node-RED version: v3.1.8
NodeJS version: Where do I find the?

**Comment by hklages** [comment]
Hi. 
I can not reproduce this on my systems (unraid server, Node-RED 3.1.8, sonos plus 6.7.7). 
payload: "x-file-cifs://unraid/Multimedia/Music/AAAMyNotifications/foghorn_1.mp3"

Could you please install the official SONOS app (either for desktop or dmartphone), start group notification with cifs and watch the messages on the SONOS app.

**Comment by hklages** [comment]
... Hahaha, sometimes - even these days - computer and software are
mysteries...
