### ISSUE TITLE
Can't create snapshot when source is TV: "Root element is missing or invalid"

### ISSUE THREAD

**Issue by johnekarlsson** [hklages/node-red-contrib-sonos-plus#289]
### What node/command (topic)/state (payload)

node: Universal
command: group.create.snap

### In case of a bug: Are you able to reproduce the error

Yes

### Versions and Infrastructure

**what system:** Node Red running on Home assistant on an Intel NUC. 
**node-red-contrib-sonos-plus version:** 6.7.7
**Node-RED version:** 3.1.8

When trying to create a snapshot when the source is TV it throws an error. It works perfectly when another source is chosen as input.

<img width="588" alt="image" src="https://github.com/hklages/node-red-contrib-sonos-plus/assets/63417088/a2769777-74de-4216-a20e-4aaa86265cdf">

**Comment by johnekarlsson** [comment]
The full error message is:

`group.create.snap:Root element is missing or invalid (line 1, column 1)
  NOT_IMPLEMENTED
  ^
 :: Details: {"stack":"XmlError: Root element is missing or invalid (line 1, column 1)\n  NOT_IMPLEMENTED\n  ^\n\n    at Parser.error (/config/node_modules/@rgrove/parse-xml/src/lib/Parser.ts:775:12)\n    at new Parser (/config/node_modules/@rgrove/parse-xml/src/lib/Parser.ts:48:18)\n    at parseXml (/config/node_modules/@rgrove/parse-xml/src/index.ts:32:11)\n    at Function.ParseXml (/config/node_modules/@svrooij/sonos/lib/helpers/xml-helper.js:77:54)\n    at Function.DecodeAndParseXml (/config/node_modules/@svrooij/sonos/lib/helpers/xml-helper.js:52:21)\n    at AVTransportService.parseValue (/config/node_modules/@svrooij/sonos/lib/services/base-service.js:252:54)\n    at /config/node_modules/@svrooij/sonos/lib/services/base-service.js:246:30\n    at Array.forEach (<anonymous>)\n    at AVTransportService.parseEmbeddedXml (/config/node_modules/@svrooij/sonos/lib/services/base-service.js:245:14...`

**Comment by hklages** [comment]
Hi. Thats a bug. I can reproduce it. Give me some time to check, how I can solve that.

**Comment by hklages** [comment]
Please install release 6.7.8. 

Does it solve the issue?

**Comment by johnekarlsson** [comment]
Yes! It works now! Many thanks! 👍
