### ISSUE TITLE
Request for TTS with cache

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#29]
I really like what you have have achieved node and I have replace almost all Sonos functions with your node.

Would you be able to implement TTS functionality (like notification) with cache functionality similar to what is possible in [https://flows.nodered.org/node/node-red-contrib-sonospollytts](url) ==> this is avoiding unnecessary TTS request for repeated statements!

thanks for considering

**Comment by hklages** [comment]
Hi, thanks :-) 

sonospollytts is a great package. Caching is not easy. What is your use case.? Play a phrase? How many phrased do you have.  Do the phrases change?

**Comment by tsprivate** [comment]
Hi, i'm using the Sonospollytts for almost all my announcements/notificataions where I do not have static content (mp3 file... i have ~30 static phrases like "Balcony door is open")
- regular time notification (e.g. every 30m, when somebody comes home,..) .. no cache req for that
- notification on weather (e.g. morning, noon, evening or whenever there is upcoming rain/storm) .. here cache can be helpful to minimize TTS as it does not often change during day


In retrospect, it would be awesome if you get TTS working even without cache ! .. but at least save the mp3 file optionally ;)
-

**Comment by hklages** [comment]
Hi, for the (existing) static phrase you can simply copy these mp3 to the static folder and provide them as service with http commands. See [Complex examples](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-How-To-and-Examples), example K. 

> ::: K ::: To play a notification using a specific mp3 file on your local system you have to "serve" that file. Assuming that your NodeRED is installed on a Raspberry Pi with 192.168.178.55:

Copy your file to a specific directory for instance /home/pi/Downloads
Enable "serving files" in your settings.js: uncomment httpAdminRoot: '/admin', and uncomment/modify httpStatic: '/home/pi/downloads/',
Create a flow to serve your file (see example above)
Play notification using that file (http://192.168.178.55:1880/bell1.mp3)
Remark: At the Raspberry Pi you can use nano to edit the settings file, which is located in directory /usr/lib/node_modules/node-red: sudo nano settings.js.

**Comment by tsprivate** [comment]
Hi @hklages , yes ... I'm already using the your node for all my static notifications!

Thx for enhancing your node with TTS!

**Comment by Supergiovane** [comment]
Hello tsprivate
sonospollytts is aimed to only play TTS on Sonos, for example for alarm security panels, doorbells and so on. It's a very specific node.
The node-red-contrib-sonos-plus is a very well designed Sonos multi purpose node, music oriented. Both can be used at the same time, because sonospollytts will never handle music playlist and so on. ;-)

**Comment by tsprivate** [comment]
> 
> 
> Hello tsprivate
> sonospollytts is aimed to only play TTS on Sonos, for example for alarm security panels, doorbells and so on. It's a very specific node.
> The node-red-contrib-sonos-plus is a very well designed Sonos multi purpose node, music oriented. If you need music and tts, use sonos-plus.
> ;)

Yes, I really do like the sonospollytts and have it installed for ages. It just causes sometimes conflicts with this node here (cutting off notifications when two notifications are close) and I would like to have one solution to control and use my sonos devices

**Comment by hklages** [comment]
Sorry - it took some time to make up my mind. And I am still exploring the possibilities.

Have a look at this page: [TTS for SONOS](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification).

**Comment by tsprivate** [comment]
it works great with Polly-TTS

- Polly-TTS does the cache build in
- The original stream does resume after the notification 
- just set the cache folder to a shared location
- Update payload/topic to match Universal-Node requirements

**General flow:**
![image](https://user-images.githubusercontent.com/41630517/82392734-f9c63380-9a87-11ea-8081-a21a2bd8976b.png)

**Set Cache:**
![image](https://user-images.githubusercontent.com/41630517/82393037-af918200-9a88-11ea-9a9a-9195787c15bf.png)

**Prep Universal-Node:**
![image](https://user-images.githubusercontent.com/41630517/82393175-06975700-9a89-11ea-9afc-101fd98763a7.png)

Thanks a lot ... this can be closed now
