### ISSUE TITLE
device not reachable/rejected

### ISSUE THREAD

**Issue by NickBorgersOnLowSecurityNode** [hklages/node-red-contrib-sonos-plus#292]
### Description
I am suddenly having this error with basically all node types:
<img width="361" alt="image" src="https://github.com/hklages/node-red-contrib-sonos-plus/assets/73143201/311f53d6-a331-4b1d-95f0-ea14b032b358">

At first I thought one of my speakers had gone bad, so I tried removing it from the configuration but the issue persists. It seems to be a new issue between the module and the speakers.

I've tried:
- Installing Sonos speaker updates
- Reverting to 6.7 of this module
- Factory resetting speakers

I don't really know that the problem originates in a code change here given reversion doesn't fix it. Perhaps what I'm doing is unique and others aren't seeing this.

### What node/command (topic)/state (payload)

node: 
command: 
state: 

### Versions and Infrastructure

**what system:** podman on Fedora box, Home Assistant
**node-red-contrib-sonos-plus version:** 6.7.3, 6.7.8, 6.8.0
**Node-RED version:** 3.1.3 and 3.1.9
**NodeJS version:** using Docker container for node-red

```
"dependencies": {
        "node-red-contrib-home-assistant-websocket": "~0.63.1",
        "node-red-contrib-homekit-bridged": "~1.6.0",
        "node-red-contrib-log-elk": "~1.2.8",
        "node-red-contrib-pythonshell": "~1.5.4",
        "node-red-contrib-sonos-plus": "^6.7.3",
        "node-red-contrib-state": "~1.6.1",
        "node-red-contrib-sunevents": "~3.1.1",
        "node-red-contrib-tts-ultimate": "~2.0.5"
    }
```

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
Hi.
That sounds like a network problem. Do you use static ip address or dns
names? Please check the ip address of your speakers.

**Comment by NickBorgersOnLowSecurityNode** [comment]
Had been using dns names, have tried switching to ip addresess
Just got NodeRed running on a different host (laptop) and have the same problem behavior, so not a network problem between the server I'm running NodeRed on and the speaker.
Am going to try moving the laptop closer to the Sonos speakers from a network perspective.

**Comment by NickBorgersOnLowSecurityNode** [comment]
I can consistently reach them directly via the diagnostics HTTP interface
<img width="945" alt="image" src="https://github.com/hklages/node-red-contrib-sonos-plus/assets/73143201/60ab78be-3459-4b3c-9244-ab8d5afc570b">

Though we have been seeing unable to connect to Sonos errors in the app sometimes...

**Comment by hklages** [comment]
OK - thats a good sign.

Do you have a lot of nodes? 100 or more?

You can check one node and activate "Do not check avaialabily of sonos
player" and try that

**Comment by hklages** [comment]
Looking at your github pictures all sonos nodes have an issue - there it says "could not resolve dns names".

Are the players reachable in Home Assistant? as media player?

**Comment by NickBorgersOnLowSecurityNode** [comment]
The images generated for GitHub are in an ephemeral container in a GitHub Action; they're not captured from my running instance.

My problem is at a Sonos level, I rarely use the iOS app b/c everything is managed via NodeRed but now I've been poking around and Spotify isn't working reliably. 

It's silly, but I think the "what changed" is that a neighbor moved into the apartment next door and we're now just over the edge on RF interference for the SonosNet to function.

Will look at "Do not check availability of sonosplayer"; definitely a good thing to disable with how many Sonos nodes I have.

**Comment by NickBorgersOnLowSecurityNode** [comment]
Wow, "Do not check availability of sonosplayer" has made some difference. I'm not seeing the same connection errors anymore.

Also I think Sonos is having a Spotify connectivity problem at the moment, other music services ARE working in the app.

**Comment by NickBorgersOnLowSecurityNode** [comment]
OK, I'm chalking this up to general system network instability.

Disabling "Do NOT check availability of sonosplayer" did make a difference though; the system is working much better after [that change](https://github.com/NickBorgers/node-red/commit/03f70152618b3c8a09da009a7d0b145020a20da3). I think the burst of checks was contributing the problem originally, and I'm not seeing the specific error I initially was seeing and reported anymore. However, my system still isn't working properly and I think it has nothing to do with this code.

Thanks for responding, and quickly. You did help me get to a much better limping state. I move in a month anyway so I'll just live with degraded functionality of my Sonos system until then. With the config tweak to not check speaker state on deployment this codebase seems to be working properly and not causing or contributing to any problem.

**Comment by hklages** [comment]
... you can even more optimize by just using Node-RED link nodes and sending messages with topic/payload to a few universal node - maybe even to only one single universal node. 

Thanks for your feedback.

**Comment by hklages** [comment]
Added #293 to discussions
