### ISSUE TITLE
Universal node: household.set.alarmTime does not work

### ISSUE THREAD

**Issue by gitjho** [hklages/node-red-contrib-sonos-plus#296]
It seems there is a problem with setting alarm time in the universal node, when the command is given in msg.topic
In debug messages i notice that the command is converted to all lowercase but it is defined with a capital T in Time.

Message sent to universal node:
{"_msgid":"86ec5ea044e05685","topic":"household.set.alarmTime","payload":"7","alarmTime":"11:58:00"}

Response from universal node:
processInputMsg: command is invalid >>household.set.alarmtime  :: Details: none

If Universal node is permanently configured with topic "household.set.alarmTime" it works.

Running on:
Ubuntu 22.04.4 LTS
node-red-contrib-sonos-plus version 6.8.1
NodeJS version 18.17.1
Node-RED 3.1.7

**Comment by hklages** [comment]
Thanks for making me aware of that bug. 
All commands should be lower case! 

Please check 6.9.0.
Be aware: Any node with command household.set.alarmTime (the old command) has to be manually edited and the new command "household.set.alarmtime" has to be selected. 

Does that fix the issue for you?

**Comment by gitjho** [comment]
You are welcome, and yes it is fixed in 6.9.0 :-)
Now that Sonos has decided that the alarm feature should not be included i their new mobile app update, your great work will come to rescue :-D

Thank you very much for node-red-contrib-sonos-plus
