### ISSUE TITLE
New Sonos Firmware and App

### ISSUE THREAD

**Issue by Sandblech** [hklages/node-red-contrib-sonos-plus#300]
Question: Before I update my Sonos to the latest firmware 16.2 and app version, will all functions still be available via the NodeRed Sonos nodes? e.g. "libary.get.album" or "group.play.streamhttp" and so on. Are there any known problems in connection with the Sonos nodes? (I know about the other Sonos problems with the app).

Frage: Bevor ich mein Sonos auf den aktuellen Firmware 16.2 und App Stand bringe, sind danach noch alle Funktionen über die NodeRed Sonos Nodes zu nutzen? z.B "libary.get.album" oder "group.play.streamhttp"  und so weiter. gibt es bekannte Probleme in Zusammenhang mit den Sonos Nodes. (Die anderen Sonos Probleme mit der App kenne ich).

Danke für die Arbeit die in diese Nodes bis jetzt gesteckt wurde!
Gruß Michael

**Comment by hklages** [comment]
Hi. 

Antwort: Geht alles - streamhttp getestet mit Bayern 1 und die Library mit meinem SMB Server. 
Answer: Yes, everything should work fine.

Gruß Henning
