### ISSUE TITLE
How do I find the Tunein station id numbers?

### ISSUE THREAD

**Issue by AnandJhaveri** [hklages/node-red-contrib-sonos-plus#304]
### Description
How do I find the Tunein station id numbers?

### What node/command (topic)/state (payload)

node: Universal
command: group.play.tunein
state: 

### Versions and Infrastructure

**what system:** Raspberry Pi
**node-red-contrib-sonos-plus version:** 6.9.0
**Node-RED version:** 3.1.1
**NodeJS version:** v18.15.0

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
Hi. 

Use any webbrowser and visit the [tune in page](https://tunein.com/). Search for your radio such as SWR3 and start the stream. In this example the url is `https://tunein.com/radio/SWR3-996-s24896/` and `s24896` is the tunein number. 

Does that help?

**Comment by AnandJhaveri** [comment]
great!

thanks for your help.

regards,
Anand.
