### ISSUE TITLE
Correct URI path to local file for group.play.notification

### ISSUE THREAD

**Issue by qwertz79** [hklages/node-red-contrib-sonos-plus#306]
I´m getting stucked ... notification works fine with sounds via "x-file-cifs://" and "https://". But my sound is stored locally at "/home/pi/gong.mp3", whats the right scheme or prefix to play this sound?

**Comment by hklages** [comment]
The Sonos Player is only able to access your song with "standard" methods - usually that is smb/cifs smb file serving or http / https. Either you add your song to a NAS device and use the Sonos Library Media functionality or you set up a "https file service".

In Node-RED you can do that with the http node. See this example [serve files](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification). Hope that helps

**Comment by qwertz79** [comment]
Okay thanks, i´ve installed a smb server and load the sound with "x-file-cifs://" from the local drive.  Additionally i can share the sounds through the network - thats cool also ;-)
