### ISSUE TITLE
group.play.notification produces an error while returning to previous content if Sonos device has fixed volume

### ISSUE THREAD

**Issue by pe231** [hklages/node-red-contrib-sonos-plus#309]
Thanks very much for this very helpful project, I use it everyday.

### Description
I want to use "group.play.notification" for a notification as intented. For player with variable volume, it works as expected.
For a player with fixed volume (Connect connected to my HiFi system), I get this error in debug:

group.play.notification:Sonos error on SetVolume UPnPError 501 (Action failed) :: Details: {"stack":"SonosError: Sonos error on SetVolume UPnPError 501 (Action failed)\n    at RenderingControlService.handleErrorResponse (/data/node_modules/@svrooij/sonos/lib/services/base-service.js:227:23)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Object.restoreGroupSnapshot (/data/node_modules/node-red-contrib-sonos-plus/src/Commands.js:416:9)\n    at playGroupNotification (/data/node_modules/node-red-contrib-sonos-plus/src/Commands.js:120:5)\n    at Object.groupPlayNotification [as group.play.notification] (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-universal.js:1303:5)","message":"Sonos error on SetVolume UPnPError 501 (Action failed)","Action":"SetVolume","FaultCode":"s:Client","Fault":"UPnPError","UpnpErrorCode":501,"UpnpErrorDescription":"Action failed","name":"SonosError"}

After playing the notification, Sonos doesn't return to the previous content, so playback is stopped.

If I set the volume to "variable" everything works fine on the same device.

### What node/command (topic)/state (payload)

node: Universal  
command: group.play.notification 

### In case of a bug: Are you able to reproduce the error

yes

### Versions and Infrastructure

**what system:** docker on Raspberry Pi
**node-red-contrib-sonos-plus version:** 6.9.0 
**Node-RED version:** 4.0.5 
**NodeJS version:** v20.18.0 

Thanks in advance.
Best regards
Peter

**Comment by hklages** [comment]
For me it seems that that is exactly what SONOS want - see the following article. I can not change that. 

![sonos_connect](https://github.com/user-attachments/assets/ab1236d3-a663-41d0-ab65-aa00dcb07f8c)

**Comment by pe231** [comment]
I don't want to change the volume, I just wanted to play the notification without changing the volume:
![grafik](https://github.com/user-attachments/assets/add21311-3464-4232-8dce-afcb880abee3)
As a workaround I deactivated the fixed volume in Sonos and set the volume in Node Red.

Best regards
Peter

**Comment by hklages** [comment]
oh - sorry. I did not read that. I will check again.

**Comment by pe231** [comment]
No problem, I did not write that I don't change the volume, so it was not clearly described from me.

**Comment by hklages** [comment]
I just released 6.9.1 - can you please check. 

Does it solve the issue?

**Comment by pe231** [comment]
I've just updated and it works now.
Thank you very much for the fast solution.

Vielen Dank!
Best regards
Peter
