### ISSUE TITLE
May one pair (stereo) not group players also via node-red or only via sonso app?

### ISSUE THREAD

**Issue by AndreasMaverick** [hklages/node-red-contrib-sonos-plus#32]
I'm looking for an oportiunity to pair two players to form a stereo pair, not only a group playing the same mono channel. Is there already a feature in the contrib package available, like the pairing from the sonos app?
Thank you in advance for your assistance...

**Comment by hklages** [comment]
There is a command, but no description. I need a description how to set up it. 
[paring](https://github.com/SoCo/SoCo/issues/612)

**Comment by AndreasMaverick** [comment]
Whom may one ask top obtain this information?

**Comment by AndreasMaverick** [comment]
I found this Python Script:
https://github.com/erikmansson/pair-sonos
May you find the required information in there?

**Comment by hklages** [comment]
Yes, thats exactly what i need. In the next days I am going to publish 2.0.1 including the commands. I let you know how to use.

**Comment by AndreasMaverick** [comment]
Great, thank's a lot. Looking forward...

**Comment by hklages** [comment]
Hi. I just published 2.1.0 with `create_stereopair` and `seperate_stereopair` in "Control Player" node. 
To pair two players, they have to be the same model and we need the so called uuid. The flow gets the uuid from the first player (get_property), moves the data to the right place and then start the pairing with that data. I could NOT test it as I don't have 2 player of same type. 

`[{"id":"46e04a29.ea75f4","type":"inject","z":"99e6906e.c69df","name":"","topic":"","payload":"get_properties","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":540,"wires":[["a2d2d0be.38181"]]},{"id":"a2d2d0be.38181","type":"sonos-get-status","z":"99e6906e.c69df","confignode":"a1fa48a2.6e0c98","name":"player left","x":261,"y":540,"wires":[["320d05ad.4dcd0a"]]},{"id":"320d05ad.4dcd0a","type":"change","z":"99e6906e.c69df","name":"create stereopair","rules":[{"t":"set","p":"topic","pt":"msg","to":"uuid","tot":"msg"},{"t":"set","p":"modelName","pt":"msg","to":"payload.modelName","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"create_stereopair","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":431,"y":540,"wires":[["12b0b905.cb9827"]]},{"id":"12b0b905.cb9827","type":"sonos-control-player","z":"99e6906e.c69df","confignode":"32a98882.56e1c8","name":"player right","x":583,"y":467,"wires":[["47f082f6.abd44c"]]},{"id":"47f082f6.abd44c","type":"debug","z":"99e6906e.c69df","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":603,"y":507,"wires":[]},{"id":"a1fa48a2.6e0c98","type":"sonos-config","z":"","name":"play1","serialnum":"B8-E9-37-58-31-C0:A","ipaddress":"192.168.178.38"},{"id":"32a98882.56e1c8","type":"sonos-config","z":"","name":"bad","serialnum":"00-0E-58-FE-3A-EA:5","ipaddress":"192.168.178.35"}]`

**Comment by AndreasMaverick** [comment]
Wow, this was pretty fast. I'll try it on this weekend and let you know about the result. Thank you very much for your great support!

**Comment by AndreasMaverick** [comment]
I tried it. The result is that the right player gets paired with something unknown. It looks in the Sonos App Like this: <player name> (?+R)
I tried to pair two Play 5 of 1.gen.
Do you have any suggestion?

**Comment by hklages** [comment]
Yes. :-) 
Please (wait an hour) and install 2.1.1 Here is an example flow. I dont check anymore "same model" and simplified the separate_stereopair.

`[{"id":"20fdba72.27d266","type":"inject","z":"99e6906e.c69df","name":"","topic":"","payload":"get_properties","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":540,"wires":[["ecc6b9fb.a28bb8"]]},{"id":"ecc6b9fb.a28bb8","type":"sonos-get-status","z":"99e6906e.c69df","confignode":"32a98882.56e1c8","name":"player right","x":271,"y":540,"wires":[["986618a9.2293e8"]]},{"id":"986618a9.2293e8","type":"change","z":"99e6906e.c69df","name":"create stereopair","rules":[{"t":"set","p":"topic","pt":"msg","to":"uuid","tot":"msg"},{"t":"set","p":"modelName","pt":"msg","to":"Sonos Play:1","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"create_stereopair","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":490,"y":540,"wires":[["dde74552.b1d598"]]},{"id":"204a38d9.0e8e18","type":"inject","z":"99e6906e.c69df","name":"","topic":"","payload":"separate_stereopair","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":490,"y":500,"wires":[["dde74552.b1d598"]]},{"id":"91ba37a8.e4d708","type":"debug","z":"99e6906e.c69df","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":723,"y":500,"wires":[]},{"id":"dde74552.b1d598","type":"sonos-control-player","z":"99e6906e.c69df","confignode":"2113e9bb.c52236","name":"player left","x":720,"y":540,"wires":[["91ba37a8.e4d708"]]},{"id":"32a98882.56e1c8","type":"sonos-config","z":"","name":"bad","serialnum":"00-0E-58-FE-3A-EA:5","ipaddress":"192.168.178.35"},{"id":"2113e9bb.c52236","type":"sonos-config","z":"","name":"play1","serialnum":"B8-E9-37-58-31-C0:A","ipaddress":""}]`

**Comment by AndreasMaverick** [comment]
OK, thank's. I'll check it tomorrow and let you know...

**Comment by AndreasMaverick** [comment]
Pairing is working 😊 fine!
But injecting the seperate command results into the following Error Message:

"separate stereo pair - statusCode >>500 & upnpErrorCode >>402 upnpErrorMessage >>Invalid Args :: Details: none"

**Comment by hklages** [comment]
We make progess :-) 

It seems that we have to use the same flow as in "create_stereopair" - not the shortcut. For that I will change the input parameter - tomorrow with 2.1.3

**Comment by AndreasMaverick** [comment]
OK, then I will test it again.

**Comment by hklages** [comment]
Hi. Here are the flows for 2.1.3. I modified separate_stereopairs and now double cross my fingers.

`[{"id":"7842b4b6.3a01dc","type":"inject","z":"99e6906e.c69df","name":"","topic":"","payload":"get_properties","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":586,"wires":[["aa30c460.a2b5c8"]]},{"id":"20fdba72.27d266","type":"inject","z":"99e6906e.c69df","name":"","topic":"","payload":"get_properties","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":540,"wires":[["ecc6b9fb.a28bb8"]]},{"id":"ecc6b9fb.a28bb8","type":"sonos-get-status","z":"99e6906e.c69df","confignode":"32a98882.56e1c8","name":"player right","x":270,"y":540,"wires":[["986618a9.2293e8"]]},{"id":"aa30c460.a2b5c8","type":"sonos-get-status","z":"99e6906e.c69df","confignode":"32a98882.56e1c8","name":"player right","x":270,"y":586,"wires":[["393ee1d7.60b13e"]]},{"id":"393ee1d7.60b13e","type":"change","z":"99e6906e.c69df","name":"separate stereopair","rules":[{"t":"set","p":"topic","pt":"msg","to":"uuid","tot":"msg"},{"t":"set","p":"modelName","pt":"msg","to":"Sonos Play:1","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"separate_stereopair","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":450,"y":586,"wires":[["dde74552.b1d598"]]},{"id":"986618a9.2293e8","type":"change","z":"99e6906e.c69df","name":"create stereopair","rules":[{"t":"set","p":"topic","pt":"msg","to":"uuid","tot":"msg"},{"t":"set","p":"modelName","pt":"msg","to":"Sonos Play:1","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"create_stereopair","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":450,"y":540,"wires":[["dde74552.b1d598"]]},{"id":"dde74552.b1d598","type":"sonos-control-player","z":"99e6906e.c69df","confignode":"2113e9bb.c52236","name":"player left","x":540,"y":480,"wires":[["91ba37a8.e4d708"]]},{"id":"91ba37a8.e4d708","type":"debug","z":"99e6906e.c69df","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":630,"y":520,"wires":[]},{"id":"32a98882.56e1c8","type":"sonos-config","z":"","name":"bad","serialnum":"00-0E-58-FE-3A-EA:5","ipaddress":"192.168.178.35"},{"id":"2113e9bb.c52236","type":"sonos-config","z":"","name":"play1","serialnum":"B8-E9-37-58-31-C0:A","ipaddress":""}]`

**Comment by AndreasMaverick** [comment]
Well, that's it. Great, woderfull Job!!! Pairing and decoupling is now working as expected. Thank you once again for your outstanding support.
Only one remark. In your provided example you should replace the string "Sonos Play:1" again by
msg.payload.modelName
Thank you Mate. This was really agile development 😉

**Comment by hklages** [comment]
Super. Thanks.  
I corrected the example. In fact we dont need the modelName anymore as it also works with not compatible player - strange but ok. 

I close this topic. Have a good time.
