### ISSUE TITLE
Strange behavior with play_notification when sending it to multiple players at once

### ISSUE THREAD

**Issue by Markus-** [hklages/node-red-contrib-sonos-plus#34]
Hi,

as said in the other issue I still have some problems. I just updated to 2.1.4 but I think there is an issue with sending a notification to multiple players at once.

I tried to find separate the issue with the following flow:
`[
    {
        "id": "104f125d.150b5e",
        "type": "tab",
        "label": "Debug Sonos",
        "disabled": false,
        "info": ""
    },
    {
        "id": "8b973d5b.5bae7",
        "type": "inject",
        "z": "104f125d.150b5e",
        "name": "BOTH",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 130,
        "y": 120,
        "wires": [
            [
                "84ca48ce.a5a2b8"
            ]
        ]
    },
    {
        "id": "84ca48ce.a5a2b8",
        "type": "change",
        "z": "104f125d.150b5e",
        "name": "BOTH Doorbell @ Volume15",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "play_notification",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic-old",
                "pt": "msg",
                "to": "http://10.20.0.2/addons/red/media/doorbell.mp3",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "volume",
                "pt": "msg",
                "to": "15",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "http://soundbible.com/mp3/foghorn-daniel_simon.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 360,
        "y": 120,
        "wires": [
            [
                "d7e8bf34.c2886",
                "c96fe98c.9bc738"
            ]
        ]
    },
    {
        "id": "c96fe98c.9bc738",
        "type": "sonos-control-player",
        "z": "104f125d.150b5e",
        "confignode": "588a41a4.76a3d",
        "name": "SONOS-AZM",
        "x": 640,
        "y": 120,
        "wires": [
            [
                "834d1f76.59df2"
            ]
        ]
    },
    {
        "id": "d7e8bf34.c2886",
        "type": "sonos-control-player",
        "z": "104f125d.150b5e",
        "confignode": "a8e8ea1b.3d38d8",
        "name": "SONOS-FI",
        "x": 630,
        "y": 180,
        "wires": [
            [
                "834d1f76.59df2"
            ]
        ]
    },
    {
        "id": "4bccc5d2.d41e2c",
        "type": "inject",
        "z": "104f125d.150b5e",
        "name": "activate_queue AZ",
        "topic": "",
        "payload": "activate_queue",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 340,
        "wires": [
            [
                "726f5050.2dcb8"
            ]
        ]
    },
    {
        "id": "726f5050.2dcb8",
        "type": "sonos-manage-queue",
        "z": "104f125d.150b5e",
        "confignode": "588a41a4.76a3d",
        "name": "",
        "x": 640,
        "y": 300,
        "wires": [
            [
                "834d1f76.59df2"
            ]
        ]
    },
    {
        "id": "834d1f76.59df2",
        "type": "debug",
        "z": "104f125d.150b5e",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 930,
        "y": 220,
        "wires": []
    },
    {
        "id": "114a3dc1.beca52",
        "type": "sonos-manage-queue",
        "z": "104f125d.150b5e",
        "confignode": "a8e8ea1b.3d38d8",
        "name": "",
        "x": 640,
        "y": 360,
        "wires": [
            [
                "834d1f76.59df2"
            ]
        ]
    },
    {
        "id": "ac7203fc.8b529",
        "type": "change",
        "z": "104f125d.150b5e",
        "name": "FITNESS Doorbell @ Volume15",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "play_notification",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic-old",
                "pt": "msg",
                "to": "http://10.20.0.2/addons/red/media/doorbell.mp3",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "volume",
                "pt": "msg",
                "to": "15",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "http://soundbible.com/mp3/foghorn-daniel_simon.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 370,
        "y": 200,
        "wires": [
            [
                "d7e8bf34.c2886"
            ]
        ]
    },
    {
        "id": "e5bff98e.3a7d58",
        "type": "change",
        "z": "104f125d.150b5e",
        "name": "AZ Doorbell @ Volume15",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "play_notification",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic-old",
                "pt": "msg",
                "to": "http://10.20.0.2/addons/red/media/doorbell.mp3",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "volume",
                "pt": "msg",
                "to": "15",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "http://soundbible.com/mp3/foghorn-daniel_simon.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 350,
        "y": 160,
        "wires": [
            [
                "c96fe98c.9bc738"
            ]
        ]
    },
    {
        "id": "45310ece.6c5c6",
        "type": "inject",
        "z": "104f125d.150b5e",
        "name": "AZ",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 130,
        "y": 160,
        "wires": [
            [
                "e5bff98e.3a7d58"
            ]
        ]
    },
    {
        "id": "41239dd9.d056c4",
        "type": "inject",
        "z": "104f125d.150b5e",
        "name": "FITNESS",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 140,
        "y": 200,
        "wires": [
            [
                "ac7203fc.8b529"
            ]
        ]
    },
    {
        "id": "9490bd6e.06a2c",
        "type": "inject",
        "z": "104f125d.150b5e",
        "name": "activate_queue FITNESS",
        "topic": "",
        "payload": "activate_queue",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 190,
        "y": 380,
        "wires": [
            [
                "114a3dc1.beca52"
            ]
        ]
    },
    {
        "id": "4cc2f901.f56c38",
        "type": "inject",
        "z": "104f125d.150b5e",
        "name": "activate_queue BOTH",
        "topic": "",
        "payload": "activate_queue",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 180,
        "y": 300,
        "wires": [
            [
                "726f5050.2dcb8",
                "114a3dc1.beca52"
            ]
        ]
    },
    {
        "id": "7c27fba2.d8f8e4",
        "type": "inject",
        "z": "104f125d.150b5e",
        "name": "",
        "topic": "",
        "payload": "stop",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 570,
        "y": 240,
        "wires": [
            [
                "d7e8bf34.c2886",
                "c96fe98c.9bc738"
            ]
        ]
    },
    {
        "id": "588a41a4.76a3d",
        "type": "sonos-config",
        "z": "",
        "name": "SONOS AZM",
        "serialnum": "",
        "ipaddress": "10.10.0.7"
    },
    {
        "id": "a8e8ea1b.3d38d8",
        "type": "sonos-config",
        "z": "",
        "name": "SONOS-FI",
        "serialnum": "",
        "ipaddress": "10.10.0.18"
    }
]`

So:
 activating the queue on AZ OR FITNESS and sending a notification to it results in: Playing Music -> Playing Notification -> Playing Music (resuming queue) - DEBUG msgs as expected.

activating the queue on BOTH and sending the notification to BOTH results in: Playing Music on Both players -> Playing Notification on Both players -> Resuming Queue on Fitness - Debug msg for FITNESS.

Again my strange network or does the flow works for you?

Thanks
Markus

- in:

**Comment by Markus-** [comment]
Just tried to debug a little bit more.

It works when the two players are grouped and I send the notification to the leader.
It also works when I send the notification to the follower (it plays it and rejoins the playback).

It does still not work if I send two messages to two independent speakers. One speaker plays the notification and then stops the playback.

Could you test it on your site?
Regards
Markus

**Comment by hklages** [comment]
Yes - I could reproduce the error. Even when using different files the outcome is the same. 

I am still waiting for an update on [node-sonos](https://github.com/bencevans/node-sonos) to get better error messages (issue 448).  

On the week end I will dig into that.

**Comment by hklages** [comment]
Group should work. The only problem is that the volume in only increase for the addressed player. The other one is quite. If you send a adjust volume  and afterwords back it might work.

**Comment by Markus-** [comment]
In a group it works as designed. I could not find any issue with the volume. 

Or do you talk about sending the messages to two players?

**Comment by hklages** [comment]
Put two player in group. Set the volume of both to 10. Then start play notification with a volume 60. Watch it in the original SONOS app. You both will stay in the group but only one will increase the  volume

**Comment by Markus-** [comment]
Ah Ok. This is a "separate" issue inside a given group. With single players it doesn't work at all, correct?

**Comment by hklages** [comment]
There are several issues: 
a) sondbible.com does not seem to be very stable. 
> It looks like the webpage at http://soundbible.com/ might be having issues, .... 

b) The API node-sonos `Sonos.prototype.playNotification` method starts a listener. That's works fine on my windows system but on CCU3 the listener causes a crash (not handled promise) or does not play notification/revert back on all players. 

So I will create a another "play_notification_new" which is not based on the above command.

**Comment by Markus-** [comment]
I think it's also not working with a local file. Regarding b): Sounds good to know the problem. Looking forward to your new solution.

Thanks
Markus

**Comment by hklages** [comment]
Hi Markus. I have just published 2.1.6 - there is an undocumented command "`play_notif`" at the "Control Player" node. properties are among others: `msg.volume`, `msg.useCoordinator`, `msg. sameVolume`. 

useCoordinator (boolean true/false) uses the coordinator in that group instead of the original player.  

sameVolume (boolean true/false) will set all player in that group to the specified volume. 
That makes only sense in case you you use useCoordinator or the original player is in already the player. 

On my test system (Raspberry Pi, nodeRED, 4 sonos players) it works fine. 

Sending to a client in a group the client-player will leave the group, play notification and then joins the group again. 

Sending to a coordinator (or to a client with msg.useCoordinator = true) will play the notification on all members of the group and if you choose msg.sameVolume = true everywhere the same volume. 

I could also send 3 messages to 3 independent player and each of them plays the notification and returns to the previous music. 

Next week I am going to do the testing on CCU3/RedMatc and if that also works there the code will be published under 2.2 with full documentation. 

Awating your feedback ... :-)

**Comment by hklages** [comment]
There is now also a flow to demonstrate the serving of mp3 files (also TTS) with nodered http. 
[serving mp3 files](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification)

**Comment by Markus-** [comment]
Hi. 

Sorry for the delay - it kind of works ;)
The music resumes on all players after the notification - BUT:
The queue seems to get activated in any case:
 - Before: Fitness is stopped, office plays music; After: Both players activates their queues
 - Before: Both players are stopped; After: Both players play music (queue)
 - Before: Office stopped; After: Offices plays music

Leaving the group while playing seems to work, but also here the queue is activated after the notification was played in every case.

Did you test it without playing music?
Regards
Markus

**Comment by hklages** [comment]
Hi - I fixed the bug in 2.1.7. 

I did not do intense testing - wanted to get your feedback first. When everything work I will write the documentation and do more testing. 

`play_notification` does "listen" to the player and after receiving an "end" event it triggers the "roll back". That event handling is not stable on CCU. Thats why I changed the function totally. 
`play_noti` calculates the length of the mp3 and sets a timer. It then reacts on that timer.

There is another option `msg.duration` to define you own length - default is to calculate the duration.

You  can also try `msg.onlyWhenPlaying`  for additional "adjustments". 

Hope it works now :-)
`

**Comment by Markus-** [comment]
Hi,

most of the things are working now as expected. I also found a little bug.

Create a Group. Stop playback. Fire a notification to BOTH players (not the group) with onlyWhenPlaying set to true. The "slave" plays the notification while the Controller accepts the flag. 

All other quick tests worked as you mentioned. So I think I can implement the doorbell at the weekend!

Can you also implement the opposite of onlyWhenPlaying? It could be helpful when you play the notification an all players but leave out the active ones. Probably rename the option to 
playOn with the options "all, active, inactive" or sth. like this.

Thanks and Regards
Markus

**Comment by Markus-** [comment]
Could you reproduce this error?

Regards
Markus

**Comment by hklages** [comment]
Yes - the reason is that all "client/slave" players in a group return "playing" as the state - even when the group is stopped. You can verify that with get_state on a client in a group. So I have to check the state of the coordinator (and not the client) even if msg. useCoordinator is missing/false. 
I will try to fix it in 2.2.0 coming next week. 

Regarding playOn option:  Not sure whether I can implement that (see above). What about implementing it in a flow?  Can you give an example?

**Comment by Markus-** [comment]
Ah ok. 

I tried it with a flow. We discussed the addressing by name - this would be helpful here. 
Should we start an issue for tracking the feature request? 

The flow works. 
[
    {
        "id": "bc9fd2bf.465b5",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "bd11fae9.2e1ba8",
        "type": "inject",
        "z": "bc9fd2bf.465b5",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 80,
        "y": 220,
        "wires": [
            [
                "a6c2534e.f2359"
            ]
        ]
    },
    {
        "id": "a6c2534e.f2359",
        "type": "change",
        "z": "bc9fd2bf.465b5",
        "name": "Set Basics",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "get_basics",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "volume",
                "pt": "msg",
                "to": "15",
                "tot": "num"
            },
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "http://www.sorrygottago.com/SoundFiles/DOORBELL.mp3",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 240,
        "y": 220,
        "wires": [
            [
                "4ed49aaa.bfa8f4",
                "adbd948b.a89548"
            ]
        ]
    },
    {
        "id": "4ed49aaa.bfa8f4",
        "type": "sonos-get-status",
        "z": "bc9fd2bf.465b5",
        "confignode": "588a41a4.76a3d",
        "name": "AZM",
        "x": 370,
        "y": 100,
        "wires": [
            [
                "67602b66.32dff4"
            ]
        ]
    },
    {
        "id": "adbd948b.a89548",
        "type": "sonos-get-status",
        "z": "bc9fd2bf.465b5",
        "confignode": "a8e8ea1b.3d38d8",
        "name": "FITNESS",
        "x": 380,
        "y": 320,
        "wires": [
            [
                "4713c2b1.7f12bc"
            ]
        ]
    },
    {
        "id": "7810f537.7b041c",
        "type": "change",
        "z": "bc9fd2bf.465b5",
        "name": "Play Noti",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "play_noti",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 520,
        "y": 160,
        "wires": [
            [
                "1fa4353d.490a3b"
            ]
        ]
    },
    {
        "id": "67602b66.32dff4",
        "type": "switch",
        "z": "bc9fd2bf.465b5",
        "name": "Playing?",
        "property": "state",
        "propertyType": "msg",
        "rules": [
            {
                "t": "neq",
                "v": "playing",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 500,
        "y": 100,
        "wires": [
            [
                "7810f537.7b041c"
            ]
        ]
    },
    {
        "id": "4713c2b1.7f12bc",
        "type": "switch",
        "z": "bc9fd2bf.465b5",
        "name": "Playing?",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "neq",
                "v": "playing",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 520,
        "y": 320,
        "wires": [
            [
                "f0100da0.d7d8a"
            ]
        ]
    },
    {
        "id": "f0100da0.d7d8a",
        "type": "change",
        "z": "bc9fd2bf.465b5",
        "name": "Play Noti",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "play_noti",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 520,
        "y": 260,
        "wires": [
            [
                "7f5e5f72.cf47"
            ]
        ]
    },
    {
        "id": "7f5e5f72.cf47",
        "type": "sonos-control-player",
        "z": "bc9fd2bf.465b5",
        "confignode": "a8e8ea1b.3d38d8",
        "name": "SONOS-FI",
        "x": 670,
        "y": 260,
        "wires": [
            [
                "70a85421.3373cc"
            ]
        ]
    },
    {
        "id": "1fa4353d.490a3b",
        "type": "sonos-control-player",
        "z": "bc9fd2bf.465b5",
        "confignode": "588a41a4.76a3d",
        "name": "SONOS-AZM",
        "x": 680,
        "y": 160,
        "wires": [
            [
                "70a85421.3373cc"
            ]
        ]
    },
    {
        "id": "70a85421.3373cc",
        "type": "debug",
        "z": "bc9fd2bf.465b5",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 830,
        "y": 200,
        "wires": []
    },
    {
        "id": "588a41a4.76a3d",
        "type": "sonos-config",
        "z": "",
        "name": "SONOS AZM",
        "serialnum": "",
        "ipaddress": "10.10.0.7"
    },
    {
        "id": "a8e8ea1b.3d38d8",
        "type": "sonos-config",
        "z": "",
        "name": "SONOS-FI",
        "serialnum": "",
        "ipaddress": "10.10.0.18"
    }
]

Regards
Markus

**Comment by hklages** [comment]
Hi. Your flow is fine. So we dont need the "only if not playing" Maybe I also leave the "OnlyIfPlaying" because NodeRED is ideal for that. 

Regarding "command": Another issue is NOT necessary. I have already a few commands available in the "Universal Node". 

When 3.0.0 is out, please use the new Node for notification because the above command will be "depreciated".

**Comment by hklages** [comment]
Hi. It took a while to implement it. 3.0.0 is published with a new node Universal: 
play.notification plays on all player in a group - group is kept
joiner.play.notification plays only on a joiner in a group. 

and hopefully in 3.1 I will have a property msg.players = ['kitchen', 'sauna'] - where you can specify multiple groups to play the notifcation. Right now you have to send to commands but should work.

**Comment by Markus-** [comment]
I already played around a bit...

If I send the play.notification to each player (broadcast) while they are grouped the behavior is a bit strange.

The notification is played two times on both players (one after the other) and the playback does not resume. Instead the "Playlist" contains the doorbell.mp3.

Is this a thing I have to precheck in a flow or could the node be extended?
```
[
    {
        "id": "c18174eb.f63798",
        "type": "debug",
        "z": "3313c5e6.daaf5a",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 730,
        "y": 160,
        "wires": []
    },
    {
        "id": "1228ab68.d90265",
        "type": "sonos-universal",
        "z": "3313c5e6.daaf5a",
        "confignode": "a8e8ea1b.3d38d8",
        "name": "",
        "x": 540,
        "y": 160,
        "wires": [
            [
                "c18174eb.f63798"
            ]
        ]
    },
    {
        "id": "54af676b.ca69c8",
        "type": "change",
        "z": "3313c5e6.daaf5a",
        "name": "Doorbell @ Volume20",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "play.notification",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "http://10.20.0.2/addons/red/media/doorbell.mp3",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "volume",
                "pt": "msg",
                "to": "20",
                "tot": "num"
            },
            {
                "t": "set",
                "p": "duration",
                "pt": "msg",
                "to": "00:00:04",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "playerName",
                "pt": "msg",
                "to": "AZ Markus",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 320,
        "y": 120,
        "wires": [
            [
                "1228ab68.d90265"
            ]
        ]
    },
    {
        "id": "e729c79b.64a358",
        "type": "change",
        "z": "3313c5e6.daaf5a",
        "name": "Doorbell @ Volume20",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "play.notification",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "http://10.20.0.2/addons/red/media/doorbell.mp3",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "volume",
                "pt": "msg",
                "to": "20",
                "tot": "num"
            },
            {
                "t": "set",
                "p": "duration",
                "pt": "msg",
                "to": "00:00:04",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "playerName",
                "pt": "msg",
                "to": "Fitness",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 320,
        "y": 200,
        "wires": [
            [
                "1228ab68.d90265"
            ]
        ]
    },
    {
        "id": "ab3ba2e8.7165d",
        "type": "inject",
        "z": "3313c5e6.daaf5a",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 80,
        "y": 160,
        "wires": [
            [
                "54af676b.ca69c8",
                "e729c79b.64a358"
            ]
        ]
    },
    {
        "id": "a8e8ea1b.3d38d8",
        "type": "sonos-config",
        "z": "",
        "name": "SONOS-FI",
        "serialnum": "",
        "ipaddress": "10.10.0.18"
    }
]
```

**Comment by hklages** [comment]
That works as designed :-)  The first command makes a snapshop, plays the notification and then restores the original state. In the meantime, the second command arrives and does the same and interfering with this process. There is no SONOS function to block that. But you can implement a queue. 

The intention of the play.notification command is, that you only need one command to play on all members of the group. So there is no need to send to multiple players in that group. They will all play in sync and you can also set the volume. 

In case you have many notifications, which may interfere, I also recommend to "queue" them.  Here is an [example](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification). 

Queuing can be done with the following function: `[{"id":"c6772716.60af68","type":"function","z":"4318847d.0693cc","name":"queue","func":"// modified version - originally from https://gist.github.com/dceejay/cea8afa28b7a93ebdc0f \n\n// restartQueue = create new\nif (msg.hasOwnProperty(\"restartQueue\")) {\n    context.queue = []\n    \n// if queue doesn't exist, create it    \n} else {\n    context.queue = context.queue || []\n    context.busy = context.busy || false\n\n    // if the msg is a trigger one release next message\n    if (msg.hasOwnProperty(\"releaseNext\")) {\n        if (context.queue.length > 0) {\n            var m = context.queue.shift()\n            node.status({ fill: 'green', shape: 'dot', text: context.queue.length })\n            return m \n        }\n        else {\n            context.busy = false;\n        }\n    }\n    else {\n        if (context.busy) {\n            // if busy add to queue\n            context.queue.push(msg);\n        }\n        else {\n        // otherwise we are empty so just pass through and set busy flag\n            context.busy = true;\n            node.status({ fill: 'green', shape: 'dot', text: context.queue.length })\n            return msg;\n        }\n    }\n}\nnode.status({ fill: 'green', shape: 'dot', text: context.queue.length })\n\nreturn null;","outputs":1,"noerr":0,"x":1012,"y":1315,"wires":[["7435b64e.0a2fb8"]]}]`

**Comment by Markus-** [comment]
The thing is I want to use my Sonos-System as Doorbell.
So I need to play the notification on all speakers - independent which groups are actually active.

For this case I actually don't see the universal node - I will fire the event against each player individually (CTRL Player). This works as expected.

I thing this Issue can be closed again, correct?

Regards
Markus

**Comment by hklages** [comment]
YES.
