### ISSUE TITLE
Play notification error

### ISSUE THREAD

**Issue by githubwesseln** [hklages/node-red-contrib-sonos-plus#35]
The error message at "play notification" is:

play notification - Request failed with status code 412 :: Details: {"stack":"Error: Request failed with status code 412\n    at createError (/data/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/data/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/data/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","message":"Request failed with status code 412","config":{}}

The version of "node-red-contrib-sonos-plus" is 2.1.7
The version of "node-red" is 1.0.3

**Comment by hklages** [comment]
Hi.

Code 412 stands for: Precondition failed. 

- What is your topic (the file to be used for playing)? Can you please export the part of the flow.

Do you use pure node-red or in combination with RedMatic? 

There is an - so far undocumented- new command: `play_noti` 
Can you please try that.

**Comment by githubwesseln** [comment]
Lese gerade Standort München, deshalb die Antwort auf deutsch, vielen Dank für die schnelle Antwort.
Habe noch einiges getestet. Die Fehlermeldung ist nicht immer reproduzierbar, habe die Gründe dafür noch nicht gefunden. Dachte erst nach einem Reboot wäre der Fehler beseitigt, aber nach einiger Zeit trat er teilweise wieder auf.
Im Falle der Fehlermeldung wird der Text ausgegeben, aber der Ursprungszustand von Sonos nicht wieder hergestellt.
Zusätzliche Info: Node Red läuft im Docker.
Die neue Option funktionierte nur bei kurzen Texten ("NewPost"; bislang ohne Fehlermeldung). Bei langen Texten ("New") erfolgt keine Ausgabe. Der Ursprungszustand von Sonos wird wieder hergestellt.

Hier der Test-Flow:

[{"id":"89ff2493.12e0f8","type":"sonos-control-player","z":"afb06c02.a05f38","confignode":"1372ec11.ef8454","name":"","x":600,"y":220,"wires":[[]]},{"id":"3df12c38.a90f94","type":"function","z":"afb06c02.a05f38","name":"Old","func":"\nmsg.payload='play_notification';\nmsg.topic='http://192.168.178.32/mp3/an_3d_e.mp3';\n\nreturn msg;\n","outputs":1,"noerr":0,"x":270,"y":220,"wires":[["89ff2493.12e0f8"]]},{"id":"fc121eee.0585a","type":"inject","z":"afb06c02.a05f38","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":220,"wires":[["3df12c38.a90f94"]]},{"id":"cb6f535e.92c4f8","type":"function","z":"afb06c02.a05f38","name":"New","func":"\nmsg.payload='play_noti';\nmsg.topic='http://192.168.178.32/mp3/an_3d_e.mp3';\n\nreturn msg;\n","outputs":1,"noerr":0,"x":270,"y":260,"wires":[["89ff2493.12e0f8"]]},{"id":"a5817182.e1ca6","type":"inject","z":"afb06c02.a05f38","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":260,"wires":[["cb6f535e.92c4f8"]]},{"id":"76dca06.032016","type":"inject","z":"afb06c02.a05f38","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":300,"wires":[["e2cd2034.c11378"]]},{"id":"e2cd2034.c11378","type":"function","z":"afb06c02.a05f38","name":"NewPost","func":"\nmsg.payload='play_notification';\nmsg.payload='play_noti';\nmsg.topic='http://192.168.178.32/mp3/an_post.mp3';\n\nreturn msg;\n","outputs":1,"noerr":0,"x":280,"y":300,"wires":[["89ff2493.12e0f8"]]},{"id":"1372ec11.ef8454","type":"sonos-config","z":"","name":"Play5","serialnum":"5C-AA-FD-02-8D-D4:D","ipaddress":"192.168.178.24"}]

Ansonsten sehr gute Nodes, bin begeistert. Wünschenswert wäre höchstens noch die Konfiguration (IP, Serialnumber) über den Input, würde Flows für verschiedene Räume sehr vereinfachen.

Gerne auch Rückfragen...

**Comment by hklages** [comment]
Hi. 

Bei "play_notification" wird ein Webserver als Event Handler gestartet. Das kann zu "unpredictable" Verhalten auf "begrentzten" Systemen führen. Ich nehme an, das ist die Ursache. 

Deshalb habe ich "play_noti" gerade in Arbeit. Dort nehme ich die Build-in timer. Das scheint besser zu laufen. 

Bei mir ist die längste "Notification" 43 Sekunden und läuft reibungslos. 
Kann es sein, dass irgendwas mit deiner "langen" Notification ist? 
Ich habe [hier](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification)
beschrieben, wie ich die mp3 Dateien zur Verfügung stelle - der untere Teil. Man braucht aber auch den Setup (obere Abschnitt der Grafik).  

Zur Konfiguration (IP, Seriennummer): Was meinst du damit? 
Ich überlege gerade, ob ich eine node mit allen Befehlen erstelle, die als Input den Namen des Players aus der Sonos app nutzt. Also zum Beispiel msg.usePlayerWithName=Küche

**Comment by Markus-** [comment]
Evtl. könnte auch Docker das Problem sein. Bist du sicher, dass alles hinsichtlich IGMP / Netzwerk sauber läuft? Ich hatte auch sehr komische Fehler als ich die Weiterleitung über VLAN-Grenzen hinweg nicht korrekt eingestellt hatte.

Bzgl. der IP, Seriennummer: Meiner Meinung nach können die Konfigurationsknoten ruhig bleiben, ein generischer Knoten der sich dann über ein Msg-Feld steuern ließe wäre natürlich hinsichtlich übersichtlichem Code sehr gut.

Gruß
Markus

**Comment by githubwesseln** [comment]
Habe ein paar Test auf meinem alten Raspi 3 mit Node Red als ioBroker-Adapter (also ohne Docker) durchgeführt. Konnte dabei den "alten" Fehler nicht reproduzieren (auch auf dem Wirksystem unter Docker z. Z. nicht aufgetreten), sollten es deshalb dabei belassen.
Aber beim neuen Kommando ist mir folgendes aufgefallen:
MP3-File auf NGINX-Server unter Docker (Raspi 4) keine/richtige Wiedergabe je nach MP3, Sonos-Restauration ok,
MP3-File auf Apache-Server (xampp) unter Window keine/richtige Wiedergabe je nach MP3, Sonos-Restauration ok,
MP3-File auf ioBroker-Server-Adapter (Raspi 3) Wiedergabe ok (Ende etwas abgeschnitten), Sonos-Restauration ok.
Im Fehlerfalle kann man am Anfang manchmal einen sehr kleinen Bruchteil vom Text hören.
Habe die Vermutung das nur MP3 einer bestimmten Länge ohne Fehler laufen.
Wiedergabe und Restauration über das alte Kommando ist immer ok.
Also nicht Docker abhängig, habe keine Erklärung für die Fehler bzw. keine Fehler unter ioBroker.
MP3 wurden mit ioBroker-SayIt-Adapter (Sprache Google-Deutsch) erstellt, die Server laufen alle im gleichen Netzwerk.
Es wurden die gleichen Files (heute neu erstellt) auf allen Systemen verwendet, direkter Aufruf im Browser ist immer ok.
Hoffe dir helfen diese Infos weiter.

Statt Konfiguration (IP, Serialnumber) über den Input ist natürlich eine über Sonos-Name noch besser. Hintergund: aktuell wird im Flow über Switch-Nodes auf die einzelnen Sonos-Nodes verzweigt. Den Flow könnte man mit der Ansprache über die Input-Msg wesentlich einfacher gestallten (ohne Switch-Nodes und nur mit einem Sonos-Adapter pro Kommando-Ebene).

Viele Grüße
Jochen

**Comment by hklages** [comment]
Erstmal Danke für die vielen Test. Wenn play_notification bei dir funktioniert, ist ja alles in Ordnung. 

**Bzgl. der Ergebnisse:** 
Das ist sehr merkwürdig, weil play_noti und play_notification für das Abspielen des mp3 den selben Befehl verwenden. Die einzige Erklärung die ich habe, ist, dass es auf einem anderen player spielt oder die Lautstärke zu leise zum Hören ist. 

Du könntest play_noti versuchen mit 
msg.useCoordinator = true (boolean)
msg.sameVolume = true (boolean)
msg.volume = 70 (number)

**Comment by hklages** [comment]
Bei Version 3.0 habe ich eine neue node "Universal" mit 2 Befehlen für notification: 
play.notification spielt auf der gesamten Gruppe, man kann die Lautstärke für alle "anheben"
joiner.play.notification spielt nur auf einem "joiner", der die Gruppe kurz verläst und dann wieder zurückgeht. 

useCoordinator gibt es nicht mehr, da alle Befehle in Universal auf GROUP gehen. Man kann die Gruppe selektieren mit msg.playerName = 'Küche'. Das macht es vielleicht auch einfacher.

**Comment by DIYtechie** [comment]
I don't speak german, so I don't know if this issue is solvet, but I also get an error when trying to play a notification. This is my test flows (one using control player and another using universal):

`[{"id":"4bb24b3a.7720c4","type":"change","z":"dda43617.5a8188","name":"play.notification","rules":[{"t":"set","p":"payload","pt":"msg","to":"play.notification","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"http://soundbible.com/grab.php?id=1466&type=mp3","tot":"str"},{"t":"set","p":"volume","pt":"msg","to":"25","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":680,"wires":[["8b062925.c26278"]]},{"id":"eabe92f6.11922","type":"inject","z":"dda43617.5a8188","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":620,"wires":[["933eb9ea.0352b8"]]},{"id":"933eb9ea.0352b8","type":"change","z":"dda43617.5a8188","name":"play_notification","rules":[{"t":"set","p":"payload","pt":"msg","to":"play_notification","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"http://soundbible.com/grab.php?id=1466&type=mp3","tot":"str"},{"t":"set","p":"volume","pt":"msg","to":"25","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":620,"wires":[["75c8d9ce.e369a8"]]},{"id":"75c8d9ce.e369a8","type":"sonos-control-player","z":"dda43617.5a8188","confignode":"3fe5fa76.d1cff6","name":"","x":660,"y":620,"wires":[[]]},{"id":"8b062925.c26278","type":"sonos-universal","z":"dda43617.5a8188","confignode":"3fe5fa76.d1cff6","name":"","x":640,"y":680,"wires":[[]]},{"id":"6e621ceb.5dbe84","type":"inject","z":"dda43617.5a8188","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":680,"wires":[["4bb24b3a.7720c4"]]},{"id":"3fe5fa76.d1cff6","type":"sonos-config","z":"","name":"Play 1","serialnum":"","ipaddress":"192.168.3.13"}]`

When trying to play a notification, I get this error:
![Skærmbillede 2020-04-22 kl  10 57 42](https://user-images.githubusercontent.com/20454469/79962333-32262200-8488-11ea-941a-121238086ff4.png)

the mp3-file plays fine on my Google Home mini.

**Comment by hklages** [comment]
What about: http://soundbible.com/mp3/Two%20Tone%20Doorbell-SoundBible.com-1238551671.mp3

The SONOS players seems to have problems to resolve the location.

**Comment by hklages** [comment]
Alternative is: download that specific mp3 file and serve it on your system. 
The file extension should a SONOS supported file type: mp3, ...

A flow is [here.](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification)
You dont need the TTS part - only setup, serving, serialize.

**Comment by DIYtechie** [comment]
> What about: http://soundbible.com/mp3/Two%20Tone%20Doorbell-SoundBible.com-1238551671.mp3
> 
> The SONOS players seems to have problems to resolve the location.

Thank you very much. The speaker now plays the doorbell sound (yay!), but does not save what was already playing? When I try to resume the music that was already playing, it simply plays the doorbell sound again. I thought the notification feature would save the state before interrupting playback?

**Comment by hklages** [comment]
With both nodes (control player, universal) the current music stops, the notification is being played and then the music continues. The universal nodes should work more reliable (i hope). 

Which node did you use? Did you group your player?

**Comment by DIYtechie** [comment]
I only sent one payload with paypload: play_notification, topic: url, volume: 75. Did not group?

I just tried using a universal node instead, and it also plays the notification, but then throws an error instead of resuming:

![Skærmbillede 2020-04-22 kl  12 45 45](https://user-images.githubusercontent.com/20454469/79973064-30b02600-8497-11ea-92a4-760285791165.png)

**Comment by hklages** [comment]
Could you please check either the console for messages or the debug file? 
402 means an invalid argument. I need to know when that occurs.

The console or terminal should look like: 
![debug](https://user-images.githubusercontent.com/17273119/79980682-c651b280-84a3-11ea-9aec-d9c1b920efd2.png)

**Comment by DIYtechie** [comment]
> Could you please check either the console for messages or the debug file?
> 402 means an invalid argument. I need to know when that occurs.
> 
> The console or terminal should look like:
> ![debug](https://user-images.githubusercontent.com/17273119/79980682-c651b280-84a3-11ea-9aec-d9c1b920efd2.png)

Sure. How do I see this in the terminal? Where to find the debug file?

**Comment by hklages** [comment]
On what system is your Node-RED running.

**Comment by DIYtechie** [comment]
Running in the official Node-RED docker on Raspbian. 

Just did some testing and realised that it works when I start the music from the sonos app (which i rarely do), but doesn't work when i start the music from the spotify app (which I usually do).

**Comment by hklages** [comment]
Good hint.  Then we don't need the terminal/debug info. 

When playing a song via Spotify, what is the result of get_songmedia (Get Status node) for that player at that time. Can you please upload it?

Most important are these properties: 
media.CurrentURI
media.CurrentURIMetaData
position.TrackURI

**Comment by DIYtechie** [comment]
Sure:

media.CurrentURI
x-sonos-vli:RINCON_B8E93750C30801400:2,spotify:639da57c84aa9c877cd69787d12e2729

media.CurrentURIMetaData
<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="spotify" parentID="0" restricted="false"><dc:title>Spotify</dc:title><upnp:class>object.item.audioItem.linein</upnp:class><res protocolInfo="x-sonos-vli:*:audio:*">x-sonos-vli:RINCON_B8E93750C30801400:2,spotify:639da57c84aa9c877cd69787d12e2729</res><vli cookie="9" group=""></vli></item></DIDL-Lite>

position.TrackURI
x-sonos-vli:RINCON_B8E93750C30801400:2,spotify:639da57c84aa9c877cd69787d12e2729

**Comment by hklages** [comment]
Please import the following flow and change the player config file to your play1. 

Does that work or do you get the 402 error message.

`[{"id":"2ce4cf27.10fa2","type":"inject","z":"55805384.a4695c","name":"","topic":"x-sonos-vli:RINCON_B8E93750C30801400:2,spotify:639da57c84aa9c877cd69787d12e2729","payload":"activate_avtransport","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":2480,"wires":[["c30a96d1.4a0ca8"]]},{"id":"c30a96d1.4a0ca8","type":"sonos-control-player","z":"55805384.a4695c","confignode":"2113e9bb.c52236","name":"","x":420,"y":2480,"wires":[["ea44540b.6ab018"]]},{"id":"ea44540b.6ab018","type":"debug","z":"55805384.a4695c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":590,"y":2480,"wires":[]},{"id":"2113e9bb.c52236","type":"sonos-config","z":"","name":"variable","serialnum":"B8-E9-37-58-31-C0:A","ipaddress":"192.168.178.38"}]`

**Comment by DIYtechie** [comment]
unfortunately, I get the error message:
![Skærmbillede 2020-04-24 kl  13 05 22](https://user-images.githubusercontent.com/20454469/80206281-515db480-862c-11ea-8596-36c637c6296c.png)

**Comment by hklages** [comment]
It seem that x-sonos-vli can not be "saved" and restored. 
Do you play always the same spotify playlist? 
I assume you "always" use the Spotify app and when arriving at home you switch from smartphone to sonos player. What is your use case? Maybe we find a work around.

**Comment by DIYtechie** [comment]
I always use the Spotify app, but often listen to the same few Spotify radio stations and playlists.

Any ideas for a workaround?

**Comment by DIYtechie** [comment]
Perhaps the playlist could be recognised and then resumed from Sonos itself rather than from the Spotify app? I.e read x-sonos-vli and figure out the playlist name and then start playlist with regular playlist command.

Sonos-plus can start Spotify playlists, right?

As far as I can see, Spotify playlists cannot be added as Sonos playlists in the Sonos app. I think it was possible once, but not anymore.

**Comment by DIYtechie** [comment]
Perhaps the playlist could be recognised and then resumed from Sonos itself rather than from the Spotify app? I.e read x-sonos-vli and figure out the playlist name and then start playlist with regular playlist command?

**Comment by hklages** [comment]
It is possible to add Sonos playlists/album, etc. The easiest way is to use the Sonos app, select you playlist and use "Add to My Sonos". Then you can use My Sonos node, command export.item and Universal node play.export. 

Can you check 2 things. 
1. When playing from Spotify app: Are you able to "see" the Sonos queue in the Sonos App? 
2. When playing from Spotify app: Does switching to flight mode (turn wifi etc off) have an impact? Does Sonos player continue to play the selected music.

**Comment by DIYtechie** [comment]
Sure.

1) No, when I press the queue icon in the top right, I just get this image
![IMG_21E1EF737D9D-1](https://user-images.githubusercontent.com/20454469/81018660-46ddbf00-8e65-11ea-9df2-c577e34f526e.jpeg)

2) Music keeps playing on the Sonos speaker

**Comment by hklages** [comment]
OK. I could not find anything in the internet related to this and will open a topic at node-sonos. Maybe they have an idea. 

What you can try: 
In the SONOS App, tab "My Sonos": there should be a "Recently played" category. Maybe you have to enable it. Does your spotify stream show up there? If yes long press will show a menu with Add xxx to My Sonos.  

What is the output of My Sonos get.items for that item?

**Comment by hklages** [comment]
Here is the link to the[ issue ](https://github.com/bencevans/node-sonos/issues/464)

Could you please resend the media.CurrentURIMetaData from you post 13 days ago? 
The one is not complete or in error.

**Comment by DIYtechie** [comment]
> OK. I could not find anything in the internet related to this and will open a topic at node-sonos. Maybe they have an idea.

It seems this might be a deeper issue: https://www.home-assistant.io/integrations/sonos/#service-sonosrestore (from the Home Assistant integration documentation):
![Skærmbillede 2020-05-05 kl  10 10 16](https://user-images.githubusercontent.com/20454469/81046413-a0bba480-8eb8-11ea-8626-dba88ad15b63.png)
 
Perhaps the only solution for now is a work around, i.e. trying to match the cloud playlist with a sonos playlist?

> What you can try:
> In the SONOS App, tab "My Sonos": there should be a "Recently played" category. Maybe you have to enable it. Does your spotify stream show up there? If yes long press will show a menu with Add xxx to My Sonos.

This was the method I already tried. This only gives me an option to add the songs from the selected playlist to a Sonos or Spotify playlist. 

Strangely, however, if I navigate to the same Spotify playlist via the "browse" tab in the Sonos app, I can add the playlist to "My Sonos". Yes!

----
One thing that should be possible to solve regardless of the cloud queue issue is resuming the correct volume, even if the queue cannot be resumed? This would also be helpfull, since I've set the doorbell volume quite loud.

**Comment by hklages** [comment]
> One thing that should be possible to solve regardless of the cloud queue issue is resuming the correct volume, even if the queue cannot be resumed? This would also be helpfull, since I've set the doorbell volume quite loud.

Do you use Universal node, `play.notification`? There it should already work. 
1. volume is restored
2. content is restored

Anyway I changed the code a bit and now it will ignore the Spotify initiated content, reset the volume and finish the program regularly. You can then start playing your playlist from the My Sonos  wiht export.item+play.export

**Comment by DIYtechie** [comment]
@hklages play.notification works great with streams started from the Sonos and the volume is now also restored correctly when playing from Spotify.

But, what is the correct topic to use with export.item?

![Skærmbillede 2020-05-10 kl  13 01 57](https://user-images.githubusercontent.com/20454469/81497384-71dd6e00-92be-11ea-907d-bab86d4eb8be.png)

**Comment by hklages** [comment]
The topic should be a unique (among all My Sonos title) search string. For instance: "Dust in the Wind". That of course only works if you you had added this song to My Sonos in the SONOS App. 

With get.items you get all My Sonos items and the titles. 

PS: I updated the Wiki - maybe that helps.

**Comment by DIYtechie** [comment]
Oh, I see. So in order to play a playlist with (payload: "export"; topic: name of song or playlist) I should sheck out available titles with (payload: "get.items"; topic: empty)? 

When I send get.items using the test flow from the wiki (with my own speaker of cource), I get this error:
![billede](https://user-images.githubusercontent.com/20454469/81676673-7c2f7180-9450-11ea-958e-c7b3882e64fb.png)

**Comment by hklages** [comment]
that's a bug. One of your Sonos playlist does not have any album Art. 
I fixed it - the AlbumArtURI will now be an empty string!
3.1.3 will be available tomorrow.

**Comment by DIYtechie** [comment]
Awesome, thanks. Is there a way to get the _name_ of the current playlist, when it is started from Spotify, or is that what "get_songmedia" was supposed to show?

**Comment by hklages** [comment]
Hi. I just published 3.1.3 with the fix. Let me know if it works for your.
By the way: You can also lookup the name of any Sonos playlist in the SONOS App, My Sonos tab, playlists. The subitle is Sonos playlist. And you can create one manually in the SONOS app.

name: Right. get_songmedia provides all information the SONOS system can deliver. 

Now in the "Universal node" there is a command `get.trackplus`. It provides the same information as get_songmedia.

**Comment by DIYtechie** [comment]
Hi again :) Did som testing: 
get.items, get.trackplus, export.item and play.export all work 👍 :)

**Comment by hklages** [comment]
Great to hear. Thanks for the feedback. 
I close this issue.
