### ISSUE TITLE
Wiedergabeliste wechseln

### ISSUE THREAD

**Issue by niwre2019** [hklages/node-red-contrib-sonos-plus#36]
Hallo,

ich würde gerne eine bestehende Wiedergabe einer Gruppe stoppen, dann etwas anderes wiedergeben und danach wieder die ursprüngliche Wiedergabe fortsetzen. Kann mir hierbei jemand helfen? Was ich nicht hinbekomme, ist die aktuelle Wiedergabe zwischenzuspeichern und dann wieder an die Gruppe zum fortsetzen zu übergeben. Geht so etwas überhaupt?

Play_Notification ist leider keine Lösung, da die Wiedergabe sich immer wieder ändert.

Gruß
Niwre

**Comment by hklages** [comment]
Hallo. Es gibt mehrere Optionen. 
a) Wenn die "Wiedergabe" eine MP3 Datei ist, die sich immer ändert, könnte man sie auf eine andere Datei mit festen Namen kopieren und diesen dann (immer gleicher Name) verwenden. 
Schau dir diesen [flow](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification) an. 

b) Ein play notification Node ist gerade in Arbeit. Dort könnte ich safe und restore für eine dedizierte Gruppe verfügbar machen. Das könnte auch funktionieren. Das dauert aber ein paar Tage. Bin noch in der Überlegungsphase.

**Comment by niwre2019** [comment]
Hallo,
die zweite Lösung hört sich für mich gut an, dann warte ich mal auf das nächste Update.
Vielen Dank für deine Hilfe.
Gruß 
Niwre

**Comment by hklages** [comment]
3.0.0 ist jetzt "published" und enthält die ersten GROUP Befehle. Damit kann ich jetzt diesen Punkt angehen. 
In 3 Wochen kommt 3.1 und dort ist sowas wie create.snaphot, restore.snapshot.  Imdirekt sind diese beiden Funktion in 3.0.0 schon in player.notification enthalten.

**Comment by niwre2019** [comment]
Super, vielen Dank. Dann kann ich mein Projekt ab Version 3.1 perfekt umsetzen. Werde bis dahin schon einmal mit den bereits vorhandenen Möglichkeiten ein wenig testen.

**Comment by niwre2019** [comment]
Habe die neuen Funktionen play.notification und joiner.play.notification getestet und das funktioniert wirklich super. Vielen Dank für die tolle Umsetzung und den tollen Support, ich freue mich schon auf die Vers 3.1.

**Comment by hklages** [comment]
Hallo. Jetzt ist 3.1 auf npm verfügbar. Es gibt die neuen Funktionen create.snap, play.snap und zum sichern der Queue  save.queue, clear.queue, remove.sonosplaylist. Der Befehle queue in Verbindung mit My Sonos kann zum restoren verwendet werden. 

Die Queue kann man mit save.queue in eine Sonos playlist speichern - zum Beispiel mit dem Namen queueBackup. Alte playlists sollte man vorher löschen (deshalb remove.sonosplaylist). Ansonsten werden unter dem Namen munter Playlists erzeugt. Sehen kann man all in der App, Tab My Sonos oder mit get.items. 

Anschließend kann man mit create.snap die anderen Dinge (playbackstate, .. ) sichern. 

Hier ist ein Beispiel flow: 

![Snap](https://user-images.githubusercontent.com/17273119/80729732-f5ea6580-8b08-11ea-8cf3-61315e3417f1.png)

`[{"id":"491bd16d.1212e","type":"comment","z":"4318847d.0693cc","name":"Example 8: Group snapshot","info":"","x":125,"y":1060,"wires":[]},{"id":"52d1f7c1.e35848","type":"inject","z":"4318847d.0693cc","name":"","topic":"queueBackup","payload":"remove.sonosplaylist","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":1095,"wires":[["d9311d99.f498c"]]},{"id":"95cb2b68.7214d8","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":700,"y":1139,"wires":[["ba48ff29.15c59"]]},{"id":"43d03f0a.512fd","type":"change","z":"4318847d.0693cc","name":"create snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"create.snap","tot":"str"},{"t":"set","p":"snapVolumes","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"snapMutestates","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":680,"y":1099,"wires":[["95cb2b68.7214d8"]]},{"id":"e095c253.fc1b1","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":581,"y":1235,"wires":[["572964f2.c187cc"]]},{"id":"572964f2.c187cc","type":"debug","z":"4318847d.0693cc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":713,"y":1235,"wires":[]},{"id":"ba48ff29.15c59","type":"change","z":"4318847d.0693cc","name":"store in flow, stop","rules":[{"t":"set","p":"recentsnapshot","pt":"flow","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"stop","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":910,"y":1099,"wires":[["da231a54.c69008"]]},{"id":"7163589.a72b2a8","type":"change","z":"4318847d.0693cc","name":"play snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"play.snap","tot":"str"},{"t":"set","p":"snap","pt":"msg","to":"recentsnapshot","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":561,"y":1195,"wires":[["e095c253.fc1b1"]]},{"id":"41c7ac74.a2c854","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":480,"y":1139,"wires":[["43d03f0a.512fd"]]},{"id":"4c5efb45.196ff4","type":"inject","z":"4318847d.0693cc","name":"","topic":"","payload":"clear.queue","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":1195,"wires":[["5cfc7f18.6f27"]]},{"id":"7f910b16.96cf24","type":"sonos-manage-mysonos","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":343,"y":1235,"wires":[["7163589.a72b2a8"]]},{"id":"5cfc7f18.6f27","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":120,"y":1235,"wires":[["1eb0b341.f8addd"]]},{"id":"1eb0b341.f8addd","type":"change","z":"4318847d.0693cc","name":"restore queue","rules":[{"t":"set","p":"payload","pt":"msg","to":"queue","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":1195,"wires":[["7f910b16.96cf24"]]},{"id":"da231a54.c69008","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":920,"y":1139,"wires":[["6324aa0b.dc1234"]]},{"id":"330983f0.916e6c","type":"change","z":"4318847d.0693cc","name":"create snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"save.queue","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":460,"y":1100,"wires":[["41c7ac74.a2c854"]]},{"id":"d9311d99.f498c","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":300,"y":1135,"wires":[["330983f0.916e6c"]]},{"id":"6324aa0b.dc1234","type":"debug","z":"4318847d.0693cc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1110,"y":1139,"wires":[]},{"id":"88e9fa70.4a53e8","type":"sonos-config","z":"","name":"coordinator","serialnum":"5C-AA-FD-00-22-36:1","ipaddress":"192.168.178.37"}]`

**Comment by niwre2019** [comment]
Hallo,
VIELEN DANK. Das ist viel mehr als ich mir erhofft hatte und absolut Spitze umgesetzt. Meine Probleme sind damit gelöst und ich schließe deshalb hier sehr gerne.
Gruß
Niwre2019
