### ISSUE TITLE
Spotify Manage Queue

### ISSUE THREAD

**Issue by Speeedy0815** [hklages/node-red-contrib-sonos-plus#37]
Since last update 2.1.7  (I don't know wich software-version I used before) I can't add Spotify Playlists to Queue.

I use an IKEA symfonisk with newest Software. 

"Manage Queue" does not show an error. But the Anwering of this is every time:  "Kein Antwortobjekt" (german for "no answering object")

"Flush Queue" is working fine. So I think the connection to my  IKEA symfonisk is working.

I tryed also the example of the wiki with "Manage my sonos" and Spotify. There the node is showing an error: "error: queue my sonos item - cannot read property 'length' of undefined."

Could you Check please?

**Comment by hklages** [comment]
Hi. 
It sounds as if there are no items in "My Sonos".  I just send an update 2.1.8. It should provide the message "no items". Can you please verify. 
What is the output of "get_items". Do you see the title of your spotify playlist in that list?

**Comment by Speeedy0815** [comment]
get_items shows the same Error: "error: queue my sonos item - cannot read property 'length' of undefined."

**Comment by Speeedy0815** [comment]
I tryed now: 

Add some songs to sonos with their app and tryed "get_items" . But same behaviour.

**Comment by hklages** [comment]
Can you please verify that you are in the "My Sonos" tab of the app? 
![MySonos in App](https://user-images.githubusercontent.com/17273119/78284216-5d6bc000-751f-11ea-8492-780b1db49bb1.jpg)

**Comment by Speeedy0815** [comment]
Here 2 Screenshots. 

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/59925572/78295522-8fcfea00-752c-11ea-882b-fb3d03caf102.png)

2nd one: 
![image](https://user-images.githubusercontent.com/59925572/78295630-c0178880-752c-11ea-8068-928c98bd5dae.png)

**Comment by hklages** [comment]
:-)  - "Mein Sonos" ist etwas anderes als "Sonos". "Mein Sonos" ist eine Favoritenliste für playlists, Alben, Lieder. etc. So wie es aussieht ist Dein "Mein Sonos" leer - deshalb kommt auch die Fehlermeldung. 

Gehe mal auf "Suchen" Adele, wähle 21 aus und dann auf die 3 vertikalen Punkte oben  und dort füge Album zu "Mein Sonos". 

Dann erscheint es unter Alben in Mein Sonos.

**Comment by Speeedy0815** [comment]
Ok, danke für deine Hilfe. Das funktioniert jetzt und auch get_items bringt einige Einträge, die ich jetzt hinzugefügt habe. Ich glaube aber, dass ich dich jetzt mit meinem Unwissen in die falsche Richtung gelenkt habe.

Mein eigentliches Ziel war mit Manage Queue eine Playlist (nicht Favorit) aus Spotify hinzuzufügen. Das funktioniert nicht mehr. Hier ein Screenshot:

![image](https://user-images.githubusercontent.com/59925572/78326062-b23c2480-7579-11ea-877f-65c1fd9d5ed8.png)

**Comment by hklages** [comment]
insert_spotify_uri muss ich mir ansehen. Da scheint Spotify etwas geändert zu haben. 

Meiner Ansicht nach der einfachste Weg ist:

1. SONOS APP: Gehe in die SONOS App, dann Durchsuchen oder Suchen Tab, dann den Titel deiner Spotify Playlist eingeben und mit "Hinzufügen zu Mein Sonos"  zu "Mein Sonos" hinzufügen. 

2. NODE RED: Du kannst dann mit der Node "My Sonos", payload "queue" und topic den Titel deine Playlist einfügen. Das geht für Spotify playlists, einzelne Lieder, Alben, ... und ist somit ein universeller Weg.

**Comment by Speeedy0815** [comment]
Hi, ich habe jetzt alle meine wichtigen Playlists umgebaut. Damit ist das ersteinmal eine Umgehung mit der ich leben kann. Danke. Es wäre aber trotzdem schön, wenn du es dir bei Gelegenheit ansehen könntest.

**Comment by hklages** [comment]
Hi. Ich packe es auf die ToDo list. Der sicherste Weg ist immer über My Sonos - dann ist SONOS in der Pflicht Änderungen bei Spotify einzubauen. Mit insert_spotify_uri muss ich es anpassen und das ist sehr fisselig.  

In 2.1.9 sollte jetzt auch die Fehlermeldung kommen "no items found". 
Das ist auch leider nur schwer zu testen, weil ich für den Test immer "Mein Sonos" löschen müsste. 

Ich schließe den issue somit.

**Comment by hklages** [comment]
Noch einen Hinweis. Bei spotify uri muss man die folgende Syntax genau einhalten: 
Also spotify:user:spotify:playlist:  Wie sah dein topic aus? 

spotify:user:spotify:playlist:37i9dQZEVXbMDoHDwVN2tF

**Comment by Speeedy0815** [comment]
Ehrlich gesagt, durch den Umbau habe ich es jetzt schon weg geschmissen. Aber so ungefähr wie bei dir sah die URI aus. Bis vor 3/4 Tagen ging es ja auch noch. Ich hatte die Uri es aus der Spotifyapp kopiert.

**Comment by hklages** [comment]
This package is based on node-sonos. There is an open issue addressing your spotify problem. So it will be solved in one of the next release of node-sonos and then automatically in in node-red-contrib-sonos-plus. 
[open issue ad node-sonos](https://github.com/bencevans/node-sonos/issues/457)
