### ISSUE TITLE
set EQ - Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by phralh** [hklages/node-red-contrib-sonos-plus#38]
Hi, 

In my unchanged flow, setting Nightmode och DialogLevel on my Sonos Beam has stopped working and is giving me this error:

set EQ - Cannot read property 'includes' of undefined :: Details: {"stack":"TypeError: Cannot read property 'includes' of undefined\n    at sonosPlayer.deviceDescription.then (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-control-player.js:908:29)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","message":"Cannot read property 'includes' of undefined"}

The input is {"_msgid":"42c86f33.8f036","topic":"NightMode","payload":"set_eq","eqvalue":"On"} This worked fine before, but I'm not sure when it stopped working.

Get status for NightMode and DialogLevel still works.

Regards
Fredrik

**Comment by hklages** [comment]
oh - sorry. Right now I am modifying a lot to improve the error messages. Unfortunately, sometimes thing goes wrong.  I will fix latest tomorrow - maybe today.

**Comment by hklages** [comment]
Hi. 

Hava a look at 2.1.9 
That should fix the bug .
