### ISSUE TITLE
Nothing works after upgrading to 3.0.1?

### ISSUE THREAD

**Issue by DIYtechie** [hklages/node-red-contrib-sonos-plus#41]
This simple toggle flow worked before upgrading to 3.0.1:

`[{"id":"1b7b193.1c86be7","type":"sonos-control-player","z":"c5ae02e1.ce9bb","confignode":"75950d78.804364","name":"","x":700,"y":780,"wires":[[]]},{"id":"858249ad.58e508","type":"inject","z":"c5ae02e1.ce9bb","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":320,"y":780,"wires":[["525ae267.9fd96c"]]},{"id":"525ae267.9fd96c","type":"change","z":"c5ae02e1.ce9bb","name":"toggleplayback","rules":[{"t":"set","p":"payload","pt":"msg","to":"toggleplayback","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":500,"y":780,"wires":[["1b7b193.1c86be7"]]},{"id":"75950d78.804364","type":"sonos-config","z":"","name":"Play 1","ipaddress":"192.168.3.13"}]`

Now I get this error:

> TypeError: Cannot read property 'split' of undefined

**Comment by hklages** [comment]
Hi. Strange. I tested the flow on my Dev System and a test system. It works for all of my players. 
Even a Play:1. 
Do you have access to the debug file? Could you send it. 

You can also try this flow (changing the config node to your play1)
`[{"id":"ed8a328b.dcd","type":"inject","z":"931fad95.92398","name":"","topic":"","payload":"toggle.playback","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":1160,"wires":[["fa2550f6.27e52"]]},{"id":"fa2550f6.27e52","type":"sonos-universal","z":"931fad95.92398","confignode":"69dd92.b985227","name":"","x":320,"y":1160,"wires":[[]]},{"id":"69dd92.b985227","type":"sonos-config","z":"","name":"bad","serialnum":"00-0E-58-FE-3A-EA:5","ipaddress":"192.168.178.35"}]`

**Comment by hklages** [comment]
Can you please check: In your config node: Did you ONLY enter the ip address or did you also picked up the serial number. Try picking up the serial number.

**Comment by DIYtechie** [comment]
Thank you for your swift reply. much appreciated :)

Very strange indeed. Tried your subflow with the universal node and it works!

Then tried autodiscovering the serial number as requested:
![Skærmbillede 2020-04-22 kl  10 22 52](https://user-images.githubusercontent.com/20454469/79958492-44ea2800-8483-11ea-9989-5c01971ded50.png)

and received this message:

![Skærmbillede 2020-04-22 kl  10 26 32](https://user-images.githubusercontent.com/20454469/79958906-bf1aac80-8483-11ea-855d-a24bbece8037.png)

The strangest part is that the flow I posted initially still doesn't work, but if I create a new one, which seem to be identical, it works.

This still doesn't work:
`[{"id":"858249ad.58e508","type":"inject","z":"c5ae02e1.ce9bb","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":980,"y":180,"wires":[["525ae267.9fd96c"]]},{"id":"525ae267.9fd96c","type":"change","z":"c5ae02e1.ce9bb","name":"toggleplayback","rules":[{"t":"set","p":"payload","pt":"msg","to":"toggleplayback","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1160,"y":180,"wires":[["1b7b193.1c86be7"]]},{"id":"1b7b193.1c86be7","type":"sonos-control-player","z":"c5ae02e1.ce9bb","confignode":"75950d78.804364","name":"","x":1360,"y":180,"wires":[[]]},{"id":"75950d78.804364","type":"sonos-config","z":"","name":"Play 1","ipaddress":"192.168.3.13"}]`

whereas this now works:
`[{"id":"99bdd141.d177","type":"sonos-control-player","z":"c5ae02e1.ce9bb","confignode":"3fe5fa76.d1cff6","name":"","x":760,"y":180,"wires":[[]]},{"id":"d5318061.d23ff","type":"change","z":"c5ae02e1.ce9bb","name":"toggleplayback","rules":[{"t":"set","p":"payload","pt":"msg","to":"toggleplayback","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":580,"y":180,"wires":[["99bdd141.d177"]]},{"id":"5f71c0b9.f40c1","type":"inject","z":"c5ae02e1.ce9bb","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":380,"y":180,"wires":[["d5318061.d23ff"]]},{"id":"3fe5fa76.d1cff6","type":"sonos-config","z":"","name":"Play 1","serialnum":"","ipaddress":"192.168.3.13"}]`

Why is this?

**Comment by DIYtechie** [comment]
Aha. Now I see. One uses a different config node.
![Skærmbillede 2020-04-22 kl  10 47 10](https://user-images.githubusercontent.com/20454469/79961167-9d6ef480-8486-11ea-8ca8-6607bb053432.png)

I can't tell them apart as both use same ip adress and the serial number is not visible in either, but one works and one doesn't. Still strange, but I am satisfied with deleting the config that doesn't work.

**Comment by hklages** [comment]
Hi. Thanks - the two configurations are almost identical - but with a small difference. 
serialnumber is missing in one, and that causes the exception. In the other configuration it is an empty string "". 

I extract the mac address from the serial number using the split function. That causes the error message. Its a but and has to be fixed.

**Comment by hklages** [comment]
3.0.2 fixes that issue.
