### ISSUE TITLE
"My Sonos" "get.items" empty

### ISSUE THREAD

**Issue by MeanderingCode** [hklages/node-red-contrib-sonos-plus#44]
Several nodes function, including "Get Status" `get_basics`, "Universal" `play`, and "Manage Queue" `get_queue`, but I receive an empty array using "My Sonos" `get.items`, and attempting "Manage Queue" `insert_spotify_uri` with a playlist in my My Sonos collection results in `statusCode 500 & upnpError 800` (possibly related to not being able to enumerate My Sonos items).

I am new to Node Red and do not yet know how to output more error information (my "catch" node isn't triggering and I haven't looked up how to increase log verbosity). I can update this issue with more information as I find time to troubleshoot, but I wanted to start it in case there's something simple I am missing.

**Comment by hklages** [comment]
Hi. Have a look at this [wiki](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A.-Overview). There you find some example. 

Have you "grouped" some player? 
upnpError 800 often means that you try to send a command to a "non-coordinator" in a group. 
That should not occur with the "universal node". 

Lets start with My Sonos get.items.  Are you familiar with "My Sonos"? 
 A short description can be found [here](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/C.-SONOS-Concept
)
Please have a look at the SONOS App (Android or Iphone), tab "My Sonos". Are there any items?

**Comment by MeanderingCode** [comment]
I have read those and played with some of it. Further testing has some progress, and some things that I am stuck on or are bugs:
* One Spotify playlist in "My Sonos" (added via Sonos Android weeks ago):
  * `My Sonos` node `get.items` returns empty
* Added a "native" playlist (empty) to "My Sonos" in Sonos Android:
  * `My Sonos` node `get.items` returns empty
* Added a playlist from Plex and a track from Plex to the "My Sonos" native playlist:
  * `My Sonos` node `get.items` returns Spotify and Plex playlists, but not the Sonos playlist

Also:
* `Universal` `play` works
* `My Sonos` `queue` with the "name" of the Spotify playlist works
* `Universal` `play.export` works with the Spotify playlist retrieved via `My Sonos` `export.item` (`topic: <plalistName>`)
* `Manage Queue` `play_song` with an index works
* `Manage Queue` `insert_spotify_uri` **continues to error**

The Sonos were not grouped. A `Control Player` `leave_group` succeeds, but does not change the behavior or `Manage Queue` `insert_spotify_uri`. I always get the following error, whether using a track or playlist Spotify URI:

```
statusCode 500 & upnpError 800 :: Details: Lookup upnpError 800
```

As the strange `get.items` behavior has changed, I suspect it is a Sonos API-side issue and not relevant to this project. Given that, I think this ticket can be closed.

I am still hoping to get `insert_spotify_uri` to work. I didn't find information that seemed the same as my issue, but I will keep looking. If you know of a ticket in this or another project, or better yet a solution, I would appreciate being pointed in that direction.

I'd also love it if playing Spotify on my Sonos through the API caused my native Spotify players to pick up the state and stay in sync, but that's another Sonos/Spotify problem not related to third party projects.

**Comment by MeanderingCode** [comment]
Another update:
* `Manage Queue` `get_sonos_playlists` returns the one "native" Sonos playlist, even though `My Sonos` `get.items` does not.
* Adding a `region: 3079` (US) property to `insert_spotify_uri` command stops the `Manage Queue` node from producing an error, but it does ever return, either.

**Comment by hklages** [comment]
You are right - Sonos playlists are still not supported in "My Sonos". You already described the work around. I opened the new issue #45 for that topic and hope to solve it in a 2-3 weeks.

What is still open? The insert_spotify_uri? Anything else? Please open a new topic for that because no one will expect that under this issue/topic. Please add an example or flow. 

More details: 
You get more information in the console/terminal of node-RED. In case of a Docker container: Go to Details, Terminal. In some implementations you have to edit the settings.js file and enable debugging. 
![docker](https://user-images.githubusercontent.com/17273119/80476822-37351680-894b-11ea-8a93-b870aa223ad1.png)

**Comment by hklages** [comment]
I close this topic following your comment "Given that, I think this ticket can be closed."
