### ISSUE TITLE
Support for playNotifications command

### ISSUE THREAD

**Issue by carstenlenz** [hklages/node-red-contrib-sonos-plus#5]
Hello,
great Work. It was really easy to get started with node-red and Sonos :)

I want to use the sonos module for playing notifications and the Node Sonos lib has a [command](https://github.com/bencevans/node-sonos/blob/master/docs/sonos.md#sonossonosplaynotificationoptions) for this.

Would it be possible to support that ?
Cheers 
Carsten

**Comment by tsprivate** [comment]
There is currently a good playNotification with the [SonosPollyTTS](https://flows.nodered.org/node/node-red-contrib-sonospollytts) node ... this feature is on the long-term roadmap of this node (or a merger)

**Comment by carstenlenz** [comment]
Thanks for your feedback. 

I haven't  tried SonosPollyTTS yet. Looking at it it provides a very specialized experience. 

So having the playNotifications command as a basic block in this lib still makes sense. Good to hear it's on the (although long-term) roadmap :)

**Comment by hklages** [comment]
In a first step I added to the "Control Player" node the command "lab_play_notification".  You can test it. The notification song has to be sent via topic, for instance: 
https://www.zapsplat.com/wp-content/uploads/2015/sound-effects-the-sound-pack-tree/tspt_pull_bell_02_065.mp3?_=1

Please watch the processes on your system. The recommendation from the nodes-sonos API is to exit the process (process.exit()) . But doing that crashes nodeRED on my Raspberry Pi. So I removed that line of code.  So it might be that Zombi process are created.

Any feedback is highly welcome.

**Comment by carstenlenz** [comment]
Thanks - I will give it try this weekend :)

**Comment by hklages** [comment]
Hi, it is now in 0.4.4 as play_notfication (control player node).
I close this topic now.

**Comment by carstenlenz** [comment]
Thank you! :) Worked pretty well but I immediately updated to 0.4.4 because being able to set the volume is really the only thing I could bring up :)
