### ISSUE TITLE
TTS Notification and restore Queue

### ISSUE THREAD

**Issue by sfbay712** [hklages/node-red-contrib-sonos-plus#50]
Hi,
great work on the flow!
When making a TTS announcement, is it possible to pause, save the current queue, start the announcement with pollyTTS, and go back to the previous queue? I figured out how to restore the volume, but not the queue.

Thx!

**Comment by hklages** [comment]
Hi. Thanks :-)

There are 2 new commands in "Universal" node:` save.queue, remove.sonosplaylist. `
`save.queue`: saves the queue to a sonos playlist. 
The playlist shows up in My Sonos under Playlists.
You can remove that playlist with remove.sonosplaylist.

You can export that playlist with "My Sonos" node, command `export` or queue and play it with "Universal" node `play.export` or` play.queue.` 

![Snap](https://user-images.githubusercontent.com/17273119/80730379-cf78fa00-8b09-11ea-9460-958b63f01661.png)

Here is a flow:  `{"id":"491bd16d.1212e","type":"comment","z":"4318847d.0693cc","name":"Example 8: Group snapshot","info":"","x":125,"y":1060,"wires":[]},{"id":"52d1f7c1.e35848","type":"inject","z":"4318847d.0693cc","name":"","topic":"queueBackup","payload":"remove.sonosplaylist","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":1095,"wires":[["d9311d99.f498c"]]},{"id":"95cb2b68.7214d8","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":700,"y":1139,"wires":[["ba48ff29.15c59"]]},{"id":"43d03f0a.512fd","type":"change","z":"4318847d.0693cc","name":"create snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"create.snap","tot":"str"},{"t":"set","p":"snapVolumes","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"snapMutestates","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":680,"y":1099,"wires":[["95cb2b68.7214d8"]]},{"id":"e095c253.fc1b1","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":581,"y":1235,"wires":[["572964f2.c187cc"]]},{"id":"572964f2.c187cc","type":"debug","z":"4318847d.0693cc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":713,"y":1235,"wires":[]},{"id":"ba48ff29.15c59","type":"change","z":"4318847d.0693cc","name":"store in flow, stop","rules":[{"t":"set","p":"recentsnapshot","pt":"flow","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"stop","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":910,"y":1099,"wires":[["da231a54.c69008"]]},{"id":"7163589.a72b2a8","type":"change","z":"4318847d.0693cc","name":"play snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"play.snap","tot":"str"},{"t":"set","p":"snap","pt":"msg","to":"recentsnapshot","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":561,"y":1195,"wires":[["e095c253.fc1b1"]]},{"id":"41c7ac74.a2c854","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":480,"y":1139,"wires":[["43d03f0a.512fd"]]},{"id":"4c5efb45.196ff4","type":"inject","z":"4318847d.0693cc","name":"","topic":"","payload":"clear.queue","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":1195,"wires":[["5cfc7f18.6f27"]]},{"id":"7f910b16.96cf24","type":"sonos-manage-mysonos","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":343,"y":1235,"wires":[["7163589.a72b2a8"]]},{"id":"5cfc7f18.6f27","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":120,"y":1235,"wires":[["1eb0b341.f8addd"]]},{"id":"1eb0b341.f8addd","type":"change","z":"4318847d.0693cc","name":"restore queue","rules":[{"t":"set","p":"payload","pt":"msg","to":"queue","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":1195,"wires":[["7f910b16.96cf24"]]},{"id":"da231a54.c69008","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":920,"y":1139,"wires":[["6324aa0b.dc1234"]]},{"id":"330983f0.916e6c","type":"change","z":"4318847d.0693cc","name":"backup queue","rules":[{"t":"set","p":"payload","pt":"msg","to":"save.queue","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":460,"y":1100,"wires":[["41c7ac74.a2c854"]]},{"id":"d9311d99.f498c","type":"sonos-universal","z":"4318847d.0693cc","confignode":"88e9fa70.4a53e8","name":"","x":300,"y":1135,"wires":[["330983f0.916e6c"]]},{"id":"6324aa0b.dc1234","type":"debug","z":"4318847d.0693cc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1110,"y":1139,"wires":[]},{"id":"88e9fa70.4a53e8","type":"sonos-config","z":"","name":"coordinator","serialnum":"5C-AA-FD-00-22-36:1","ipaddress":"192.168.178.37"}]`

**Comment by hklages** [comment]
You can also use this: 
[TTS with pollly](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification)

**Comment by hklages** [comment]
Closed as no feedback received, times out.
