### ISSUE TITLE
URL is not defined  ERROR

### ISSUE THREAD

**Issue by Wayfinder624** [hklages/node-red-contrib-sonos-plus#51]
I'm missing some configuration. Getting the following error using your universal node example. I did configure it for my Sonos.

processing msg: URL is not defined :: Details: {"stack":"ReferenceError: URL is not defined\n    at getGroupMemberDataV2 (/data/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:530:11)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)","message":"URL is not defined"}

**Comment by hklages** [comment]
Hi. Please send the flow. That seems to be a bug.

**Comment by thomasklingbeil** [comment]
Same issue for me: Here's my flow:

```
[
    {
        "id": "ad0a331a.faa22",
        "type": "sonos-manage-mysonos",
        "z": "2e6aaf82.726b98",
        "confignode": "8751791c.cce128",
        "name": "",
        "x": 351.5,
        "y": 499,
        "wires": [
            [
                "b7203434.1eafa"
            ]
        ]
    },
    {
        "id": "aa6455c8.53b7e8",
        "type": "inject",
        "z": "2e6aaf82.726b98",
        "name": "",
        "topic": "Folge 11: Hunde im Schnee",
        "payload": "export.item",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 136.5,
        "y": 501,
        "wires": [
            [
                "ad0a331a.faa22"
            ]
        ]
    },
    {
        "id": "5b69ad2a.b91c2c",
        "type": "debug",
        "z": "2e6aaf82.726b98",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 715.5,
        "y": 498,
        "wires": []
    },
    {
        "id": "b7203434.1eafa",
        "type": "sonos-universal",
        "z": "2e6aaf82.726b98",
        "confignode": "8751791c.cce128",
        "name": "",
        "x": 542.5,
        "y": 499,
        "wires": [
            [
                "5b69ad2a.b91c2c"
            ]
        ]
    },
    {
        "id": "8751791c.cce128",
        "type": "sonos-config",
        "z": "",
        "name": "MySonos",
        "serialnum": "",
        "ipaddress": "192.168.000.000"
    }
]
```

When debugging the flow there's reasonable data coming out of the My Sonos node.

**Comment by hklages** [comment]
@thomasklingbeil : the ip address 192.168.000.000 looks strange. Please verify.

**Comment by thomasklingbeil** [comment]
I redacted the actual information from the copied flow. Connection to my Sonos works properly for other nodes.

**Comment by hklages** [comment]
Please try to edit the confignode. Right to the serial field there is a search button. Pushing that searches your network for valid Sonos players. You can then choose it from the list.

**Comment by thomasklingbeil** [comment]
But the connection to my Sonos works. I have manually changed the IP to the value above before posting it here.

I can also retrieve the info what is currently playing, search for media etc. 

The thing that does not work is the play command.

**Comment by hklages** [comment]
OK. Now I understand. Please make a short notice in case you "redact" any data.

I imported your flow, changed the confignode (my Sonos player) and replaced the search string. 
The flow then works fine at my test system. So it is not the flow logic. 

1. Go to that flow and use Node-RED menue, Restart Flows. 
Is there any error message as node status for the universal node in that flow? Eg. invalid ip address, ...

2. Please send a "get.state" to the above "Universal node" and let me know the output. In case you dont want to publish it her: send it to my email address  "nrcsplus@gmail.com".  
email can be in English oder Deutsch. 

3. How many player are in your network?

**Comment by hklages** [comment]
..... if `get.state` does not work: Use `get_groups` and send it to "Get Status" node with the same config node.

**Comment by thomasklingbeil** [comment]
I have just realized, I executed the stuff on my v8 node-red (needed for compatibility for other flows). I'll try it out with a more recent version and let you know.

With v8, when querying the state: Exactly the same error:
```
"processing msg: URL is not defined :: Details: {"stack":"ReferenceError: URL is not defined\n at getGroupMemberDataV2 (/data/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:530:11)\n at <anonymous>\n at process._tickCallback (internal/process/next_tick.js:189:7)","message":"URL is not defined"}"
```

The problem seems to come from here https://github.com/hklages/node-red-contrib-sonos-plus/blob/ee791c87952c7785f265be936adc11b51505dfb0/src/Sonos-Commands.js#L527.

If I understand the error correctly, the URL object ist not available: https://nodejs.org/api/url.html But that would make sense for an older node version...

**Comment by thomasklingbeil** [comment]
Big surprise (or not...): When using a current version of node-red (with a current version of Node.js beneath it), it works...

**Comment by hklages** [comment]
I like these kind of surprises :-) 

@Wayfinder624 : Could you please check your installation. It seems that your nodeJS /Node-RED version may be outdated.

**Comment by bdormael** [comment]
I have exact the same issue and same error message.
I've updated my Node-Red already to 1.0.6 and nodejs to 8.17

The universal flow is never working, the other ones (like CTRL Player & Mng Queue) is working fine.

**Comment by hklages** [comment]
Please update  nodeJS to V10 or V12. V8 is from 2017. 
[NodeJS](https://nodejs.org/en/). They recommend 12.16 LTS.

**Comment by Wayfinder624** [comment]
Thanks! Upgraded from 8.16.1 to 12.16.3 and it is now working.

**Comment by bdormael** [comment]
> Please update nodeJS to V10 or V12. V8 is from 2017.
> [NodeJS](https://nodejs.org/en/). They recommend 12.16 LTS.

Updated from 8.17 to 12.16.3 and alls is working now, thx

**Comment by hklages** [comment]
Thanks all for your feedback. I will keep that issue open for a month as it seems that many have this issue.
