### ISSUE TITLE
Discussion topic / payload usage in this node. 

### ISSUE THREAD

**Issue by hklages** [hklages/node-red-contrib-sonos-plus#54]
What is the best way to us topic/payload. Currently payload is used for command and topic for some paramenter if needed. 

Any ideas to improve?

**Comment by tsprivate** [comment]
Hi,

all the standard nodes are using PAYLOAD as the activity to execute (ON,OFF,PLAY,PAUSE) and the topic is used for the task (SetVolume, SetStation, etc). 

This would apply for INPUT and OUTPUT of your nodes.


Using the standard method would enable the normal use of other components

**_Example: Slide-Node to adjust Volume_**
- the output payload will be dynamic based on slider setting
- Topic will always be "Volume"
![image](https://user-images.githubusercontent.com/41630517/81353521-a4476980-910c-11ea-9ed3-cfc5e421babf.png)

**_Example: Dropdown selection_**
- the output payload will provide the StationID
- the topic will always be "play.tunein"
![image](https://user-images.githubusercontent.com/41630517/81353804-67c83d80-910d-11ea-941d-fa0a6e889d1d.png)

**_Example:  Simple Switch-Node_**
- output ON/OFF based on switch-state
- topic "set.mutestate"
![image](https://user-images.githubusercontent.com/41630517/81354161-3c921e00-910e-11ea-9a6d-f52df612b033.png)

**Comment by remygiraud** [comment]
First of all, thanks for the great set of nodes :)
I think that in the "new" Universal node, the use of payload and topic is consistent with the general approach in NodeRed. If I can suggest an improvement, why not having msg.payload and msg.topic settable within the Universal node? At the moment, you have to have (eg) a change node to do this. For "simple" tasks being able to put the payload and the topic as part of the node would avoir some cluttering of the flows.

**Comment by hklages** [comment]
Thanks all for you feedback. I leave that open for further discussion.

**Comment by hklages** [comment]
I am working on the following and just finished for Universal and will do it now for My Sonos node: 

- msg.cmd will be the new property for all commands
- payload will be the new property for on/off, uris, volumes, ....
- there will be a drop down menu to select the command e.g. group.play,... This will override msg.cmd
- the drop down menu will also allow "use incoming message" 

msg.topic is free for future use (maybe a combination of player + cmd)

There is an option to still use the old style (command in msg.payload, state in msg.topic´)

**Comment by hklages** [comment]
You can now set the state (in payload) and command (in topic) or in compatibility mode vice versa. 
Dropdown selection is now possible. 
I intend to provide other properties (e. g. playerName) but that will take a bit. Right now there are a lot of changes already and more could be to confusing/ anoying.
I close this topic.
