### ISSUE TITLE
Request:   "msg.playerName" to nominate target Sonos-Device in Universal-Node

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#55]
Hi,

I'm using your Sonos-Nodes for all my audio messages and notifications via Sonos devices. As I want to address all my Sonos-devices individually I need an "IF" statement to select the correct Universal-Node.

Would it be possible to provide "msg.playerName" to the Universal-Node (and maybe all the others) to select the correct Sonos device?
![image](https://user-images.githubusercontent.com/41630517/81352718-8bd64f80-910a-11ea-8a32-8c1361a0c3e3.png)

Thanks for considering

**Comment by hklages** [comment]
I guess it is already implemented. Delete 2 of the three nodes and use msg.playerName with Study, Kitchen, Bedroom.  But be aware: playerName is the Sonos player name in the Sonos app - not your config node.

**Comment by tsprivate** [comment]
I have tried the msg.playerName and it works like a charm !

Is there a way to read the list of all sonos-names as defined in the Sonos-App ?

**Comment by hklages** [comment]
Good to hear :-) 

"all sonos-names": That is in work for "Universal node" and will provide an array of all groups with all members: Sonos player name, ip, port, baseUrl - similiar to get.state payload.members for a group.
 
Its due end of next week.  Name maybe household.get.groups or household.get.topology or houshehold.get.properties :-).

**Comment by tsprivate** [comment]
sounds great.. looking forward to it.

P.S: Wenn ich mal wieder in Muenchen bin muessen wirr uns aufn Bier treffen ;)

**Comment by hklages** [comment]
PS: gern. Am besten ein paar Tage vorher melden (email nrcsplus@gmail.com ) Es beginnt ja langsam die Biergartenzeit.

**Comment by hklages** [comment]
Hi. 3.1.3 is published and you should now be able to get all player names, grouped by group. 
Universal node: `household.get.groups`
You can use JSONATE to further process. 

I close this issue as the original topic (msg.playerName is already working) and household should work.
