### ISSUE TITLE
Request: List of commands per Node

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#56]
Hi,

great work with your node and all the quick support/response you provide.

I'm a bit loosing track of all the different commands per node. Would it be possible to put a table in your WIKI with all the commands and parameters per node?

E.G:
![image](https://user-images.githubusercontent.com/41630517/81461139-12635d80-91ed-11ea-8ac1-db90a37a82ed.png)

**Comment by hklages** [comment]
That will get easier with every release and at the end 3 nodes will be left (Universal, My Sonos, Musiclibrary): 
- now "Manage Radio" is depeciated -> all function moved to "Universal"
- next week "Control player" and "Get status" will be depreciated -> all function moved to "Universal"

"Manage Queue" will be renamed to "Music library" and focus on command to handle the Music Library. 
"My Sonos" will still be available and get more search/browse capabilities. 

My Sonos and Music Library are special as they are system wide. It might be that I merge them later under Universal and prefix `household.`

Regarding your request for "station Art ": Have look at issue #21 

> Radio id example: s57109
logo exampel: http://cdn-profiles.tunein.com/s57109/images/logoq.png

Unfortunately there are several pattern for different stations:
http://cdn-profiles.tunein.com/s42824/images/logoq.png?t=151377
http://cdn-profiles.tunein.com/s25005/images/logoq.jpg?t=1
http://cdn-radiotime-logos.tunein.com/s260120q.png

**Comment by tsprivate** [comment]
Yes, the 3 Node concept is a good approach .. lesser is better ;) .. yes .. merging them later into Universal would be great.

Still the list of commands with description would be a nice to have

**Comment by hklages** [comment]
OK. So we leave that open.

I just moved from switch / case to a decision table und I try to implement a better "check msg property" function. The base for that is a list of commands and their properties plus attributes (optional, requried).

**Comment by hklages** [comment]
I am preparing this sheet for version 4.0.0 - its almost finished. 
![Command List](https://user-images.githubusercontent.com/17273119/83623588-cf00d280-a591-11ea-8f8a-70ae06c14324.png)

**Comment by hklages** [comment]
Hi. Its not possible to attach a file to issues or the Wiki. 
You may send an email to nrcsplus@gmail.com and I will send it via email.

**Comment by hklages** [comment]
It's now under example.
