### ISSUE TITLE
Request:  Event-Node

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#57]
Hi,

as discussed in the other thread I have checked [Sonos-Notify](node-red-contrib-sonos-notify) to get notified on state changes of my Sonos devices.

Unfortunately the Sonos-Notify informs only on track changes and does not provide information on volume,play-state, progress, or album. At this  time I use it as a trigger only and request the state update via Universal-Node.

Would it be possible (I don't know if the Sonos core node does support) to have an Event node notification on
- Play state changes (Play, Pause,Stop)
- Volume change 
- MuteState change
- Playing progress (nice to have but not important)
- Line-In change

The simplest solution would be an event-trigger with the payload of the Event-Name... than we can use the Universal-Node to get the state information required.

thanks for considering

**Comment by hklages** [comment]
Hi. Thats a good solution. 
I suggest that you contact the owner of that package to add these features. 
Right now I can not add the functionality to node-red-contrib-sonos-plus because I failed to implement it in a way not crashing my production system ccu3. So dont expect anything here in the next months.

**Comment by hklages** [comment]
it is now available: [sonos-events](https://www.npmjs.com/package/node-red-contrib-sonos-events)

> Playing progress (nice to have but not important)
Sonos did following the UPNP org recommendation NOT to implement that as event instead led the user poll the status. That is available in node-red-contrib-sonos-plus  - group.get.trackplus.
