### ISSUE TITLE
play.notification & volume

### ISSUE THREAD

**Issue by bdormael** [hklages/node-red-contrib-sonos-plus#59]
- I'm using play.notification to play a local mp3 file (a 5 second file to warn if a door is still open) which I access via http (via a local webserver) 
- Together with the msg.payload I send a msg.volume of 60
- My player which is then playing has an initial volume of 10

When sending the request, the volume goes to 60, plays the file and goes back to 10, so far so good

The issue:
The file which I'm playing is already playing before the volume is set correctly to 60 so I can't hear the first 2 seconds (because it plays at volume 10)

Is there a way to wait until the volume has been set before the file starts playing ?

**Comment by hklages** [comment]
Hi. The program changes the volume then plays the notification. 
It seems that Sonos player does "execute" the change fast enough. 
What I can to is implement a msg.delayBefore (milliseconds). This will put a delay after the change of volume and before playing the notification. Default if property is missing would be 0.
Your view?

**Comment by bdormael** [comment]
Hi,

Thx for the swift answer.
A delay before the sound is played would be perfect, this would solve my issue.

As a worst case scenario I was going to modify my sound files to add silence of 2 seconds in front of it, with your delay solution I don’t need to do this :-)

Kind regards,

Benny

**Comment by hklages** [comment]
Hi Benny. 
I just published 3.1.4. The order in `play.notification` is now changed. 
Let know whether it now works for you.

**Comment by bdormael** [comment]
Hi,

I’ve tested it and it seems to work ok now.
I’m gonna test more extensive this weekend but I need to modify a lot for this in my NodeRed. Is it ok to keep the ticket open till after the weekend ?

Thx again for your support,

Benny

**Comment by hklages** [comment]
Sure. Even longer.

**Comment by bdormael** [comment]
Hi,

I was able to test it thoroughly and the issue that I had is totally gone now, the volume is immediately at the correct level, thx for that.

During testing I’ve found another issue but I’m not sure you can do something about it:
- I have multiple sensors at home which detects doors open, movements etc. while I’m away or when I enter my home before the alarm has been turned off.
- This is all done via NodeRed (connected to OpenHab, zwave)
- So when I enter my kitchen, it detects that I open the door and it detects movement, therefore it sends 2 notifications to my Sonos which is in my kitchen to warn me.
- These are 2 different NodeRed flows (if/then condition) (every sensor has it’s own flow)
- The problem now is that the notifications overwrite eachother, so the first notification starts, and a second later the other notification overrules the first notification.

If I add them in sequence in NodeRed, it perfectly waits until the first one is finished, but in my case I cannot predict which sensor is going to be alarmed first (I have about 50), so cannot add them in sequence.

Is there a possibility when a notification is playing, it waits until finished before another notification is played, even when injecting them while a notification is not finished yet ?

I know this might not be a problem you can solve, but it’s worth asking :-)

Thx again for the wonderful software,

Benny

**Comment by hklages** [comment]
Hi. Thank you.

Regarding notification overwrite: please have a look at the wiki, example TTS. There is a function named queue. It works in combination with the catch status node.

**Comment by bdormael** [comment]
Hi,

Wow, I've tested the queue function and it works perfectly, I'm gonna
change all my nodes now to incorporate the queue function per tab.

Thanks for your kind support,

Benny

Op za 23 mei 2020 om 09:54 schreef H. Klages <notifications@github.com>:

**Comment by hklages** [comment]
your are welcome. You seems to have a very safe home. 

I close this issue now. 

Have a good time. Henning
