### ISSUE TITLE
Unable to start playlist using My-Sonos Node

### ISSUE THREAD

**Issue by martinjuhasz** [hklages/node-red-contrib-sonos-plus#60]
Hey,

i know this was raised several times in the issues but i could not figure out my problem.
I try to start playing a playlist from "My Sonos" randomly. I used the demo code from the "My Sonos" Node wiki but it fails with `get my sonos: Cannot read property 'length' of undefined ::`

This is the flow, basically taken from the example:
```
[{"id":"833ef74d.ef1e88","type":"inject","z":"f57f2ef2.84554","name":"","topic":"Songs","payload":"export","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":2932,"y":2449,"wires":[["712aabb.c92c354"]]},{"id":"712aabb.c92c354","type":"sonos-manage-mysonos","z":"f57f2ef2.84554","confignode":"89956c78.ba78d","name":"","x":3143,"y":2451,"wires":[["a1e031d.5a1bed"]]},{"id":"a1e031d.5a1bed","type":"sonos-universal","z":"f57f2ef2.84554","confignode":"89956c78.ba78d","name":"any","x":3303,"y":2451,"wires":[["25562451.8fc0bc"]]},{"id":"25562451.8fc0bc","type":"debug","z":"f57f2ef2.84554","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":3303,"y":2413,"wires":[]},{"id":"89956c78.ba78d","type":"sonos-config","z":"","name":"coordinator","serialnum":"78-28-CA-F2-00-DC:1","ipaddress":"10.0.20.7"}]
```
The playlist "Songs" is added to MySonos. 
![IMG_0118](https://user-images.githubusercontent.com/204190/81832689-18d03d00-953f-11ea-8e98-f0b6ef7ebfb3.PNG)

but basically everything fails with the same error of the example page.
I also added the universal node examples, there when i click the "TuneIn" example, it starts playing swr3 with no problem. (the tunein example of the My-Sonos node fails)

What am i doing wrong? Is there a way to start a my-sonos (or spotify) playlist using the universal node?

Thanks !

**Comment by hklages** [comment]
What sonos-plus version do you use?

**Comment by hklages** [comment]
what Node.js version do you use? It should be 10 or 12.

**Comment by martinjuhasz** [comment]
🤦 i was on 3.1.1. 
Thanks for the quick help and all your work on these libraries!

Would i be able to randomly start a my-sonos playlist using the universal node yet?

**Comment by hklages** [comment]
Not now but I guess Node-RED can do that. Use get.items and store it in a flow variable. Then use other Node-RED nodes to create "random" number between 1 and get.items array length.
