### ISSUE TITLE
get_mysonos - command in Universal Node?

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#61]
If you want to be sure: Add the TuneIn Station to My Sonos and use in get_mysonos in node "Manage Radio". The output will show the exact link and the item includes also the Radio ID.

As advised by you I used the Manage Radio node to get an AlbumURL link and the current RadioID... as Manage Radio is deprecated I do miss that feature in Universal-Node

Pls advise

**Comment by hklages** [comment]
"My Sonos", get.items
There is `payload.albumArt` and the Radio ID is in `payload.uri` 
x-sonosapi-stream:**s24903**?sid=254&flags=8224&sn=0

Does that help?

**Comment by tsprivate** [comment]
Yes, thats exactly what I was looking for .. thx a lot

**Comment by hklages** [comment]
3.1.4 is published - now get.items shows the radioId if available.

**Comment by tsprivate** [comment]
Just tested and it works great!   

thanks for implementing
