### ISSUE TITLE
Sample:  Read Favorite Stations and show in select box for playing (no issue)

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#63]
(no issue)

I just wanted to share with you a nice flow which is now possible with the new nodes.

The below flow will
- load all the stations in your favorite list including logo
- show the list in a small select list
- will start playing the selected station

have fun ;)

Thanks for this awesome node!!

`[
    {
        "id": "427f21f6.98f11",
        "type": "inject",
        "z": "a1390b9f.672798",
        "name": "",
        "topic": "",
        "payload": "get.items",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "x": 120,
        "y": 3980,
        "wires": [
            [
                "e5ef1805.c4e1d8"
            ]
        ]
    },
    {
        "id": "e5ef1805.c4e1d8",
        "type": "change",
        "z": "a1390b9f.672798",
        "name": "fav",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "get.items",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 310,
        "y": 3980,
        "wires": [
            [
                "a9125db.92399a"
            ]
        ]
    },
    {
        "id": "a9125db.92399a",
        "type": "sonos-manage-mysonos",
        "z": "a1390b9f.672798",
        "confignode": "3ff0dd25.a83542",
        "name": "study",
        "x": 450,
        "y": 3980,
        "wires": [
            [
                "5ada3403.5fdf8c",
                "8d9012b3.e4b43"
            ]
        ]
    },
    {
        "id": "5ada3403.5fdf8c",
        "type": "debug",
        "z": "a1390b9f.672798",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 570,
        "y": 3940,
        "wires": []
    },
    {
        "id": "8d9012b3.e4b43",
        "type": "function",
        "z": "a1390b9f.672798",
        "name": "Reformat for list",
        "func": "newPayload = [];\nvar xxx='';\nmsg.payload.forEach(function(entry) {\n    if(entry.type != 'Coordinator') {\n       newentry = {'SID': entry.sid, \n               'description': entry.title,\n                'icon': entry.albumArt\n      };\n      newPayload.push(newentry);\n    }\n});\n\nmsg.payload=newPayload;\nreturn msg;\n",
        "outputs": 1,
        "noerr": 0,
        "x": 640,
        "y": 3980,
        "wires": [
            [
                "24dd2264.a21f7e"
            ]
        ]
    },
    {
        "id": "24dd2264.a21f7e",
        "type": "ui_list",
        "z": "a1390b9f.672798",
        "group": "f96597f7.295c68",
        "name": "Fav",
        "order": 4,
        "width": 6,
        "height": 2,
        "lineType": "two",
        "actionType": "click",
        "allowHTML": true,
        "x": 790,
        "y": 3980,
        "wires": [
            [
                "e00bcaae.f03e98",
                "e90d0b56.339358"
            ]
        ]
    },
    {
        "id": "e00bcaae.f03e98",
        "type": "debug",
        "z": "a1390b9f.672798",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 970,
        "y": 3980,
        "wires": []
    },
    {
        "id": "e90d0b56.339358",
        "type": "change",
        "z": "a1390b9f.672798",
        "name": "track",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "payload.description",
                "tot": "msg"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "export",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 310,
        "y": 4040,
        "wires": [
            [
                "3d2320b.c059fe"
            ]
        ]
    },
    {
        "id": "3d2320b.c059fe",
        "type": "sonos-manage-mysonos",
        "z": "a1390b9f.672798",
        "confignode": "3ff0dd25.a83542",
        "name": "study",
        "x": 450,
        "y": 4040,
        "wires": [
            [
                "34cfd355.19348c"
            ]
        ]
    },
    {
        "id": "34cfd355.19348c",
        "type": "sonos-universal",
        "z": "a1390b9f.672798",
        "confignode": "3ff0dd25.a83542",
        "name": "study",
        "x": 610,
        "y": 4040,
        "wires": [
            [
                "6b077562.0d2d5c"
            ]
        ]
    },
    {
        "id": "6b077562.0d2d5c",
        "type": "debug",
        "z": "a1390b9f.672798",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 790,
        "y": 4040,
        "wires": []
    },
    {
        "id": "3ff0dd25.a83542",
        "type": "sonos-config",
        "z": "",
        "name": "Study",
        "serialnum": "78-28-CA-23-EA-CE:E",
        "ipaddress": "192.168.1.223"
    },
    {
        "id": "f96597f7.295c68",
        "type": "ui_group",
        "z": "",
        "name": "Radio",
        "tab": "457f7667.10a928",
        "order": 2,
        "disp": true,
        "width": "12",
        "collapse": true
    },
    {
        "id": "457f7667.10a928",
        "type": "ui_tab",
        "z": "",
        "name": "Sonos",
        "icon": "speaker",
        "order": 7,
        "disabled": false,
        "hidden": false
    }
]`
![image](https://user-images.githubusercontent.com/41630517/82135282-3efa2380-9844-11ea-8525-4a2a040fa9fc.png)

**Comment by hklages** [comment]
That looks really nice! 
If you like you can add it to the wiki - as a separate page. Maybe as B.2. 

I close this issue.
