### ISSUE TITLE
msg.albumArtUrl showing Sonos-IP when using Spotify Playlist

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#64]
Hi, I was just using some Spotify playlist and realized that the first entry does have the Sonos-Player-IP in the URL

msg.albumArtURL = http://192.168.1.223:1400https://i.scdn.co/image/ab67616d0000b273b0ae68e5a092871296a07cfb

and
msg.trackData.albumArtURL=
https://i.scdn.co/image/ab67616d0000b273b0ae68e5a092871296a07cfb

Is that on purpose or should they be the same ?

**Comment by tsprivate** [comment]
Just on the topic of consistency... Why is the entire content of msg.payload often redundant/duplicate to the rest of the msg ?

**E.g.:**
msg.payload.trackData  ==>  msg.trackData
msg.payload.mediaData ==> mediaData


`{"_msgid":"79371d42.8f6754","topic":"","payload":{"trackData":{"id":null,"parentID":null,"title":"bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","artist":null,"album":null,"albumArtURI":null,"position":0,"duration":0,"albumArtURL":null,"uri":"aac://http://streams.bigfm.de/bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","queuePosition":1},"artist":"unknown","title":"bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","albumArtURL":"","mediaData":{"NrTracks":"5","MediaDuration":"NOT_IMPLEMENTED","CurrentURI":"x-sonosapi-stream:s299525?sid=254&flags=8224&sn=0","CurrentURIMetaData":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"-1\" parentID=\"-1\" restricted=\"true\"><dc:title>bigFM Sunset Lounge</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id=\"cdudn\" nameSpace=\"urn:schemas-rinconnetworks-com:metadata-1-0/\">SA_RINCON65031_</desc></item></DIDL-Lite>","NextURI":"","NextURIMetaData":"","PlayMedium":"NETWORK","RecordMedium":"NOT_IMPLEMENTED","WriteStatus":"NOT_IMPLEMENTED"},"queueActivated":false,"radioId":"s299525","positionData":{"Track":1,"TrackDuration":"0:00:00","TrackMetaData":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"-1\" parentID=\"-1\" restricted=\"true\"><res protocolInfo=\"aac:*:application/octet-stream:*\">aac://http://streams.bigfm.de/bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02</res><r:streamContent></r:streamContent><dc:title>bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02</dc:title><upnp:class>object.item</upnp:class></item></DIDL-Lite>","TrackURI":"aac://http://streams.bigfm.de/bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","RelTime":"0:00:00","AbsTime":"NOT_IMPLEMENTED","RelCount":"2147483647","AbsCount":"2147483647"}},"trackData":{"id":null,"parentID":null,"title":"bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","artist":null,"album":null,"albumArtURI":null,"position":0,"duration":0,"albumArtURL":null,"uri":"aac://http://streams.bigfm.de/bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","queuePosition":1},"artist":"unknown","title":"bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","albumArtURL":"","mediaData":{"NrTracks":"5","MediaDuration":"NOT_IMPLEMENTED","CurrentURI":"x-sonosapi-stream:s299525?sid=254&flags=8224&sn=0","CurrentURIMetaData":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"-1\" parentID=\"-1\" restricted=\"true\"><dc:title>bigFM Sunset Lounge</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id=\"cdudn\" nameSpace=\"urn:schemas-rinconnetworks-com:metadata-1-0/\">SA_RINCON65031_</desc></item></DIDL-Lite>","NextURI":"","NextURIMetaData":"","PlayMedium":"NETWORK","RecordMedium":"NOT_IMPLEMENTED","WriteStatus":"NOT_IMPLEMENTED"},"queueActivated":false,"radioId":"s299525","positionData":{"Track":1,"TrackDuration":"0:00:00","TrackMetaData":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"><item id=\"-1\" parentID=\"-1\" restricted=\"true\"><res protocolInfo=\"aac:*:application/octet-stream:*\">aac://http://streams.bigfm.de/bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02</res><r:streamContent></r:streamContent><dc:title>bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02</dc:title><upnp:class>object.item</upnp:class></item></DIDL-Lite>","TrackURI":"aac://http://streams.bigfm.de/bigfm-sunsetlounge-128-aac?usid=0-0-H-A-A-02","RelTime":"0:00:00","AbsTime":"NOT_IMPLEMENTED","RelCount":"2147483647","AbsCount":"2147483647"}}`

**Comment by hklages** [comment]
Its just "historical". I strive to have all output no to msg.payload.
That is fixed in 4.0.0 - available next week.
