### ISSUE TITLE
Version 4 2020-06-09  -- MIGRATION

### ISSUE THREAD

**Issue by hklages** [hklages/node-red-contrib-sonos-plus#67]
# VERSION 4 available now

There are some changes which **might break your existing flows** in case you already use  "Universal", "My Sonos" nodes! Please take some minutes to update you flows. Feel free to open an issue or (if you don't have a github account) send an email to nrcsplus@gmail.com. I will assist you.

Flows using only "Control Player", "Get Status", "Manage Radio", "Manage Queue" should still work but it is **recommended to replace** them during the next month with "My Sonos", "Universal" nodes (in standard mode).

## Major Changes

All changes only apply to **"Universal", "My Sonos"** node!

-  According to Node-RED standards  `msg.payload` is now being used for the "message/state" (e. g. on/off, new volume, uri, ...) and` msg.topic` for the command. There is a compatibility mode that lets you still use the old style (`msg.payload` holds the command and` msg.topic` the state). This mode has to be manually activated in each node (tic box compatibility) and can be used as a work around for a limited  time (some month).

- You can now select the command and provide the state in the node. Please use that! It works in standard  and in compatibility mode.

- A few commands are renamed and the output is now always in `msg.payload` and the state input expected in ` msg.payload.`    See the detailed list of commands in the [Wiki](https://github.com/hklages/node-red-contrib-sonos-plus/wiki)

## Action required 
- All flows based on "Universal", "My Sonos" node have to be updated. Best is to edit the node, select the command and enter the state if required. If you prefer to use the "using msg" option please reverse the use of `msg.payload`, `msg.topic` (recommended) or tic the compatibility box. 

- "Universal" node: Rename the following command: `remove.sonosplaylist` to `household.remove.sonosplaylist`. 

- "My Sonos" node: Rename `queue` to `mysonos.queue.item`,` stream` to `mysonos.stream.item` and use `mysonos.get.item` to receive all items.

- "Universal" node: check the usage of `group.play.export` / `group.play.snap` in combination with  `mysonos.export.item` / `group.save.snap`. See documentation and try to use the command selection box.

- "Universal" node: states On/Off (also ins `group.create.snap`) are replaced with on/off  as everywhere else. 

- Midterm: replace "Control player", "Get Status", "Manage Radio", "Manage Queue"  with "Universal", "My Sonos" nodes - their you can select the command and enter state what makes everything much easier and more comfortable. 

## Rollback to version 3.1.5
In case you did the update to 4.0.0 but need more time to check your flows: Here are the commands to roll back to 3.1.5. Later you can use the palette to update again to 4.0.0.
```
cd ~/.node-red   // home directory and then .node-red. In Docker /data/.node-red
npm uninstall node-red-contrib-sonos-plus
npm install node-red-contrib-sonos-plus@3.1.5
```

**Comment by Morl99** [comment]
Just wanted to drop some feedback, not sure where else to put it. The new design of the nodes, with the ability to select the command directly in the node greatly simplified the use of the nodes. Thanks for that!

**Comment by hklages** [comment]
Glad to hear :-) Thanks.
