### ISSUE TITLE
How to change to Universal node?

### ISSUE THREAD

**Issue by remygiraud** [hklages/node-red-contrib-sonos-plus#68]
I saw the future deprecation of Control Player and Get Status. I am using both in this flow:

`[{"id":"e023ed05.891fc","type":"sonos-get-status","z":"84d87b47.f375b8","confignode":"76b8357d.3e9ccc","name":"Get Status","x":370,"y":660,"wires":[["173248ff.db7997"]]},{"id":"173248ff.db7997","type":"switch","z":"84d87b47.f375b8","name":"","property":"payload.modelName","propertyType":"msg","rules":[{"t":"eq","v":"Sonos Beam","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":530,"y":660,"wires":[["82ff3eec.5ac1f"]]},{"id":"82ff3eec.5ac1f","type":"change","z":"84d87b47.f375b8","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"'x-sonos-htastream:RINCON_' & \t$replace(msg.payload.MACAddress, ':', '') & \t'01400:spdif'\t","tot":"jsonata"},{"t":"set","p":"payload","pt":"msg","to":"activate_avtransport","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":680,"y":660,"wires":[["c4531aa3.77f9c8"]]},{"id":"c4531aa3.77f9c8","type":"sonos-control-player","z":"84d87b47.f375b8","confignode":"76b8357d.3e9ccc","name":"Control Player","x":860,"y":660,"wires":[[]]},{"id":"cb711fd4.e1eeb","type":"change","z":"84d87b47.f375b8","name":"Prop","rules":[{"t":"set","p":"payload","pt":"msg","to":"get_properties","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":190,"y":660,"wires":[["e023ed05.891fc"]]},{"id":"76b8357d.3e9ccc","type":"sonos-config","z":"","name":"Sonos","serialnum":"34-7E-5C-99-E5-B6:E","ipaddress":"192.168.1.12"}]`

I get how to change the Get Status (get.state with Universal), but, I can seem to find in the very good examples how to change the source (the magic syntax with RINCON...) with Universal.

Have I missed it ?

Thanks,

**Comment by hklages** [comment]
No, you didn't miss it.
Please wait until 4.0.0 - should be available latest next week. 

4.0.0 will have the missing commands from Get Status, Control Player, Manage Queue and also enable you to select the command from a drop down box.

**Comment by hklages** [comment]
Hi. Now the 4.0.0 is published. 
Be aware: you will need some minutes to change your flows. So plan some time. 

I did an update on the Wike - see [example 4](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-How-To-and-Examples)

**Comment by remygiraud** [comment]
OK. Thanks. I'll try that.  I'll publish an update if I have some issues. Continue the great job!!

**Comment by remygiraud** [comment]
Just to thank you for the great set of nodes. I eventually upgraded to 4.1 and it went like a charm. Keep up the extremely good work :)

**Comment by hklages** [comment]
Thanks for the kind feedback.
