### ISSUE TITLE
Question: What about Sonos S2

### ISSUE THREAD

**Issue by Rolf-M** [hklages/node-red-contrib-sonos-plus#69]
Hello Henning,
have you tested if the system works with Sonos S2?
Most seem to be afraid, that Sonos might have closed the underlaying API, but it seems that nobody knows...
Regards, Rolf

**Comment by hklages** [comment]
Hello Rolf. 
Yesterday evening I installed the new Android App Sonos (S2) and the app updated all Sonos player. So I assume, all my players are on S2 level. 

The test for 4.0.0 I did today and there was one issue but I fixed it (device property shows strange data).

**Comment by hklages** [comment]
Update: It seems that two of 3 out of the 68 commands have issues (all use a missing property **CurrentURI**: 
- group.get.state (CurrentURI)
- group.get.trackplus(CurrentURI) 
- group.set.queuemode

I opened and issue at node sonos.

**Comment by niwre2019** [comment]
Hallo Henning,
betreffen diese 3 Probleme auch meinen Issue Wiedergabeliste wechseln #36, oder kann ich problemlos auf die neue Software S2 updaten?
Grüße Niwre

**Comment by hklages** [comment]
Hi. I checked again. The above issues with group.get.state, .. are not related to S2.
node-red-contrib-sonos-plus works fine with S2 (so far after 2 day at my installation)

There is a small issue (not related to S2) with the above commands. In case of TV selected they throw an error. I will fix that in the next days.

**Comment by hklages** [comment]
@niwre2019 : It should work. I updated the Wike  [example 8](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-How-To-and-Examples)

**Comment by niwre2019** [comment]
@hklages : that's great, thank you very much.

**Comment by hklages** [comment]
... timed out ...
