### ISSUE TITLE
Just set a Radio Station

### ISSUE THREAD

**Issue by MaxRei-dev** [hklages/node-red-contrib-sonos-plus#7]
Hi,
wow great work. I'am only missing one function.
I want to set Playlist, Radiostations etc. without start to play them.
(eg. @04:00 i want to reset Volume, Radiostation, etc. to an defined state, so no heavy Metal in the morning when i press Play on the Sonos)
Is there a Way to do that ?
(in the moment i'am using node-sonos-http-api, but i dont see any need for this as your node provides almost anything i need)

Thank you.
greets

**Comment by MaxRei-dev** [comment]
Hi,
Thanks for that. I Use it like this.
ev. make an extra command for that?

should be no big deal:
see here:

`/**
 * Plays a uri directly (the queue stays the same)
 * @param  {String|Object}   options URI to a Audio Stream or Object with play options see `Helpers.GenerateMetadata`
 * @returns {Boolean}
 */
Sonos.prototype.setAVTransportURI = async function (options) {
  debug('Sonos.setAVTransportURI(%j)', options)

  if (typeof options !== 'string' && typeof options !== 'object') {
    return new Error('Options should be an object or a string')
  }

  // If the options is a string try to generate metadata from it
  if (typeof options === 'string') options = Helpers.GenerateMetadata(options, undefined, this.options.spotify.region)

  // We need this later.
  const self = this

  if (options.uri) {
    return this.avTransportService().SetAVTransportURI({
      InstanceID: 0,
      CurrentURI: Helpers.EncodeXml(options.uri),
      CurrentURIMetaData: Helpers.EncodeXml(options.metadata)
    }).then(result => {
      // Start playing by default, the notifications don't want to start playing by default.
      if ((!options.onlySetUri || options.onlySetUri !== true) && result) {
        return self.play()
      }
      return true
    })
  } else {
    return new Error('Error with uri')
  }
}`

thank you

**Comment by hklages** [comment]
Hi. 
1. Did the suggested flow work? Are you able to set queue/station prior to starting the player in the morning? 
2. In "control player" node there is "activate_avtransport" which uses exactly the code above.
Give it a try and let me know. It could be that I have to improve error handling.
