### ISSUE TITLE
Play MySonos.Export.Item with Universal node

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#70]
Hi, thanks for the updated nodes.

I'm currently working on the migration but struggle to play the MySonos radio stations via the Universal Node.

The below flow was working originally but after the migration i'm not getting the right URI into the universal node.

What am I doing wrong ?

![image](https://user-images.githubusercontent.com/41630517/84237369-98e8c300-ab3c-11ea-9e62-57a033ac033a.png)

Thanks for your help

`[{"id":"427f21f6.98f11","type":"inject","z":"a1390b9f.672798","name":"","topic":"","payload":"get.items","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":120,"y":3980,"wires":[["e5ef1805.c4e1d8"]]},{"id":"e5ef1805.c4e1d8","type":"change","z":"a1390b9f.672798","name":"fav","rules":[{"t":"set","p":"topic","pt":"msg","to":"mysonos.get.items","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":310,"y":3980,"wires":[["a9125db.92399a"]]},{"id":"a9125db.92399a","type":"sonos-manage-mysonos","z":"a1390b9f.672798","confignode":"3ff0dd25.a83542","compatibilityMode":false,"command":"message","state":"","stateType":"str","name":"study","x":450,"y":3980,"wires":[["5ada3403.5fdf8c","8d9012b3.e4b43"]]},{"id":"5ada3403.5fdf8c","type":"debug","z":"a1390b9f.672798","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":570,"y":3940,"wires":[]},{"id":"8d9012b3.e4b43","type":"function","z":"a1390b9f.672798","name":"Reformat for list","func":"newPayload = [];\nvar xxx='';\nmsg.payload.forEach(function(entry) {\n    if(entry.sid != '') {\n       newentry = {'SID': entry.sid, \n               'description': entry.title,\n                'icon': entry.albumArt\n      };\n      newPayload.push(newentry);\n    }\n});\n\nmsg.payload=newPayload;\nreturn msg;\n","outputs":1,"noerr":0,"x":640,"y":3980,"wires":[["24dd2264.a21f7e"]]},{"id":"24dd2264.a21f7e","type":"ui_list","z":"a1390b9f.672798","group":"f96597f7.295c68","name":"Fav","order":3,"width":6,"height":3,"lineType":"two","actionType":"click","allowHTML":true,"x":790,"y":3980,"wires":[["e00bcaae.f03e98","e90d0b56.339358"]]},{"id":"e00bcaae.f03e98","type":"debug","z":"a1390b9f.672798","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":970,"y":3980,"wires":[]},{"id":"e90d0b56.339358","type":"change","z":"a1390b9f.672798","name":"track","rules":[{"t":"set","p":"topic","pt":"msg","to":"mysonos.export.item","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"payload.description","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":310,"y":4040,"wires":[["3d2320b.c059fe"]]},{"id":"3d2320b.c059fe","type":"sonos-manage-mysonos","z":"a1390b9f.672798","confignode":"3ff0dd25.a83542","compatibilityMode":false,"command":"message","state":"","stateType":"str","name":"study","x":450,"y":4040,"wires":[["7938a373.0492fc","fedd1a03.1f2088"]]},{"id":"7938a373.0492fc","type":"debug","z":"a1390b9f.672798","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":4100,"wires":[]},{"id":"fedd1a03.1f2088","type":"change","z":"a1390b9f.672798","name":"track","rules":[{"t":"set","p":"topic","pt":"msg","to":"mysonos.export.item","tot":"str"},{"t":"set","p":"uri","pt":"msg","to":"payload.uri","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"payload.uri","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":610,"y":4040,"wires":[["34cfd355.19348c","24e03991.86b2e6"]]},{"id":"34cfd355.19348c","type":"sonos-universal","z":"a1390b9f.672798","confignode":"3ff0dd25.a83542","compatibilityMode":false,"command":"group.play.export","state":"","stateType":"str","name":"study","x":790,"y":4040,"wires":[["6b077562.0d2d5c"]]},{"id":"24e03991.86b2e6","type":"debug","z":"a1390b9f.672798","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":770,"y":4080,"wires":[]},{"id":"6b077562.0d2d5c","type":"debug","z":"a1390b9f.672798","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":970,"y":4040,"wires":[]},{"id":"3ff0dd25.a83542","type":"sonos-config","z":"","name":"Study","serialnum":"78-28-CA-23-EA-CE:E","ipaddress":"192.168.1.223"},{"id":"f96597f7.295c68","type":"ui_group","z":"","name":"Radio","tab":"457f7667.10a928","order":2,"disp":true,"width":"12","collapse":true},{"id":"457f7667.10a928","type":"ui_tab","z":"","name":"Sonos","icon":"speaker","order":7,"disabled":false,"hidden":false}]`

**Comment by hklages** [comment]
Hi. You can now simplify your flow.

I changed the function please check- only TuneIn stations. 
Take care:  you have to enter your ip address in the config node.

![flow](https://user-images.githubusercontent.com/17273119/84242529-3f16d780-ab01-11ea-9e70-958b89f936d2.png)

`[{"id":"c643fbcc.41d5c8","type":"inject","z":"8b827b01.bcb2e8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":150,"y":900,"wires":[["b6884c5c.557e1"]]},{"id":"b6884c5c.557e1","type":"sonos-manage-mysonos","z":"8b827b01.bcb2e8","confignode":"346af391.8b127c","compatibilityMode":false,"command":"mysonos.get.items","state":"","stateType":"str","name":"","x":334,"y":900,"wires":[["8caa1e87.a04ed"]]},{"id":"8caa1e87.a04ed","type":"function","z":"8b827b01.bcb2e8","name":"Reformat for list","func":"newPayload = [];\nvar xxx='';\nmsg.payload.forEach(function(entry) {\n if(entry.sid === '254') {\n newentry = {'SID': entry.sid, \n 'title': entry.title,\n 'icon': entry.albumArt\n };\n newPayload.push(newentry);\n }\n});\n\nmsg.payload=newPayload;\nreturn msg;\n","outputs":1,"noerr":0,"x":523,"y":900,"wires":[["7a09191e.b45f08"]]},{"id":"7a09191e.b45f08","type":"ui_list","z":"8b827b01.bcb2e8","group":"a0523c3c.32371","name":"Fav","order":3,"width":6,"height":3,"lineType":"two","actionType":"click","allowHTML":true,"outputs":1,"topic":"","x":673,"y":900,"wires":[["4e920791.17edd8"]]},{"id":"4e920791.17edd8","type":"change","z":"8b827b01.bcb2e8","name":"get title","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.title","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":340,"y":960,"wires":[["4ce9bffe.5a1d2"]]},{"id":"4ce9bffe.5a1d2","type":"sonos-manage-mysonos","z":"8b827b01.bcb2e8","confignode":"346af391.8b127c","compatibilityMode":false,"command":"mysonos.export.item","state":"","stateType":"str","name":"","x":521,"y":960,"wires":[["5c01b1e1.9eec"]]},{"id":"5c01b1e1.9eec","type":"sonos-universal","z":"8b827b01.bcb2e8","confignode":"346af391.8b127c","compatibilityMode":false,"command":"group.play.export","state":"","stateType":"str","name":"","x":734,"y":960,"wires":[[]]},{"id":"346af391.8b127c","type":"sonos-config","z":"","name":"Study-change ip","serialnum":"","ipaddress":"192.168.178.37"},{"id":"a0523c3c.32371","type":"ui_group","z":"","name":"Radio","tab":"d5a0d268.2373e","order":2,"disp":true,"width":"12","collapse":true},{"id":"d5a0d268.2373e","type":"ui_tab","z":"","name":"Sonos","icon":"speaker","order":7,"disabled":false,"hidden":false}]`

**Comment by tsprivate** [comment]
Thanks for the quick response .. with your updates it works perfectly !
