### ISSUE TITLE
Wrong range for *.set.volume

### ISSUE THREAD

**Issue by dprokscha** [hklages/node-red-contrib-sonos-plus#71]
The current range of the topic `*.set.volume` is 1 to 99. The range should be from 0 to 100, because this is the original range supported by Sonos. `*.get.volume` returns a range from 0 to 100.

I guess the changes you have to make relates to `sonos-control-player.js` where you check for `volume > 0 && volume < 100`. This should be `volume >= 0 && volume <= 100`.

**Comment by hklages** [comment]
You have to promise that you hear the difference between 0 and 1, 99 and 100 :-)
With the next update I will change that - maybe together with the Sonos Arc update.

**Comment by dprokscha** [comment]
Thank you! I swear that you'll hear a difference between 0 and 1. 0 is muted, 1 the lowest possible volume 😉

**Comment by hklages** [comment]
OK - so 4.0.1 is out. Please test it - especially the 100 :-) Hope you dont have neighbours. :-)

**Comment by dprokscha** [comment]
It works, even the 100 - thank you!

**Comment by hklages** [comment]
Thanks. Enjoy :-)
