### ISSUE TITLE
Support for Sonos Arc

### ISSUE THREAD

**Issue by dprokscha** [hklages/node-red-contrib-sonos-plus#72]
The brand new Sonos Arc is also a `PLAYER_WITH_TV` 😉

**Comment by hklages** [comment]
Hi. That's brand new. Please send the model name of the Sonos Arc. 

Please use Universal node, player.get.properties and send mit the payload.modelName, payload.modelDescription. 

Or send me the Sonos Arc - then I will check it :-))))

**Comment by dprokscha** [comment]
Here we go: `msg.payload.modelName: "Sonos Arc"`, `msg.payload.modelDescription: "Sonos Arc"`

I can't send you the Arc but I'm selling my Playbar if you want 😉

**Comment by hklages** [comment]
I just published 4.0.1 - please test it. 

I sold my Playbar already a few month ago and replaced it with a beam.

**Comment by dprokscha** [comment]
It works, thank you! 👍

**Comment by hklages** [comment]
Thanks for your feedback.
