### ISSUE TITLE
Group: Save queue to Sonos playlists returns error

### ISSUE THREAD

**Issue by mfw2010** [hklages/node-red-contrib-sonos-plus#75]
Firstly. These are great nodes and thanks for this. I think since the 4.0 upgrade I have this problem. It could also be because of Sonos S2 as I upgraded Sonos at the same time as well!

The second node in Example 8 (which is save queue) returns the error:

“processing input msg: statusCode 500 & upnpErrorCode 804. upnpErrorMessage >>unknown error :: Details: none"

Any ideas?

**Comment by hklages** [comment]
Thanks. 
What is in the current queue? You can use group.get.queue.
Is it a queue initiated by an app for instance Alexa or Spotify?

**Comment by mfw2010** [comment]
Hi
Yes, a Spotify playlist on Sonos.

But, strangely and embarrasingly, the issue has magically disappeared, which makes me wonder if it was something in my network! I think the issue can be closed, as it was a non issue.

Thanks

**Comment by mfw2010** [comment]
I think I found the issue, when the playlist on the player is totally empty (i.e. go to sonos controller and clear the playlist), then the univesal node with group.save.queue returns the error:

"processing input msg: statusCode 500 & upnpErrorCode 804. upnpErrorMessage >>unknown error :: Details: none"

To overcome this I added an extra Universal node with group.get.queue, and checked whether it is empty, and if empty then skip the save.queue, which seems to address the problem. 

Thanks

**Comment by hklages** [comment]
Hi. Thanks for testing. 
I will add an "is queue empty" check for the save.queue command in the next release.

**Comment by hklages** [comment]
Hi. I just published 4.1 and now an empty queue will throw error with right error message: "empty queue"
Please verify.

**Comment by hklages** [comment]
Closed as solved, time out for response.
