### ISSUE TITLE
Errors using play.notification

### ISSUE THREAD

**Issue by dxdc** [hklages/node-red-contrib-sonos-plus#76]
Thanks for creating this very useful plugin!

I'm trying to use the `play.notification` function, but having some issues.

1. I have some "bonded" stereo speakers within the Sonos app. From the instructions, it looks like I should just send the notification to one of the 2 IPs (the master)? Is that right?

2. I am using the group:play.notification function. I am not sure what the joiner version does, or why there is no "player" version?

3. I am sending the following payload to one of the speakers. It plays just fine: `https://www.myinstants.com/media/sounds/wrong-answer-sound-effect.mp3`

4. If I start a Spotify playlist (e.g., on my phone, streaming to one of the Sonos devices), then try the group.notification command, it does play the sound but then I see this error:

```
"processing input msg:statusCode 500 & upnpError 402 :: Details: Invalid Args"
```

From my understanding the playNotification function (in `node-sonos`) is supposed to resume playing?

Thanks for your help!

**Comment by hklages** [comment]
1. How do you "bound" the speakers? Is it just a group to play on all players the same music. In that case you can send the group command to any player in the group - its forwarded to the coordinator = master.

2. In a group there is always one coordinator and 0 or n joiner. The coordinator defines the music and all joiner play the same music. If you use joiner.play.notification the joiner will LEAVE the group, play the notification and then rejoin the group. The group itself will keep playing the original song. It is named joiner because it does not work for the coordinator (opposite of joiner). Maybe there will be a command coordintor.play.notification in the future. But so far no one has requested that. 

4. Starting music from the spotify or apple app is a special case. I can not restore the stream as I dont have access to your phone from NodeRED. So *.play.notification (also save.queue, ...) only work when the music has been started from any sonos app, nodered, ...

**Comment by dxdc** [comment]
thanks for the detailed reply @hklages. 

> How do you "bound" the speakers? Is it just a group to play on all players the same music. In that case you can send the group command to any player in the group - its forwarded to the coordinator = master.

I'm not sure I understand the coordinator terminology?

Essentially, within Sonos, I defined L/R speakers as a stereo pair. I didn't do anything specific within this NR plugin, but it seems you have some options to that also.

So, I only see one option in my Sonos list for this device. However, I see both devices (both IP's) listed in the config for this plugin. So, it doesn't matter which one I choose? I thought probably one should be preferred? If there is a preferred one, it would be cool if there was a way to see that from the list. I think I have seen some master/slave terminology in some Sonos plugin...

So, assuming a stereo pair built within Sonos, if I want to send a notification is this the correct way, using 'group' even though I didn't define a group anywhere?

![image](https://user-images.githubusercontent.com/7200365/85339103-11d70b80-b4a9-11ea-8328-256f31a268fa.png)

> (4). Starting music from the spotify or apple app is a special case. I can not restore the stream as I dont have access to your phone from NodeRED. So *.play.notification (also save.queue, ...) only work when the music has been started from any sonos app, nodered, ...

Ah, I guess the same situation as here? https://github.com/bencevans/node-sonos/issues/464
Thanks. I verified the behavior using the example/playNotification.js as part of the node-sonos package. It's the same error.

**Comment by hklages** [comment]
In your case you did create a stereopair. The result is that one player is hidden, the other one takes over the control. All commands should be send to the "visible" one. 
Have a look at Universal node, household.create.stereopair, household.seperate.stereopair. 

In the config node, all player in your network are shown -also the hidden player. Maybe I should change that. 

They act now as "one single" player and you should send commands to the visible one (not to the hidden on).  You can use group commands as a single player acts also as a (very simple) group, with only one player. 

Regarding stereo pair: I will improve that and provide more commands and also information in the next release. I seems that many people use that Sonos feature. There is another open issue. 

(4) Yes. Notification is a hand made feature with some restrictions.

**Comment by dxdc** [comment]
> In the config node, all player in your network are shown -also the hidden player. Maybe I should change that.

Thanks! Yes, this is how the SonosPolyTTS works. It shows the single node with "+1" after it.

**Comment by hklages** [comment]
exceeds time limit.
