### ISSUE TITLE
Q: EQ for setting Bass and Treble

### ISSUE THREAD

**Issue by AltaCursor** [hklages/node-red-contrib-sonos-plus#77]
Hello, have you thought of implementing the changing of Bass and Treble EQ settings?

This would be immensely useful as I'd like to disable bass at night to not disturb my neighbors. Thanks a lot!

**Comment by hklages** [comment]
I can implement it next week.

**Comment by AltaCursor** [comment]
Terrific! Thank you very much. Take your time.

**Comment by hklages** [comment]
Hi. I just published 4.1 with player.set|get.bass|treble

> .... night to not disturb my neighbors

Thats a great idea! Wish that  "my hotel" in Prague will also implement something similar for there TVs :-))

**Comment by AltaCursor** [comment]
Works absolutely flawlessly with my symfonisk setup! Thank you so so very much! You're the best. 

> Thats a great idea! Wish that "my hotel" in Prague will also implement something similar for there TVs :-))

Haha! Maybe now they will. :-))
