### ISSUE TITLE
Play Playlist from Music Libary

### ISSUE THREAD

**Issue by kickbutts** [hklages/node-red-contrib-sonos-plus#78]
Hi, i am trying to play a playlist from my music libary. Usind the old Nodes it works fine, but unsing the new Nodes does not work.
Injecting the name of the playlist into the old Nodes work fine, but when i am injecting the same string into the new MySonos Node by using mysonos.que.item i only get this Error Message:
processing input msg: No title matching search string >>Nervous Night.m3u : Details: none
Using the libary.get.playlist function of the MySonos Node, i can see the Playlist.
Any ideas that might help?
Thanks

**Comment by hklages** [comment]
It seems that the documentation is not sufficient - will improve next week. 

You have 2 options
a) use MySonos node, command library.queue.playlist
b) in your SONOS app, browse your playlist and add it to My Sonos. Then you can use mysonos.queue.item

Let me know if it works.

**Comment by kickbutts** [comment]
Yes working perfectly thanks.
You should modify your Section "How to and examples".
Thanks very much for you great work.
