### ISSUE TITLE
Commands Dropdown is empty

### ISSUE THREAD

**Issue by Morl99** [hklages/node-red-contrib-sonos-plus#79]
Hi,

I just upgraded to 4.0.1 from 3.x, and now the Universal Node is somehow broken. I am not sure on  how to provide enough detail for you do debug, let me know what you need and I will add the information. Here is what I know:

Node-red version:  0.20.8 (maybe I shoul update, but I could not find compatibility infos, let me know if this could be a problem)
Sonos V2 App

Issue: 
When I open the properties of the Universal or My Sonos Node, the command dropdown is empty.
![Anmerkung 2020-06-28 154339](https://user-images.githubusercontent.com/475516/85949297-396d1e80-b956-11ea-9a66-2aa754071816.png)

I recreated the node, but it does not help.

**Comment by hklages** [comment]
Hi. Could you please clear your browser cache or check whether the problem insist with another browser (Google chrome, firefox,  new Mircosoft edge). 

What browser do you use?

**Comment by Morl99** [comment]
So while writing up the issue it already occured to me, that the old node-red version (together with node 10) might be an issue. I update to node-red 1.0.6-12, node 12 and now it works well. 
Thanks for this great node-red contribution :)
