### ISSUE TITLE
Switch to TV source

### ISSUE THREAD

**Issue by remygiraud** [hklages/node-red-contrib-sonos-plus#8]
Hello,
Thanks again for your support.
My sonos beam can either be used to listen to music or radio using wifi but also as a sound bar for the TV.
To switch between the two, anynet+ usually works. It may not though. So switching through node-red (included in home assistant) to "TV" source would be good. Is that possible?
RG

**Comment by hklages** [comment]
Hello, you can play with this flow. But it just switches from any source to line in. 
It works at my beam but may depend on the TV setup. I used "sound, output: receiver or audio out"
`[
    {
        "id": "98675f74.f1036",
        "type": "sonos-get-status",
        "z": "55805384.a4695c",
        "confignode": "8d44022c.adb65",
        "name": "Get Status WZ",
        "x": 512,
        "y": 594,
        "wires": [
            [
                "86c0d02b.1fa73"
            ]
        ]
    },
    {
        "id": "bf4f295.e136dd8",
        "type": "inject",
        "z": "55805384.a4695c",
        "name": "",
        "topic": "",
        "payload": "get_properties",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 290,
        "y": 594,
        "wires": [
            [
                "98675f74.f1036"
            ]
        ]
    },
    {
        "id": "86c0d02b.1fa73",
        "type": "switch",
        "z": "55805384.a4695c",
        "name": "",
        "property": "payload.modelName",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "Sonos Beam",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 670,
        "y": 594,
        "wires": [
            [
                "3afce51f.f923fa"
            ]
        ]
    },
    {
        "id": "3afce51f.f923fa",
        "type": "change",
        "z": "55805384.a4695c",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "'x-sonos-htastream:RINCON_' & \t$replace(msg.payload.MACAddress, ':', '') & \t'01400:spdif'\t",
                "tot": "jsonata"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "activate_avtransport",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 851,
        "y": 594,
        "wires": [
            [
                "71eb7c66.941c04",
                "fa02f3c7.1fa3"
            ]
        ]
    },
    {
        "id": "71eb7c66.941c04",
        "type": "sonos-control-player",
        "z": "55805384.a4695c",
        "confignode": "8d44022c.adb65",
        "name": "Control Player WZ",
        "x": 1074,
        "y": 594,
        "wires": []
    },
    {
        "id": "fa02f3c7.1fa3",
        "type": "debug",
        "z": "55805384.a4695c",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1030,
        "y": 640,
        "wires": []
    },
    {
        "id": "8d44022c.adb65",
        "type": "sonos-config",
        "z": "",
        "name": "wz",
        "serialnum": "94-9F-3E-C1-3B-99:8",
        "ipaddress": "192.168.178.44"
    }
]`

**Comment by hklages** [comment]
I added some flow to the "How to " in the Wiki. Example E. 
Let me know if it does not work. Until then I close this topic.
