### ISSUE TITLE
player.join.group is asking for group player name

### ISSUE THREAD

**Issue by deblasioluca** [hklages/node-red-contrib-sonos-plus#82]
### Description
I'm trying to implement a flow that gets the command player.join.group to add a player to an existing group. I get the error, that the group player name is missing in the payload.

a) assumption would be, that config node would act as group player name?
b) if i want to keep it dynamic, how do I pass the group player name in the payload?

### What node/command (topic)/state (payload)?
node: Universal
command: player.join.group

Flow:
[{"id":"a4bc7f02.a3fbb","type":"http in","z":"24a91b6b.071ad4","name":"HTTP IN Sonos Control","url":"/xyz","method":"get","upload":false,"swaggerDoc":"","x":120,"y":992,"wires":[["73ef4ed4.712b9","f4138119.d0fb3"]]},{"id":"f4138119.d0fb3","type":"debug","z":"24a91b6b.071ad4","name":"Debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":714,"y":992,"wires":[]},{"id":"f4172149.7dd75","type":"sonos-universal","z":"24a91b6b.071ad4","confignode":"e65cf559.99e128","compatibilityMode":false,"command":"message","state":"","stateType":"str","name":"SonosNode: Office Luca","x":774,"y":932,"wires":[["ee0aefdc.2e947","f4138119.d0fb3"]]},{"id":"ee0aefdc.2e947","type":"http response","z":"24a91b6b.071ad4","name":"HTTP Response","statusCode":"","headers":{},"x":1020,"y":932,"wires":[]},{"id":"73ef4ed4.712b9","type":"change","z":"24a91b6b.071ad4","name":"extract topic and message","rules":[{"t":"move","p":"payload.topic","pt":"msg","to":"topic","tot":"msg"},{"t":"move","p":"payload.message","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":444,"y":932,"wires":[["f4172149.7dd75","f4138119.d0fb3"]]},{"id":"ac1e3a08.099728","type":"comment","z":"24a91b6b.071ad4","name":"Control Sonos","info":"","x":90,"y":892,"wires":[]},{"id":"e65cf559.99e128","type":"sonos-config","z":"","name":"SonosOfficeLuca","serialnum":"78-28-CA-1E-AA-40:7","ipaddress":"192.168.1.25"}]

### In case of a bug: Are you able to reproduce the error?
yes

### Versions and Infrastructure
Raspberry Pii
node-red-contrib-sonos-plus version: 4.1.0
Node-RED version: 1.0.6
NodeJS version: 10.19.0

see: https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a

**Comment by hklages** [comment]
Hi. I suggest that you first try it without the http request and use a simple inject/change. 

Assuming you want to keep it dynamic and that the real player names (see SONOS App) are "Bad", "Küche". 
If you want that Bad joins the group of "Küche"
msg.topic = group.join.player
msg.payload = küche
msg.playerName = Bad

and for the config node you can use any player (as it is overriden by msg.playerName)

`[{"id":"f778a846.2b1938","type":"inject","z":"c7dda7fc.3747d8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":540,"wires":[["3fca1c74.65ecb4"]]},{"id":"aa657262.e3e0c","type":"debug","z":"c7dda7fc.3747d8","name":"Debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":670,"y":540,"wires":[]},{"id":"3e9c4eb1.7965a2","type":"sonos-universal","z":"c7dda7fc.3747d8","confignode":"ffdc68c9.bb5618","compatibilityMode":false,"command":"message","state":"","stateType":"str","name":"","x":520,"y":540,"wires":[["aa657262.e3e0c"]]},{"id":"3fca1c74.65ecb4","type":"change","z":"c7dda7fc.3747d8","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"Küche","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"player.join.group","tot":"str"},{"t":"set","p":"playerName","pt":"msg","to":"Bad","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":340,"y":540,"wires":[["3e9c4eb1.7965a2"]]},{"id":"ffdc68c9.bb5618","type":"sonos-config","z":"","name":"x","serialnum":"94-9F-3E-C1-3B-99:8","ipaddress":"192.168.178.36"}]`

Does it help? 

PS: If you want to rebuild a SONOS REST API with Node-RED for SONOS you can also use the [sonos-ap](https://github.com/jishi/node-sonos-http-api)i

**Comment by deblasioluca** [comment]
Hi 

That was the missing link! Fantastic! Got it up and running through the http request as well. I use it to centralize house automation into one personal iOS app.

Regards,
Luca
