### ISSUE TITLE
Restrictions: When playing a radio station the commands next.track, previous.track may cause an error ...

### ISSUE THREAD

**Issue by HubertusH** [hklages/node-red-contrib-sonos-plus#85]
you can enable/disable the buttons for Next/Previous by sending a msg to them.

After group.get.trackplus insert the function:

```
msg.enabled = msg.payload.queueActivated;    

return msg;
```
and send this msg to the Buttons for Next - Previous - Repeat and Shuffle.

**Comment by hklages** [comment]
Hi, that's a good work around. 

You can also use a "catch node" and catch/ignore the error message.

In one of the next releases I will provide a group.get.xxxx command to provide the next/previous capability of a stream/queue even for stations. Some stations like Amazon allow next but not previous.

**Comment by hklages** [comment]
Now you can read the available actions for the current stream with: group.get.actions
