### ISSUE TITLE
Seek command question/possible feature request

### ISSUE THREAD

**Issue by tfer6** [hklages/node-red-contrib-sonos-plus#86]
### Description

Is it possible to use the group.seek command to jump forward or backward a specific amount of time in the current track?  Like skip ahead 30 seconds to avoid a commercial in a podcast or rewind 10 seconds.  I tried playing around with the seek command and it looks like I need to tell it a specific time in the track I'm listening to, not "+0:00:30 seconds" or "-0:01:00 minute"
### What node/command (topic)/state (payload)?
node: 
command: 
state: 

### Versions and Infrastructure
**what system:** 
**node-red-contrib-sonos-plus version:** 
**Node-RED version:** 
**NodeJS version:** 

see: https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a

**Comment by hklages** [comment]
Relative "seek" is missing. I will implement it in the next release and hope to be able to publish it by next Saturday (or one week later).

**Comment by tfer6** [comment]
Awesome. Love this node.  Great work thus far.

**Comment by hklages** [comment]
Hi. I just published 4.1.1 with group.seek.delta - format for time is +/-hh:mm:ss.
