### ISSUE TITLE
Future Request: Shuffle & Repeat

### ISSUE THREAD

**Issue by hbTecAG** [hklages/node-red-contrib-sonos-plus#89]
Hey there

Thank you for this fantastic nodes. Works fine!

Please can you add this Functions: Shuffle and Repeat for queue‘s?

Thanks

**Comment by hklages** [comment]
Hey  Thanks :-) 

Alread in:  Universal node, `group.set.queuemode` and then as state one out of the following list. I guess it is "SHUFFLE"; 

NORMAL|REPEAT_ONE|REPEAT_ALL|SHUFFLE|SHUFFLE_NOREPEAT|SHUFFLE_REPEAT_ONE)

**Comment by pyrler** [comment]
Hello

Thanks for your Feedback. I will test it today or tomorrow. 

Can you add this payloads to the table in the wiki? This will help me - and i thank also others..

**Comment by pyrler** [comment]
Hi

I have implemented the „shuffle“ function, works well. If i send shuffle, also the repeat function is in. Thats perfect for me! 

Do you have a solution for this:
Check, if actual play a radio or playlist and only wenn playlist, then send shuffle

**Comment by hklages** [comment]
good to hear. 

> Check, if actual play a radio or playlist and only wenn playlist, then send shuffle
You can use `group.get.taskplus`. That will provide a property "queueActivated". This property is true if your queue is activated (playlist, album or song).

**Comment by hklages** [comment]
> Can you add this payloads to the table in the wiki? This will help me - and i thank also others..

Done. October/Novembre when bad wheater starts I plan to improve Wiki and documentation.
