### ISSUE TITLE
Play a song at a given position

### ISSUE THREAD

**Issue by sushicodeur** [hklages/node-red-contrib-sonos-plus#9]
Hello, :)

Is it possible to play a song starting at a given position ? Or to jump to a given position of a playing song ?

Thank you

**Comment by sushicodeur** [comment]
Well, I found the lab_play_notification that does exactly what I was trying to do.

This is a very cool module you have there !

**Comment by hklages** [comment]
Thanks :-). 

Next week there will be an update and the new "play_notification" will have an option (property) to set the notification volume.

**Comment by hklages** [comment]
Hi, it is now in 0.4.4 as play_notfication (control player node). 
I close this topic now.
