### ISSUE TITLE
State changes from external

### ISSUE THREAD

**Issue by maramend** [hklages/node-red-contrib-sonos-plus#91]
Hi @hklages,

your node-red nodes allowed me to integrate SONOs into my KNX based smart home very smoothless.

However, I always work around the issue of updating states which are modified from the outside, e.g. by directly using the SONOS smartphone app or using the buttons on the loudspeaker itself. The only way I found is to use cronjobs and poll the states.

I'm wondering if there is a possibility to subscribe/register to something in SONOs which let receive state changes from SONOS itself, e.g. via callback?!

**Comment by hklages** [comment]
Hi, you have several options: 

1. Hardcore: Set up a web server and subscribe to the the events and catch them. 
[PDF](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf)

2. Wait some more "months"
My intention is to implement 1. with standard Node-RED nodes but unfortunately the http node does not support "notify". 
So I am exploring other options. 

3. Use another node in addition to sonos-plus
[sonos notify](https://flows.nodered.org/node/node-red-contrib-sonos-notify) creates a web server via node-sonos and subscribes to some events. sonos-notify and sonos-plus does not interfere - so can be used together.

**Comment by maramend** [comment]
Thx a lot @hklages , [sonos notify](https://flows.nodered.org/node/node-red-contrib-sonos-notify) - was not aware of this - made it for me.
However, I'm curious to try your solution then.

**Comment by hklages** [comment]
There is now another option for you: 

[sonos-events](https://www.npmjs.com/package/node-red-contrib-sonos-events)
