### ISSUE TITLE
Example 7 needs updating

### ISSUE THREAD

**Issue by amilanov75** [hklages/node-red-contrib-sonos-plus#92]
Hey there, firstly I love your node!

I have just tested joining and leaving groups and I can't get it to work the way you have shown in example 7 here:https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.-How-To-and-Examples

When I remove the "my sonos node"; the green one, it works fine e.g. like this:

![image](https://user-images.githubusercontent.com/23739630/92303468-0c984180-ef6d-11ea-8ded-e754ee39c842.png)

Unless I've missed something you might want to update your example as I scratched my head for quite some time before I got it working through trial and error.

**Comment by hklages** [comment]
Yes, you are right - thanks. I had changed the names and forgot to update this flow. 
End of September there will be an update with 2 new group functions - will update the documentation then. 
We leave this open as an reminder.

**Comment by hklages** [comment]
4.2.0 is online. Now it should be super easy to create / modify groups. 
Just use `household.create.group` and specify your new group by naming the SONOS player names, separated by comma. 
The first player will become the coordinator. 
Example 7 is modify. 

I close this issue.
