### ISSUE TITLE
Get Playbase TV status

### ISSUE THREAD

**Issue by thomasoggier** [hklages/node-red-contrib-sonos-plus#93]
Hi,
I use your add on on my home assistant but I don't find how to get the source selected on my playbase.
I want to know if the selected source is the TV, radio, spority or else.
I already saw the sample but I didn't get the way.
Thank you very much.

**Comment by hklages** [comment]
Hi. You may use group.get.trackplus as comment and check property currenturi.

**Comment by thomasoggier** [comment]
Hi thanks, I didn't saw this page.
Thank you!
