### ISSUE TITLE
player.get.nightmode and player.get.dialoglevel always return "on"

### ISSUE THREAD

**Issue by grishmanCH** [hklages/node-red-contrib-sonos-plus#94]
Request with new Universal node for **player.get.nightmode** and **player.get.dialoglevel** always return status "on"
Either via msg.topic or by selecting the respective command in the node itself.

Meanwhile, set.nightmode works and sets the mode correctly.
Immediate check after setting to e.g. "off", returns "on"

<img width="228" alt="image" src="https://user-images.githubusercontent.com/44230283/93388771-81bc1e80-f86b-11ea-833d-19294c369991.png">

### What node/command (topic)/state (payload)?
node: Universal | My Sonos 
command: player.get.nightmode and player.get.dialoglevel

### In case of a bug: Are you able to reproduce the error?
yes

### Versions and Infrastructure
**what system:**  docker on Ubuntu 18.04
**node-red-contrib-sonos-plus version:** 4.1.2
**Node-RED version:** 1.1.3

**Comment by hklages** [comment]
Hi. At my Sonos Beam it shows the right status. 

What player do you use? 
What does the SONOS App show: on/off?

**Comment by grishmanCH** [comment]
Hi, I do have a Beam as well. 
When I use set commands they do work and also correctly shown in the SONOS app.
However, when I try to get a status via a get node it always return "on".
When I am using old set of nodes it returns correct value e.g. off.
<img width="553" alt="Screenshot 2020-09-18 at 11 35 43" src="https://user-images.githubusercontent.com/44230283/93582869-5a686d00-f9a3-11ea-94ed-dadba75aa88d.png">
Result of all 3:
<img width="238" alt="Screenshot 2020-09-18 at 11 36 36" src="https://user-images.githubusercontent.com/44230283/93582913-6fdd9700-f9a3-11ea-9787-3b2ffec93a23.png">

**Comment by hklages** [comment]
You are right - that's a bug. 
Please try 4.1.3 - I just published it.

**Comment by grishmanCH** [comment]
@hklages Thanks, checked and it works great. I will close the issue now.
