### ISSUE TITLE
[FRAGE] I'm Search the Funktion to Test is the Player Power On or offline

### ISSUE THREAD

**Issue by gitpower2017** [hklages/node-red-contrib-sonos-plus#97]
Hello,

I'm search a methode to check is a player Power ON bzw. connectet to the IP-Network

Gruß
Lothar

**Comment by hklages** [comment]
Hello. 

Universal node provides the command `household.test.player` - use as a config file any player, which is "always on" and as payload the name of the player you would like to test - on/off. 

.... but there are some limitations. 

First of all, SONOS players are always "on" - there is no power switch off. If you remove power (with plug, or pull the line) it will take some time (maybe 5 minutes or more) until that is shown in the SONOS system and restarting also takes 1/2 to 1 minute. 

So the above command works fine in the standard situation but not if you hard stop the power supply. 

What would you like to achieve? Do you manually remove the player from power?

**Comment by hklages** [comment]
Du kannst diesen Flow probieren: 

`[{"id":"3cedf51f.6bc98a","type":"inject","z":"62cdb70e.b8cc78","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"192.168.178.37","payloadType":"str","x":140,"y":1797,"wires":[["7016e2fb.bf8a7c"]]},{"id":"8d947f7e.94d8e","type":"http request","z":"62cdb70e.b8cc78","name":"","method":"GET","ret":"txt","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","authType":"","x":530,"y":1797,"wires":[["61f44fa1.b9466"]]},{"id":"61f44fa1.b9466","type":"switch","z":"62cdb70e.b8cc78","name":"","property":"headers.server","propertyType":"msg","rules":[{"t":"cont","v":"Linux UPnP/1.0 Sonos/","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":670,"y":1797,"wires":[["75075933.593828","9e3b8c2a.de538"]]},{"id":"75075933.593828","type":"change","z":"62cdb70e.b8cc78","name":"true","rules":[{"t":"set","p":"payload","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":809,"y":1797,"wires":[["bf626131.b2648"]]},{"id":"52ddc88d.0acb28","type":"change","z":"62cdb70e.b8cc78","name":"false","rules":[{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":809,"y":1897,"wires":[["bf626131.b2648"]]},{"id":"bf626131.b2648","type":"debug","z":"62cdb70e.b8cc78","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":978,"y":1796,"wires":[]},{"id":"7de6f721.3469d8","type":"delay","z":"62cdb70e.b8cc78","name":"delay","pauseType":"delayv","timeout":"50","timeoutUnits":"milliseconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":666,"y":1897,"wires":[["52ddc88d.0acb28"]]},{"id":"9e3b8c2a.de538","type":"change","z":"62cdb70e.b8cc78","name":"reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":667,"y":1858,"wires":[["7de6f721.3469d8"]]},{"id":"7016e2fb.bf8a7c","type":"change","z":"62cdb70e.b8cc78","name":"","rules":[{"t":"set","p":"url","pt":"msg","to":"'http://' & $.payload & ':1400/info'","tot":"jsonata"},{"t":"set","p":"delay","pt":"msg","to":"10","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":340,"y":1797,"wires":[["8d947f7e.94d8e","7de6f721.3469d8"]]},{"id":"d5547acb.0c58a8","type":"inject","z":"62cdb70e.b8cc78","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"192.168.178.27","payloadType":"str","x":140,"y":1857,"wires":[["7016e2fb.bf8a7c"]]},{"id":"1ebdcaff.449b95","type":"inject","z":"62cdb70e.b8cc78","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"192.168.178.24","payloadType":"str","x":140,"y":1917,"wires":[["7016e2fb.bf8a7c"]]},{"id":"90b9692.7e68098","type":"catch","z":"62cdb70e.b8cc78","name":"","scope":["8d947f7e.94d8e"],"uncaught":false,"x":510,"y":1757,"wires":[[]]},{"id":"42232be.d3a09d4","type":"comment","z":"62cdb70e.b8cc78","name":"adjust msg.delay","info":"The delay should be more then the time needed to process the http request plus reset delay.","x":340,"y":1760,"wires":[]}]`

**Comment by gitpower2017** [comment]
Werde es resten
-- 
-- 
Lothar Schweikle-Droll

25.09.2020 09:52:05 H. Klages <notifications@github.com>:
