### ISSUE TITLE
Can't clear queue if playlist started with Spotify Connect

### ISSUE THREAD

**Issue by swissjon** [hklages/node-red-contrib-sonos-plus#98]
You can't clear/edit the queue (or can't figure out how to) if you previously started a playlist using Spotify Connect.

Steps:
-Start a playlist using the IOS app and cast if to a Sonos player (for me a Sonos One). I think this uses Spotify Connect, not Airplay II.
-If you look at the queue in the Sonos app, it will say "Started from Spotify" with a "End Session" button. 
-At this point, from my testing, it doesn't look like there is any way to clear, replace, edit the queue. 

Stop, next track, play seem to work.
Clear Queue doesn't do anything. It doesn't seem possible to start a playlist from My Sonos using Node-Red. 

Thanks,

**Comment by clboles** [comment]
I'm experiencing the same behavior where I've so far been unable to find any command that will override a playlist started from the Spotify app.

**Comment by clboles** [comment]
I've just discovered that I can regain control via group.play.track.  When music is playing that was initiated via the Spotify app, I can clear/set the queue to the playlist I want, and then send group.play.track and it starts correctly.

**Comment by swissjon** [comment]
I am very confused. I can't reproduce the problem I was having for the earlier this week. 
Steps I take to regain control from spotify:
-group.stop
-group.clear
-mysonos.queue.item
-group.play.queue

Another issue I was having was with a SonosPollyTTS voice not giving control back, but that seems to fixed now as well. 

btw, is there a forum or thread to discuss this? Not sure I want to submit issue reports each time. I will close this.

**Comment by hklages** [comment]
Hi - when you use Spotify or similar apps the control moves from the SONOS player to your smartphone. With this node we can only control the SONOS player but not your smartphone. So there may be some issues. 

But anyway you should be able to gain back control with the above commands group.stop, etc. 

SonosPollyTTS is a good package for TTS notification. But as all other packages it is not able to "block" the player. Any app or node-red-contrib-sonos-plus may disturb that. You can try to avoid to implement a queue to serialize the commands. See example [TTS](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification)

Regarding forum: There is no specific forum. Feel free to open another issue (thats fine) and read the closed topics. Some are related to this topic (Spotify, TTS, ...)
