### ISSUE TITLE
With reference to Example 8: Empty playlist kills flow

### ISSUE THREAD

**Issue by JorinL** [hklages/node-red-contrib-sonos-plus#99]
First great work thanks! :-)

I use the example 8 for saving my currents lists before one out of 32 door bell sounds is played and after that returned to current played music or just to the list without playing something.

Sometimes if the list is empty in a room the flow stops working there and this would mean my bell won't play :-D because I wait for both stereo sets to have this flow finished.

Is there a way to catch the empty list like - empty not saving/nothing to save -> go on?

![image](https://user-images.githubusercontent.com/33031729/94050411-8423f880-fdd6-11ea-8eb1-27538282845a.png)

**Comment by JorinL** [comment]
Worked around all that by using the "group.play.notification" :-)

**Comment by hklages** [comment]
... yes, group.play.notification should solve that. 
I close this issue.
